### ISSUE TITLE
App crash after install persistence helper 

### ISSUE THREAD

**Issue by unc87** [opa334/TrollStore#10]
Im using iPhone X 15.1

when i install persistence helper into some app (for example Notes), this App (notes) crash and not start 

after reboot the iphone, troll store and notes App crash and not start 

If I install troll store again it work

**Comment by skelitonlord** [comment]
If your gonna use the persistence, he specifically stated to use an app you don't use, like tips. I'm pretty sure youre not supposed to use the app it's been assigned to afterwards

**Comment by unc87** [comment]
Ok, thanks 

And is normal that TrollStore App does not work after reboot?

**Comment by opa334** [comment]
No the app should still work, it should have give you a TrollStore menu, if it crashes then something is wrong :/. You can always uninstall the notes app, reinstall it from AppStore and try again.

**Comment by unc87** [comment]
Solved after reinstall 

Thanks a lot!!!
