### ISSUE TITLE
Will you consider adding Chinese support?

### ISSUE THREAD

**Issue by Tzbfire** [opa334/TrollStore#100]
Will you consider adding Chinese support?

**Comment by Tzbfire** [comment]
会考虑添加汉化支持吗

**Comment by F-Unction** [comment]
It is a very easy-to-use tool. I don't think it needs multi-language support.

**Comment by BuLu0208** [comment]
我觉得有必要支持中文

**Comment by xiuxianchengdi** [comment]
Most of people are using English, why you think it need Chinese?

**Comment by opa334** [comment]
Duplicate of #68

**Comment by bm131488bm** [comment]
不影响 也就 几个 简单的 
It doesn't affect just a few simple words
