### ISSUE TITLE
Black Screen when lunch the replaced app

### ISSUE THREAD

**Issue by HaidarPhantom** [opa334/TrollStore#103]
hello,
i completed all steps about installing trollstore for A9 ( ip 6s ) 15.0.2,
i used "Contacts" app and "Reminders" app to replace them with trollstore individually  
but when the iphone reboots, and i open the replaced app its only lunches a black screen and nothing happening!
what should i do

**Comment by opa334** [comment]
Remove the apps, reinstall them from AppStore, try again

**Comment by verygenericname** [comment]
Those apps seem to just not work, not sure why. Tips and the AppleTV app work and are a good choice

**Comment by HaidarPhantom** [comment]
i reinstalled Tips and it worked like a charm . Thanks Guys
