### ISSUE TITLE
My bank application is not opening and is detecting an untrusted operating system.

### ISSUE THREAD

**Issue by showmak** [opa334/TrollStore#104]
My bank application threw this message, is this because I have TrollStore installed? I am not jailbroken but yesterday I have installed TrollStore and filza, and when I press Okay the application crashes.

![20220908_101839000_iOS](https://user-images.githubusercontent.com/17910813/189102717-1a85190d-7a15-4a55-be11-0a7c46d452dd.png)

**Comment by opa334** [comment]
Remove Filza and then it will work again.

**Comment by showmak** [comment]
> Remove Filza and then it will work again.

Yes it worked as you said, thanks.
