### ISSUE TITLE
what is “trollstoreinstalle” ？

### ISSUE THREAD

**Issue by HaloWww** [opa334/TrollStore#106]
Run trollstoreinstaller <uninstallablesystemapphere> (Tips is the best choice), Then run reboot, your phone will reboot into iOS

can't found the commond of  “trollstoreinstaller”

**Comment by verygenericname** [comment]
Clone the SSHRD_Script again

**Comment by verygenericname** [comment]
Actually wait i need to update the commit in the github repo, give me a minute

**Comment by verygenericname** [comment]
Ok now reclone

**Comment by verygenericname** [comment]
or run git pull

**Comment by hellotinh03** [comment]
I did "git pull" but still "command not found"

**Comment by verygenericname** [comment]
Did you recreate the ramdisk after

**Comment by hellotinh03** [comment]
Yes, I did everything as in the new instruction (expect I did git pull instead of recloning)

**Comment by verygenericname** [comment]
Maybe try recloning

**Comment by hellotinh03** [comment]
Recloning fixed the issue. Thanks!
