### ISSUE TITLE
iPhone 8 Plus can't ssh

### ISSUE THREAD

**Issue by cs59** [opa334/TrollStore#108]
So, I have a device iP8+ with 14.8 and not jailbroken becoz i don't want jb, so I decided to use the ramdisk method and i followed each step correctly and all went good, it did even show me that 'OK' on verbose booting, and after that i have to ssh the device through the this commands as mentioned 'iproxy 2222 22' & 'ssh -p2222 root@localhost', after typing the ssh command, I got connection reset error, dunno why, i tried like 3 times, first two times with latest ios 15.6.1 and then 14.8 (just for try :)}. Any help will be appreciated
![Screenshot from 2022-09-08 20-19-14](https://user-images.githubusercontent.com/68501788/189157503-790abc9b-6925-4ecb-bf64-70e82b57ff06.png)

**Comment by n0k0m3** [comment]
Please don't put the issue related to `sshrd` here, and also the solution for this is using usbmuxd2 by tihmstar (as discussed here: https://github.com/verygenericname/SSHRD_Script/issues/26)

**Comment by cs59** [comment]
> Please don't put the issue related to `sshrd` here, and also the solution for this is using usbmuxd2 by tihmstar (as discussed here: https://github.com/verygenericname/SSHRD_Script/issues/26)

Thank you so much for your reply, I will try the usbmuxd2 by tihmstar :)
