### ISSUE TITLE
Error when click button Install Trollstore in iphone 11 íos 14.4

### ISSUE THREAD

**Issue by huytorres10** [opa334/TrollStore#11]
I meet error as img, please fix for me. Thank you
![Uploading A86AC21B-CAA6-40F3-B979-4C65D0DC15EA.png…]()

**Comment by huytorres10** [comment]
Error downloading TrollStore: Error Domain=NSURLErrorDomain Code=-1020 "A data connection is not currently allowed." Install UserInfo={_KCFStreamErrorCodeKey= 50, NSUnderlyingError=0x2835a49c0 {Error Domain=kCFErrorDomain CFNetwork Code=-1020 "(null)" UserInfo={_kCFStreamErrorCodeKey= 50, KCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErr orKey=LocalDownloadTask <343F8D7D FCD9-456F-931F-9C877CA229FA>.< NSURLErrorRelatedURLSessionTaskEr 3>, rorKey=( "LocalDownloadTask <343F8D7D FCD9-456F-931F-9C877CA229FA>.< 3>" ), NSLocalizedDescription=A data connection is not currently allowed., NSErrorFailingURLStringKey=https:// github.com/opa334/TrollStore/ releases/latest/download/TrollStore.tar, NSErrorFailingURLKey=https:// github.com/opa334/TrollStore/ releases/latest/download/TrollStore.tar, _kCFStreamErrorDomainKey=1}

**Comment by opa334** [comment]
connect via wifi and try again, will check if I can fix this soon

**Comment by huytorres10** [comment]
I tried connect another wifi or 4G and restart Iphone, but this error still show. thank you

**Comment by opa334** [comment]
are you in low data mode? disable it

**Comment by huytorres10** [comment]
No, I don't enable low data mode

**Comment by opa334** [comment]
No idea, but this is definitely an issue with your connection
