### ISSUE TITLE
Troll installer crash ios 15 beta 19A5325f 

### ISSUE THREAD

**Issue by CosmoV2** [opa334/TrollStore#111]
when ever i click install it turns of my device then on but no troll store and it always does that when i click install

**Comment by opa334** [comment]
15.0 beta doesn't seem to be supported at the moment

**Comment by GeoffSI** [comment]
I've learned if you just type the number (example `15.0 without the "b2" it will still work. Im on 15.5b4 and 15.5 works fine

**Comment by opa334** [comment]
@GeoffSI You're talking about the ramdisk method, @CosmoV2 is talking about TrollInstaller.

Anyways if you are using an arm64e device, TrollInstaller2 should work for you now.
