### ISSUE TITLE
TrollStore 1.0.8 : change error code from 173 to 175 with same ipa

### ISSUE THREAD

**Issue by heinekenpsx** [opa334/TrollStore#117]
When I try with permasigner tool (by Nebula) this error appears :
[!] Failed to sign the bundle: ldid: Unsupported Mach-O type

Before with the azule tool, you said the ipa file was broken
[*]Couldn't set app rpath

v1.0.7 :
Install Error 173 The app is not signed with a fake CoreTrust certificate and Idid does not seem to be installed. 
Make sure Idid is installed in the settings tab and try again.

v1.0.8 :
Install Error 175 Failed to sign the app. Idid returned a non zero status code.

**Comment by opa334** [comment]
Well, your IPA is broken.

**Comment by heinekenpsx** [comment]
> Well, your IPA is broken.

But can it install and run normally with Appsync ?
