### ISSUE TITLE
Very long respring and uicache + freeze

### ISSUE THREAD

**Issue by chelaxian** [opa334/TrollStore#119]
I have iphone xs max 512gb ios 15.1
I have about 300+ apps installed from appstore
I installed about 30+ apps via TrollStore

and now after any installation of any app (both from appstore or trollstore no matters) each installation ends up with very long freeze (more that 1-2 minutes) and long respring after that (respring logo is smaller than it was with jailbreak on ios14 and has no spinning animation). Sometimes it even reboots device. Pressing buttons Respring / Uichache or Refresh App Registration are followed by same way befavior. Updating trollstore with tar archive gives the same problem

is it ok and normal? Or it should be fast and without respring/reboot?

**Comment by chelaxian** [comment]
Also this device was jailbroken before on ios 12-14. But i rootfs it before updating to ios 15. Btw some custom folders and files and tweak configs are still here

**Comment by opa334** [comment]
This is a stock bug, nothing to do with TrollStore

**Comment by chelaxian** [comment]
So it is ok an expected behavior?

**Comment by opa334** [comment]
it's not ok but you should tell that to apple
