### ISSUE TITLE
important FAQ

### ISSUE THREAD

**Issue by SudoFormatAll** [opa334/TrollStore#121]
there are questions that are of interest to many people and, in my opinion, should be added to the FAQ.

  if the system upgrades to Trolls unsupported version, but **without a hard reset:**
1. Will Troll itself continue to work and be able to sign new Apps?
2. If Troll itself dies, will Apps already installed by it continue to work?

**Comment by opa334** [comment]
Updating a device that has TrollStore installed will retain TrollStore but it will be unlaunchable, apps installed through it meet the same fate and the persistence helper will get overwritten by the original system app.
