### ISSUE TITLE
Clarify please update procedure

### ISSUE THREAD

**Issue by chelaxian** [opa334/TrollStore#122]
Is it needed to reinstall all IPA’s after upgrading trollstore version to fix old problems and add new improvements and support layers? Or it will be added to permasigned IPA’s automatically? Or it can be implemented by pressing “refresh apps registration” in Helper/Tips app?

**Comment by opa334** [comment]
it depends on what the update changed, some updates change stuff about the uicache implementation, there refreshing app registrations or rebuilding icon cache is enough. Other updates change stuff about the installation process, there reinstalling IPAs may be neccessary.
