### ISSUE TITLE
Idea to new version

### ISSUE THREAD

**Issue by chelaxian** [opa334/TrollStore#123]
Is it possible to add local shared folder in trollstore app? so any IPA opened and installed via TrollStore may be copied and stored in that folder localy like in AppCake or Appdb (this opportunity should be switchable through settings by on/off tumbler due to lack of free disk space on lowend models or just due to wish of an user)  and here should be button “Reinstall All stored IPA’s”. It will simplify process of manual reinstalling Apps after TrollStore updates release. When dozens of Apps already permasigned via TrollStore it is not easy and not fast to reinstall it all by hands

**Comment by opa334** [comment]
Not planned. You genereally won't have to reinstall anything anymore, there were just some issues with early versions.
