### ISSUE TITLE
BUG SIGN

### ISSUE THREAD

**Issue by Hineedhelpp** [opa334/TrollStore#127]
Hello, installing trollstore has cut me out from jailbreaking in any way. Any sideload app can not connect to my iphone, sideload uncover says that requires internet connection to verify the already trusted certificate. Tried to install uncover via trollstore but fails at 18/32 on “disabling codesignin”. Im on iphone xs ios 14.8 and i cant jailbreak anymore.. please i hope you could fix this sooner. Best regards, ill wait for  your fix!

**Comment by heinekenpsx** [comment]
Can no fix by TrollStore, sideload u0 with Altstore

**Comment by Hineedhelpp** [comment]
As i said, it has blocked me from signing from everything. Altstore says there is an error connecting on my phone, cydiaimpactor says the same, downloading u0 from online signed app it says that internet is required to verify the certificate.

**Comment by heinekenpsx** [comment]
You need to find out why can't connect the device to the pc maybe the usb cable is broken or try with another pc

**Comment by opa334** [comment]
Not caused by TrollStore. Uninstall unc0ver from TrollStore, then install it using a signing method.

**Comment by Hineedhelpp** [comment]
Ok, probably i cant explain myself better so i will try to make a better explanation. First of all, sorry for my bad english. Ok, im not new in jailbreak etc, before trollstore i was using reprovision with no issues. After the installation of trollstore and a random reboot after a couple of hours, i was not allowed to open my signed app cause it says “ no internet connection for verify the certificate” and this happens with every signing method, via pc via sideload via reprovision via everything. At this time of writing, i ve forced jailbreaking by locking the idevice while jaibrraking with u0 installed thru trollstore. Even reprovision still giving me errors for signing the apps. “Unable to connect to the servers”. Its acting like the trollstore has stopped some deamon which allows me to signing apps. So please, dont threat me like a fool, try to understand me. Its not cable related or pc related, its like something its bugged or disabled
