### ISSUE TITLE
Why did this happen?

### ISSUE THREAD

**Issue by JasmineYong** [opa334/TrollStore#128]
![6747A3FC-1424-48E4-844F-2963756FDAAB](https://user-images.githubusercontent.com/45485611/189507621-c5a6dfec-ed2c-434a-834d-de18950becc0.png)

**Comment by JasmineYong** [comment]
The day after updating the latest version, the software that passes through trollstore is not available

**Comment by heinekenpsx** [comment]
Open Trollstore helper and choose Refresh App Registrations

**Comment by opa334** [comment]
It's all explained in TrollStore itself, install the persistence helper into a system app, closing...
