### ISSUE TITLE
Unable to connect to device linux Ubuntu.

### ISSUE THREAD

**Issue by TomHarro** [opa334/TrollStore#130]
Step 1 works and then step two spits this out:
usb_timeout 5:
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

**Comment by MaximShatrov** [comment]
Solved this by using `sudo -i` before all steps

**Comment by TomHarro** [comment]
When pasting in step 2:
-bash: ./sshrd.sh: No such file or directory, when in line 1 it outputs: fatal: destination path 'SSHRD_Script' already exists and is not an empty directory.

**Comment by MaximShatrov** [comment]
My knowledge in Linux is very weak but let me try to help:
1. Open terminal again
2. type `sudo -i`
3. Type your root correct password
4. Type `git clone https://github.com/verygenericname/SSHRD_Script --recursive && cd SSHRD_Script`
5. If you have error agian, type `cd SSHRD_Script/`. If not, go to 6 
6. Run `./sshrd.sh <latestipswlinkhere> TrollStore <uninstallablesystemapphere>` with yours ipws an systemapp

**Comment by Remii10gfx** [comment]
Hey I had the same problem but after doing `sudo -i` it's now looping at the PATCH stage, left it for a while and it's still going.
any help with that?

**Comment by TomHarro** [comment]
Tried steps and still original issue of:
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

**Comment by opa334** [comment]
No idea, also the GitHub issues aren't really for support anyways
