### ISSUE TITLE
Shortcuts to automate some TrollStore actions

### ISSUE THREAD

**Issue by chelaxian** [opa334/TrollStore#132]
I want to say Thanks to you for such great application and want to share with you my shortcuts tributed to you and your work. 

I already posted it under your tweet in twitter but don’t know if you saw it.

TrollStore shortcut for ios 15:
https://routinehub.co/shortcut/12930/

TrollStore shortcut for ios 14:
https://routinehub.co/shortcut/12939/

**Comment by opa334** [comment]
Not an issue, thanks anyways
