### ISSUE TITLE
I don't know what's going on

### ISSUE THREAD

**Issue by king207** [opa334/TrollStore#134]
I use an iphone X on IOS 15.3.1 after giving it to install in trollhelper after a while I get this
![WhatsApp Image 2022-09-11 at 2 31 25 PM](https://user-images.githubusercontent.com/50456492/189527805-759b4ce4-c1a9-4a8f-ab13-41763fc22e2d.jpeg)

**Comment by opa334** [comment]
That's an issue with your device's internet connection. Fix it and then the button should work.
