### ISSUE TITLE
ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by yansilveira00** [opa334/TrollStore#135]
After the second step, on iPhone 8 15.5b4, the following error appears:

waiting for dfu mode device
ERROR: Unable to connect to device
ERROR: Unable to connect to device
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

Any idea to solve?
OS: Linux Mint

**Comment by lustime** [comment]
not support vm

**Comment by yansilveira00** [comment]
> not support vm

and live cd?

**Comment by lustime** [comment]
> > not support vm
> 
> and live cd?

i dont know. same with you on vm.then install a ubuntu sys. it work

**Comment by yansilveira00** [comment]
> > > not support vm
> > 
> > 
> > and live cd?
> 
> i dont know. same with you on vm.then install a ubuntu sys. it work

thankss
