### ISSUE TITLE
BUG SIGN DONT CLOSE

### ISSUE THREAD

**Issue by Hineedhelpp** [opa334/TrollStore#137]
You have closed mine without understanding the issue and without fixing it so i will re explain everything more clearly. Ok, probably i cant explain myself better so i will try to make a better explanation. First of all, sorry for my bad english. Ok, im not new in jailbreak etc, before trollstore i was using reprovision with no issues. After the installation of trollstore and a random reboot after a couple of hours, i was not allowed to open my signed app cause it says “ no internet connection for verify the certificate” and this happens with every signing method, via pc via sideload via reprovision via everything. At this time of writing, i ve forced jailbreaking by locking the idevice while jaibrraking with u0 installed thru trollstore. Even reprovision still giving me errors for signing the apps. “Unable to connect to the servers”. Its acting like the trollstore has stopped some deamon which allows me to signing apps. So please, dont threat me like a fool, try to understand me. Its not cable related or pc related, its like something its bugged or disabled

**Comment by opa334** [comment]
I understand your issue but I simply can't help you, I unfortunately don't have a magic ball. All I can tell you is that I think TrollStore is not involved here, there is no way that TrollStore could cause something like this but you can always try uninstalling it in settings, it will revert every change done by TrollStore.
