### ISSUE TITLE
ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by gorouchan** [opa334/TrollStore#140]
![Trollstore](https://user-images.githubusercontent.com/64213053/189543397-c936f44b-3e3b-4a6d-bd9e-2c1a504a77dc.png)

When typing ./sshrd.sh latest ipsw link, the prompt will say waiting for dfu mode device but once I enter DFU mode on my iPhone (X, 15.4.1), the ERROR: Unable to connect to device will show up and it will be stuck there. What's the problem? I already enabled allowing accessories while locked as well as disabling Find my iPhone in iCloud. I've also tried different USB ports and cable, restarting PC, and reinstalled SSHRD script in case something went wrong during the installation. I'm using a fresh install of Ubuntu 22.04.1 via dual boot so I'm not using a VM.

**Comment by groyner** [comment]
write "sudo" before the "./sshrd.sh" command
solved for me

**Comment by gorouchan** [comment]
> write "sudo" before the "./sshrd.sh" command solved for me

Thanks! I was able to proceed to next step but there's another problem. When I do these steps:

in a new terminal window, run iproxy 2222 22

In the previous window, run ssh -p2222 root@localhost, the pass is alpine

the following error shows up in the main window: kex_exchange_identification: read: Connection reset by peer
and the following error shows up in the new window: No connected device found, terminating.

I don't know if this might be the cause but when I did  the ./sshrd.sh <latestipswlinkhere> command, get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x39a7b5
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x12d2da4
these two errors showed up in the terminal but it still said "we are done, please use ./sshrd.sh boot to boot your device
cleanup..." So I just proceeded to the next step. I'm not quiet sure what the problem is

**Comment by gorouchan** [comment]
It seems to have been fixed by capitalizing the -P in `ssh -p2222 root@localhost` and properly asks for a password now. But it returns a new error: `Permission denied, please try again.` and after repeating it three times, `root@localhost: Permission denied (publickey,password).`

I enabled PermitRootLogin in sshd_config but it didn't fix it. I also found out in auth.log that it seems to listen to different port from 2222 e.g 
`Sep 12 13:28:58 Cet sshd[17110]: Failed password for root from 127.0.0.1 port 54560 ssh2`

So I'm guessing that the command -P2222 (Uppercase) isn't working? but the problem is neither does lower case -p as mentioned in the above comment. I have also tried -p 2222 with a space.

**Comment by groyner** [comment]
i don't know, i didn't do that proxy part

**Comment by JMillz269** [comment]
The proxy part is if you are using sshrd script for other purposes. Use the full command listed from the ssh ramdisk guide here on trollstore's github page with sudo in front of it.

**Comment by gorouchan** [comment]
Huh. That was so easy, I was following [this one](https://github.com/opa334/TrollStore/blob/1b662f645a62189014055dfd8b003054da9b0d52/install_with_sshrd.md)
