### ISSUE TITLE
Spotlight Search does not show any apps. 

### ISSUE THREAD

**Issue by chiefx2** [opa334/TrollStore#144]
None of the apps appear when searching for them on the iPhone.

**Comment by chiefx2** [comment]
> None of the apps appear when searching for them on the iPhone.

It is very intermittent. I’ve tried respringing, rebooting and it did not work. Then it started working few minutes after rebooting and it’s again now working.

**Comment by opa334** [comment]
no idea and whatever this is probably cannot be fixed

**Comment by cspencer49519** [comment]
I've noticed this issue as well. I'm on an iPhone 12 pro max on iOS 15.0. What fixes it for me, is to swipe left to search via spotlight, click in the search box, then click any of the apps under "Siri Suggestions", without searching anything. After that, spotlight seems to work properly. Not sure if this might help you in diagnosing the issue.
