### ISSUE TITLE
SSHRD don't work well in iPad 6th A10 iPadOS15.4.1

### ISSUE THREAD

**Issue by labulac** [opa334/TrollStore#149]
![截屏2022-09-12 下午11 36 31](https://user-images.githubusercontent.com/35835318/189696320-b56a7f51-42e3-4186-b5a1-9f75764351f8.png)

failed

**Comment by verygenericname** [comment]
Is this a hackintosh? What CPU?

**Comment by labulac** [comment]
> Is this a hackintosh? What CPU?

yes,but when i use the ubuntu22 to reSSHRD,also failed

**Comment by labulac** [comment]
i will try again
