### ISSUE TITLE
uyou youtube can't download media

### ISSUE THREAD

**Issue by firashacker** [opa334/TrollStore#154]
when it finishes downloading it can't move it from the tmp folder into the documents folder ( i think theres an issue realated to permissions)

**Comment by opa334** [comment]
Update to latest TrollStore, reinstall uYou IPA

**Comment by firashacker** [comment]
> Update to latest TrollStore, reinstall uYou IPA

how i can update i don't have any options to update in trollhelper nor in trollstore

**Comment by opa334** [comment]
open the latest TrollStore.tar from releases in TrollStore
