### ISSUE TITLE
missed messages

### ISSUE THREAD

**Issue by ramunozp** [opa334/TrollStore#155]
I lose link with whatsapp web, I lose messages and I can't even recover them

![image](https://user-images.githubusercontent.com/24207310/189948587-3c6ce2e3-8db9-44ba-8e8e-7f2fdaffa3b9.png)

![image](https://user-images.githubusercontent.com/24207310/189948757-b5894772-af2e-48ea-9a51-c976f471a224.jpeg)

**Comment by opa334** [comment]
Update to latest TrollStore, install proper WhatsApp IPA from Fouad Raheb github, make sure to use the one that says TrollStore.
