### ISSUE TITLE
CarPlay Entitlement for Apps

### ISSUE THREAD

**Issue by ChipSkylark37** [opa334/TrollStore#158]
Hello,

I am unable to find a definitive answer if TrollStore includes entitlements for CarPlay Apps, as it does for Notifications, etc.

There are two Apps that I am testing with:

Spotify++ 58.7.64.518 (Though version does not seem to matter) - Premium features unlocked
Youtube Music 1.19 (Version, again, does not matter) - Premium features unlocked like Download, Offline Playback, Background Playback

When connected via CarPlay:

Spotify does not show up as an App at all, nor does it show in the CarPlay Settings in iPhone. If you play a song via the iPhone, it will show up under 'Currently Playing' but if you click to open it full screen, it opens Apple Music instead. The Spotify app itself is never available on CarPlay.

Youtube Music, however, does show in CarPlay Settings and on the CarPlay App. When you open it, it states you need YouTube Premium and does not let you use the App at all.

Does TrollStore include a way to sign for these entitlements? Normal signing services have the same issue, but I thought TrollStore allowed for this, similar to how it works with Notifications and other iPhone / App Entitlements.

If this is not currently a feature, could it be or is that outside of the possibility?

**Comment by opa334** [comment]
The IPAs you're trying to use probably have had their entitlements or app plugins stripped.

**Comment by ChipSkylark37** [comment]
Does TrollStore support CarPlay, if the entitlements weren't stripped? 

If that is confirmed, I will review for alternative apps that have not had it removed. 

Is there a way to know if it contains them or not?

**Comment by opa334** [comment]
The two factors at play here are

1. TrollStore apps are registered as system apps

2. TrollStore has to use it's own uicache implementation, bypassing the stock one

So the questions you want to be asking are

1. Can system apps have CarPlay plugins

2. Is the uicache implementation of TrollStore good enough to get them to show up

The answer to 1 is: Probably, yes

The answer to 2 is: No clue

You can test by getting an unmodified IPA of an app that has CarPlay support (best if you dump it yourself with jailbroken device + Iridium) and installing that.

**Comment by ChipSkylark37** [comment]
Confirmed that with an unmodified IPA, it does show up in CarPlay. That means the entitlements are somehow (or intentionally) being stripped from the tweaked versions.

**Comment by ChipSkylark37** [comment]
Hello,

As an update, I took an unmodified IPA, downloaded the .deb for spotilife, and merged the two with Azule. This worked fine and was able to use Spotify with CarPlay as desired. 

So this means all of the current modified IPA files are stripping out the entitlements.

Thanks for the suggestion to test.

**Comment by jonas1227github** [comment]
> Hello,
> 
> As an update, I took an unmodified IPA, downloaded the .deb for spotilife, and merged the two with Azule. This worked fine and was able to use Spotify with CarPlay as desired.
> 
> So this means all of the current modified IPA files are stripping out the entitlements.
> 
> Thanks for the suggestion to test.

Hello, any news on sideloaded spotify++ with carplay?
