### ISSUE TITLE
[Suggestion] Add installed app info

### ISSUE THREAD

**Issue by AymenKcm1** [opa334/TrollStore#16]
Is it possible to add this so when we tap on an installed app in TrollStore's list it shows the app's info like version, Bundle ID, size...

Thanks.

**Comment by AymenKcm1** [comment]
Or maybe make the list look like this to have more info on the installed apps.

![image](https://user-images.githubusercontent.com/67245917/188290331-64ee022e-4814-48fd-a662-b4b5dd7fd0ad.jpeg)

**Comment by opa334** [comment]
yes it's very possible, but I don't have time for it, TrollStore is open for contributions so someone else can do it maybe

**Comment by AymenKcm1** [comment]
OK no problem 😉 the app is great as it is 🙂 as long as it is functional I'm more than satisfied with it 😘

**Comment by opa334** [comment]
This was added a while ago
