### ISSUE TITLE
Linux, ios 15.5b4, can't install, show warning please install iproxy first

### ISSUE THREAD

**Issue by kimihime96** [opa334/TrollStore#161]
while i run sshrd script showing warning "please install iproxy first"
how to fix it ?

**Comment by opa334** [comment]
you fix it by installing iproxy?

**Comment by thunderfurry** [comment]
Warning: No available formula with the name "libimobiledevice".

**Comment by HunterBoy344** [comment]
How do you install iproxy? I can't seem to install it with apt-get install

**Comment by labulac** [comment]
> How do you install iproxy? I can't seem to install it with apt-get install

i have the same question,how to install?

**Comment by opa334** [comment]
brew install libusbmuxd

or

apt-get install libusbmuxd
