### ISSUE TITLE
SSHRD not booting after verbose

### ISSUE THREAD

**Issue by shadyNeon** [opa334/TrollStore#162]
my phone 6S after trollstore verbose does not do anything, i am not 100% sure if it meant to auto boot. but by the looks of it (and a 20 min wait) something didnt go right. any ideas why?

**Comment by verygenericname** [comment]
What’s it say, does it say OK in ascii? If it does that means you have an old ssh tar

**Comment by AymenKcm1** [comment]
I have OK in ascii, and waited but no boot. 
What to do then? 
Where to get a newer SSH tar ? 
Do I just delete the repo files and clone it again?

**Comment by verygenericname** [comment]
Yes. Delete and clone again

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
