### ISSUE TITLE
ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by Dialgatrainer02** [opa334/TrollStore#164]
hi,i have an iphone  running 15.5b4 i have it in dfu mode and i am getting this error i have tried difrent usb ports to no avail after 3 tries connceting i get a diffrent  error message "jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
[-] An error occurred"

**Comment by Dialgatrainer02** [comment]
fixed using sudo now have a diffrent error "init pzb: 
Error init failed
[-] An error occurred"

**Comment by SARankDirector-Minecraft** [comment]
Mine works all through the first script with but trying sshrd boot, gives the same error

**Comment by tienanhdz00** [comment]
> hi,i have an iphone running 15.5b4 i have it in dfu mode and i am getting this error i have tried difrent usb ports to no avail after 3 tries connceting i get a diffrent error message "jq: error (at :1): Cannot index number with string "firmwares" parse error: Invalid numeric literal at line 1, column 9 [-] An error occurred"

How to fix?

**Comment by Dialgatrainer02** [comment]
Run with sudo

**Comment by SARankDirector-Minecraft** [comment]
Sudo doesn't work on the second script though

**Comment by SARankDirector-Minecraft** [comment]
It still has the problem

**Comment by abdothiss** [comment]
> It still has the problem 

did you fix it

**Comment by SARankDirector-Minecraft** [comment]
No, the second script still has the same error message, even with sudo
