### ISSUE TITLE
After rebooting troll not showing!

### ISSUE THREAD

**Issue by Mabastcity** [opa334/TrollStore#166]
I do everything and i put my phone to dfu mode with my hand then it’s working and i see troll face but my phone no rebooting and one time it’s happening and when i turn on my phone I don’t see anything in home screen, and i see something when i trying i see internal error before seeing trollface in terminal, and 
I wass use sudo to doing but idk what should i do please help!
Ip8+ 15.5.b1 linux

**Comment by opa334** [comment]
what? You need to launch the app you replaced and install TrollStore through it.

**Comment by Mabastcity** [comment]
After seeing trollface my phone is  froze in dfu mode ane when i turn on phone agaian I can't see any app installed!

**Comment by opa334** [comment]
Of course you don't see any app installed, as I already told you, launch the app you replaced.
