### ISSUE TITLE
Ipad air 2 support

### ISSUE THREAD

**Issue by seropigeorgedev** [opa334/TrollStore#171]
Plz add ipad air 2 support

**Comment by opa334** [comment]
Won't happen until Fugu15 is out

**Comment by 5718KB** [comment]
> 现在可能已经成功了，因为它运行成功了

请问您有成功吗？我的设备是air2 系统15.8.2，并不可行

**Comment by seropigeorgedev** [comment]
> > 现在可能已经成功了，因为它运行成功了
> 
> 
> 
> 请问您有成功吗？我的设备是air2 系统15.8.2，并不可行

Trollstore not only runs but also works as intended on my Ipad Air 2 (15.0) it should also work on your version take a look here: https://ios.cfw.guide/installing-trollstore/

**Comment by 5718KB** [comment]
> > > 现在可能已经成功了，因为它运行成功了> >> >> > 请问您有成功吗？我的设备是air2系统15.8.2，不可行>> Trollstore不仅运行，而且在我的Ipad Air 2（15.0）上也正常工作，也应该适用于您的版本，请查看此处：https://ios.cfw.guide/installing-trollstore/非常高兴你成功运行，至少说明trollstore是支持A8x，由于15.8.2运行方法和你不同，官方展示的方法对我不可用，我目前还没找到安装方法

**Comment by Tarikko-ScetayhChan** [comment]
诶？巨魔支持这样一款老机型？
如果碰巧是的话，我也有一台Air 2设备（2914年）

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 5718KB ***@***.***>
发送时间: Wednesday, April 17, 2024 9:57:53 PM
收件人: opa334/TrollStore ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [opa334/TrollStore] Ipad air 2 support (Issue #171)


现在可能已经成功了，因为它运行成功了> >> >> > 请问您有成功吗？我的设备是air2系统15.8.2，不可行>> Trollstore不仅运行，而且在我的Ipad Air 2（15.0）上也正常工作，也应该适用于您的版本，请查看此处：https://ios.cfw.guide/installing-trollstore/非常高兴你成功运行，至少说明trollstore是支持A8x，由于15.8.2运行方法和你不同，官方展示的方法对我不可用，我目前还没找到安装方法<https://ios.cfw.guide/installing-trollstore/%E9%9D%9E%E5%B8%B8%E9%AB%98%E5%85%B4%E4%BD%A0%E6%88%90%E5%8A%9F%E8%BF%90%E8%A1%8C%EF%BC%8C%E8%87%B3%E5%B0%91%E8%AF%B4%E6%98%8Etrollstore%E6%98%AF%E6%94%AF%E6%8C%81A8x%EF%BC%8C%E7%94%B1%E4%BA%8E15.8.2%E8%BF%90%E8%A1%8C%E6%96%B9%E6%B3%95%E5%92%8C%E4%BD%A0%E4%B8%8D%E5%90%8C%EF%BC%8C%E5%AE%98%E6%96%B9%E5%B1%95%E7%A4%BA%E7%9A%84%E6%96%B9%E6%B3%95%E5%AF%B9%E6%88%91%E4%B8%8D%E5%8F%AF%E7%94%A8%EF%BC%8C%E6%88%91%E7%9B%AE%E5%89%8D%E8%BF%98%E6%B2%A1%E6%89%BE%E5%88%B0%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95>

―
