### ISSUE TITLE
install trollstore tho linux 

### ISSUE THREAD

**Issue by parkhassan** [opa334/TrollStore#172]
![Screenshot_20220915_182206_com android gallery3d](https://user-images.githubusercontent.com/44109930/190443257-5dd5294e-4f1d-445e-a587-2d17dae20901.jpg)

**Comment by sharklatan** [comment]
Same error Ubuntu 20.04.x and 21 try another distro

**Comment by abdothiss** [comment]
did you fix it?

**Comment by labulac** [comment]
use the latest ubuntu can fix it.

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
