### ISSUE TITLE
sudo ./sshrd boot unable to get device configuration

### ISSUE THREAD

**Issue by Dialgatrainer02** [opa334/TrollStore#173]
after last time i am running with sudo and get the error "ERROR: Unable to set device configuration
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
[-] An error occurred"

**Comment by verygenericname** [comment]
Make an issue over at the SSHRD_Script repo and provide a full log please
