### ISSUE TITLE
The app is not cleanly uninstalled.

### ISSUE THREAD

**Issue by hapi888** [opa334/TrollStore#175]

**Comment by hapi888** [comment]
![image](https://user-images.githubusercontent.com/51910676/190611125-9b332a55-0518-4d50-84c5-882e23f17ef2.png)

**Comment by opa334** [comment]
need more info, what's the problem?

**Comment by hapi888** [comment]
My device is A13 iOS15.1 TrollStore 1.0.10 I uninstall pubgm. That's it.

**Comment by hapi888** [comment]
> need more info, what's the problem?

My device is A13 iOS15.1 TrollStore 1.0.10 I uninstall pubgm. That's it.

**Comment by AymenKcm1** [comment]
Try " Rebuild Icon Cache " and " Respring "

![image](https://user-images.githubusercontent.com/67245917/190918560-55602391-b1cc-4eb5-9fa4-944e0c982456.jpeg)
