### ISSUE TITLE
Sshrd boot stuck

### ISSUE THREAD

**Issue by Dialgatrainer02** [opa334/TrollStore#176]
Then loading the ramdisk file it get stuck at 1.2 and timesout i havw tried recreating the ramdisk several times all to the same error

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
