### ISSUE TITLE
Instagram apps iPad layout.

### ISSUE THREAD

**Issue by thuanma** [opa334/TrollStore#179]
Is it possible to make an option to change the layout screen between the iPad layout version and an iPhone layout version.![image](https://user-images.githubusercontent.com/49478576/190860402-f134a96d-04d6-49fc-a1ad-337e25d13c9f.png)![image](https://user-images.githubusercontent.com/49478576/190860417-bb2b6d9e-56dc-4739-a815-a6fdcd221514.png)

**Comment by skelitonlord** [comment]
This isn't trollstore related. At all.

**Comment by skelitonlord** [comment]
So your saying trollstore can change an actual app interface that's built into an app? Even though the standard iOS app doesn't have an ipad version?

**Comment by opa334** [comment]
The system doesn't realize that an app installed by TrollStore does not support iPads so it will display it in full screen but the user interface will look broken

**Comment by skelitonlord** [comment]
Huh, I haven't had this happen on any of the apps I've installed

**Comment by TheOrbOfDestiny** [comment]
I installed the old EA iPhone version of Monopoly on my iPad earlier via TrollStore and it’s in a stretched full screen that looks terrible. I hope one day this issue gets fixed.

**Comment by opa334** [comment]
Duplicate of #94

**Comment by badger200** [comment]
The PoomSmart tweak AppPad brilliantly adapts most apps to work full screen on iPad in proper Retina. I wonder if there's a way for TrollStore to integrate that .dylib on iPad apps? I've been using it on my jailbroken devices Instagram for 3+ years and it's absolutely incredible.

**Comment by opa334** [comment]
Technically yes, but you'd be better off injecting it into the IPA yourself. Injecting tweaks from inside TrollStore isn't something I intend to add.
