### ISSUE TITLE
Error init failed

### ISSUE THREAD

**Issue by iremixdev** [opa334/TrollStore#181]
Error Code
`
init pzb:
Error init failed
`

**Comment by midokof** [comment]
Type ./sshrd.sh <latest ios version> TrollStore Tips
ex:./sshrd.sh 15.7 TrollStore Tips

**Comment by midokof** [comment]
Type ./sshrd.sh  latest ios version TrollStore Tips
ex:./sshrd.sh 15.7 TrollStore Tips

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
