### ISSUE TITLE
Ramdisk doesnt exsist apparently

### ISSUE THREAD

**Issue by k3nethh** [opa334/TrollStore#182]
Using iPhone X on iOS 15.4.1 and Ubuntu 20.04
After running sudo ./sshrd.sh 15.4.1 TrollStore Tips it goes fine until the end where it says

Error: file Firmware/.trustcache does not exist, or is a directory
[-] An error occurred

After running sudo ./sshrd.sh boot it says

[*] Getting device info... this may take a second
[-] Please create an SSH ramdisk first!
![Screenshot from 2022-09-17 18-57-58](https://user-images.githubusercontent.com/113806376/190878947-138787f2-2ca9-49a6-a190-9159596b185a.png)

**Comment by abdothiss** [comment]
please i would like to know if u fix it

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
