### ISSUE TITLE
Error: file Firmware/.trustcache does not exist, or is a directory

### ISSUE THREAD

**Issue by abdothiss** [opa334/TrollStore#183]
![image](https://user-images.githubusercontent.com/113380633/190879328-02da8fa0-6500-4ce2-8577-4da01faccb30.jpeg)

i keep get this error when i try to install trollstore on ios15.4 A10

**Comment by verygenericname** [comment]
Need to statically compile

**Comment by abdothiss** [comment]
> Need to statically compile

but i don't know how to fix it
