### ISSUE TITLE
安装unc0ver越狱软件后，无法正常越狱

### ISSUE THREAD

**Issue by hfkj520** [opa334/TrollStore#184]
为什么用永久签名软件安装unc0ver越狱软件，进行越狱总是到18，越狱不了、要不就是重启，要不就是卡到18进度，试了不低于10次都不行
![C417E9C4-89F9-49A2-875B-0FC76E4874D0](https://user-images.githubusercontent.com/107908999/190892775-e2ac3c97-fb04-430f-83b4-3bd8f46ae928.png)

**Comment by opa334** [comment]
not fixable
