### ISSUE TITLE
App process kept running even after removing the app

### ISSUE THREAD

**Issue by AymenKcm1** [opa334/TrollStore#187]
I noticed today that my iPhone was getting hot when using it, so I opened CocoaTop to check what's causing that and I found out that it was a process of an app (TouchSprite) I recently installed AND REMOVED

![image](https://user-images.githubusercontent.com/67245917/190917864-6e708695-5d09-47f8-8d1e-0912d8ab75cd.jpeg)

I checked again in TrollStore to confirm that it was indeed not installed 

![image](https://user-images.githubusercontent.com/67245917/190917902-d3df0ded-8069-410b-b58d-eead5018bc9c.jpeg) 

I downloaded the app to check it and try it from here: 

https://github.com/34306/TrollStoreiPA/releases/tag/TS_iPA

I didn't even use it, when I saw that it was in a non-English language that I can't understand I removed it immediately.

Edit: I tried a respring and it didn't do anything, but killing the process in CocoaTop seems to solve the problem.

I don't know if this is a system bug or a TrollStore bug.

**Comment by verygenericname** [comment]
That’s normal with iOS 15

**Comment by verygenericname** [comment]
Wait are you on 15, I see u0

**Comment by AymenKcm1** [comment]
I like to keep it to help with the jailbreak waiting process 😅 

(I also have Taurine 🤷‍♂️ and Zebra to browse repos 😂)

+ If I ever needed to explain something u0 related to someone I like to have the app to take screenshot and then annotate it 😉

**Comment by opa334** [comment]
Yeah so I never thought of this before, but it would probably be a good idea to kill an app when uninstalling it... Will be added soon.

**Comment by AymenKcm1** [comment]
Great, thanks 👍

**Comment by opa334** [comment]
Fixed in 1.1
