### ISSUE TITLE
[Suggestions] Of course if you had the time for it

### ISSUE THREAD

**Issue by AymenKcm1** [opa334/TrollStore#188]
Useful for people like me who have a lot of installed apps.

1. Search bar (top)
2. Total installed apps (bottom)

![image](https://user-images.githubusercontent.com/67245917/190935706-7678ed4d-5691-4d02-8dd4-b7e5aafb0da0.jpeg)

Thank you for the great work you've done so far 😊

**Comment by opa334** [comment]
Search bar is implemented in 1.3.

Don't see a point in adding the count though.
