### ISSUE TITLE
Stuck on [*] Getting device info... this may take a second

### ISSUE THREAD

**Issue by aligassan** [opa334/TrollStore#191]
IPhone Xs Max 
Software Version 15.4.1 
Model Nu A1921

Stuck on [*] Getting device info... this may take a second

**Comment by itsnebulalol** [comment]
you can't use an ssh ramdisk on a12+

**Comment by aligassan** [comment]
> you can't use an ssh ramdisk on a12+

So there is no way to install TrollStore on a12+ ?!
