### ISSUE TITLE
iphone6s Tips：Not a option, TrollStore or Pogo

### ISSUE THREAD

**Issue by lyl815616** [opa334/TrollStore#192]
./sshrd.sh 15.3.1 TrollStore Tips
[*] Getting device info... this may take a second
[-] Not a option, TrollStore or Pogo

I have tried other versions too，like 15.6.1 -15.0

**Comment by lyl815616** [comment]
Forgot to mention, my mac is M1 chip

**Comment by itsnebulalol** [comment]
iirc this was fixed, `git pull` and try again

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
