### ISSUE TITLE
Ipad mini 6 Delta emulator crashing when + button is pressed

### ISSUE THREAD

**Issue by nyc709** [opa334/TrollStore#193]
Correct me if im wrong, i think app plug in dont work?

im using ipad mini 6 on ios 15.1
Installed trollstore 1.0.10
Installed idid
Installed helper via tips

Installed delta emulator without issues
But when i open it and click the + button, it will crash
Also when i check controller skins on settings nothing is showing, even when i try to add skins, nothing is showing. See attached pic

please help.

tried restart, respring, refresh app registration. It didnt work
Tried rebuild icon cached and after i pressed, it shows black screen only. Still did not work.see attached pic
![99869F4E-0E04-458C-882E-AD617112BEFA](https://user-images.githubusercontent.com/81462574/191206511-3eebeb6a-f890-46e2-a687-5af3a17bc1a1.png)

![F09D66C6-50D6-4808-B5FF-BF1C610A2EF0](https://user-images.githubusercontent.com/81462574/191205910-6b1eaa7f-5117-46d6-8d8e-7ca6281eebcf.png)

**Comment by Heroes181** [comment]
this is the only solution i found https://m.box.com/shared_item/https%3A%2F%2Fapp.box.com%2Fs%2F6c0d092snos9k821d2giwwj7na9fujkh

**Comment by nyc709** [comment]
> this is the only solution i found https://m.box.com/shared_item/https%3A%2F%2Fapp.box.com%2Fs%2F6c0d092snos9k821d2giwwj7na9fujkh

Thank you very much.
