### ISSUE TITLE
two question?(my device is iphone8plus CDMA,15.4.1)

### ISSUE THREAD

**Issue by xaxazzzz** [opa334/TrollStore#194]
1,why my phone will auto quit DFU mode when run <sudo ./sshrd.sh 15.6.1 TrollStore Tips>
2,why 
/dev/disk4          	                               	/private/tmp/SSHRD
"disk4" ejected.

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
