### ISSUE TITLE
Error: file Firmware/.trustcache does not exist, or is a directory

### ISSUE THREAD

**Issue by TomiYami** [opa334/TrollStore#196]
I have encountered this error installing TrollStore on my iPhone 7 running iOS 15.4.1. Any solutions?

../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ../Linux/PlistBuddy)
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022FallFCS/fullrestores/012-38914/C7764173-5CC4-4D58-8F8B-F093F9A060F0/iPhone_4.7_P3_15.7_19H12_Restore.ipsw
init done
Error: file Firmware/.trustcache does not exist, or is a directory
[-] An error occurred

**Comment by abdothiss** [comment]
may i know if you fixed it?

**Comment by parkhassan** [comment]
same

**Comment by TomiYami** [comment]
Can't seem to find a solution unfortunately.

**Comment by abdothiss** [comment]
run this
sudo apt-get install usbmuxd libimobiledevice6 libimobiledevice-utils wget curl

**Comment by k3nethh** [comment]
> run this sudo apt-get install usbmuxd libimobiledevice6 libimobiledevice-utils wget curl

didnt work. any other fixes?

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

Closing, as issues aren't for support.
