### ISSUE TITLE
Replacing cert.p12 with my own

### ISSUE THREAD

**Issue by serek8** [opa334/TrollStore#198]
What certificate creator do you use for cert.p12?
I created my own certificate with the [cert creator](https://raw.githubusercontent.com/zhuowei/CoreTrustDemo/main/badcert/makecerts.sh) from zhuowei and removed password from it. Then, I replaced cert.12 inside the tar archieve with it. Then I passed the new tar to TrollStore to auto-update itself. Then I tried to install an app with TrollStore but the app immediately crashes. I believe it's fault of the certificate. How your cert is created?

**Comment by serek8** [comment]
I just want to control the whole signature of the app.

**Comment by opa334** [comment]
The script should work but may have to be adapted, also make sure you're using Procursus ldid when compiling TrollStore, else it won't work on iOS 15.
