### ISSUE TITLE
keep getting this error when i  try to install trollstore through kali linux

### ISSUE THREAD

**Issue by abdothiss** [opa334/TrollStore#199]
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
[-] An error occurred

**Comment by cuucondiep** [comment]
same

**Comment by abdothiss** [comment]
> sudo apt-get install usbmuxd libimobiledevice6 libimobiledevice-utils wget curl
> 
> 

run this

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
