### ISSUE TITLE
Installed with steps via havoc repo etc i7 iOS 14.1 - My notes app crashes and doesnt open/ work after. Whats causing this? 

### ISSUE THREAD

**Issue by xbliss** [opa334/TrollStore#204]
Installed with steps via havoc repo etc i7 iOS 14.1 - My notes app crashes and doesnt open/ work after. Whats causing this?

**Comment by opa334** [comment]
That cannot be caused by TrollStore unless you installed the persistence helper into it, in that case, reinstall Notes from app store and install the persistence helper into the Tips app instead.
