### ISSUE TITLE
I have Problem " An error occurred "

### ISSUE THREAD

**Issue by MajidCS** [opa334/TrollStore#205]
Hi there,

When i use this : ./sshrd.sh 15.1 TrollStore Tips

I get this message : [-] An error occurred

Macbook pro

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
