### ISSUE TITLE
ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by achmddhr** [opa334/TrollStore#206]
inflating: gaster                  
[*] Waiting for device in DFU mode
[*] Getting device info... this may take a second
ERROR: Unable to connect to device
ERROR: Unable to connect to device
ERROR: Unable to connect to device
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by verygenericname** [comment]
Run as sudo if on linux

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
