### ISSUE TITLE
Potential downloading issue on chinese devices

### ISSUE THREAD

**Issue by buhuixiexin** [opa334/TrollStore#207]
i have same problem with [huytorres10](https://github.com/opa334/TrollStore/issues/11) 
14.7  iPhone xs max version China.
I tried 1.08-1.1 trollstorehelp.
I think maybe the problema is the version china when install a new App, need open "Apps Using WLAN & Cellular".But i cant find TrollHelper in that

**Comment by buhuixiexin** [comment]
yes, it works! thanks

**Comment by opa334** [comment]
Fixed in 1.1.1
