### ISSUE TITLE
uploading logs, if this fails, it's not a big deal.

### ISSUE THREAD

**Issue by Roberit** [opa334/TrollStore#210]
I keep getting this error: uploading logs, if this fails, it's not a big deal.

**Comment by verygenericname** [comment]
I can look and see what error you had

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
