### ISSUE TITLE
[Feature request] Temporarily return the app to the "User App" state

### ISSUE THREAD

**Issue by Halo-Michael** [opa334/TrollStore#211]
Temporarily return the app to the "User App" state will helpful for some apps put some settings in settings.bundle like UTM. After user setup is complete, we can rebuild icon cache again.

**Comment by Myown01** [comment]
Yeah, that's what we do

**Comment by Ixolaro** [comment]
How would we put this in place??

**Comment by teamc00lkidd1** [comment]
I agree, this can be very useful

**Comment by opa334** [comment]
Will work on this soon.

**Comment by TheDiamondGen** [comment]
> Will work on this soon.

Thx opa, your the best. I was really hoping for this feature for utm as well.

**Comment by opa334** [comment]
Added in 1.3.

**Comment by teamc00lkidd1** [comment]
yeeeeeee
