### ISSUE TITLE
Issue the when I run the script

### ISSUE THREAD

**Issue by ledjo07** [opa334/TrollStore#213]
[-] An error occurred
[-] uploading logs, if this fails, it's not a big deal.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   380    0    65  100   315     30    145  0:00:02  0:00:02 --:--:--   145
[!] Done uploading logs, i'll be sure to look at them and fix the issue you are facing

Operating system:macOS High Sierra 10.13

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support.
