### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by Roberit** [opa334/TrollStore#214]
![Captura de pantalla 2022-09-25 a la(s) 7 44 36 p  m](https://user-images.githubusercontent.com/93284430/192171271-d19acd91-85c9-40ae-b709-bdc0cefba1ad.png)

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
