### ISSUE TITLE
handleConnectResult new session to port : 62078 failed: 61

### ISSUE THREAD

**Issue by Jojo8275** [opa334/TrollStore#216]
Hey,

when i do ./sshrd boot the iphone boot i see start verbosing and show a TrollFace in ascii but after i have a line:

"handleConnectResult new session to port : 62078 failed: 61"
and the iphone stay here...

i need to restart the iphone manualy and i don't have Trollstore on tips...

do you know what is the problem ?

thank you all

**Comment by AymenKcm1** [comment]
@opa334 can't help you in that, as he didn't make the ramdisk method for checkm8 devices.

![image](https://user-images.githubusercontent.com/67245917/193163258-5780dcb0-2833-4a54-bf5d-7f8129334de2.jpeg)

You can try asking @dedbeddedbed on Twitter

![image](https://user-images.githubusercontent.com/67245917/193163415-a005500d-1a32-4e6a-9cc4-4470108e1657.jpeg)

Or comment under the [Youtube video tutorial](https://youtu.be/2hBE4OzqZEk) 

![image](https://user-images.githubusercontent.com/67245917/193163661-99c9e765-503e-407c-814c-5c61a1a4f253.jpeg)

Good luck 👍
