### ISSUE TITLE
Photo apps

### ISSUE THREAD

**Issue by Skilatchix** [opa334/TrollStore#217]
Hello! 
When I try to share or use a photo from the photo application I have an error message,  jailbroken iOS 14.7 unc0ver
But even without being in non-jailbroken state I have the same error message
Has anyone had this error message and been able to fix it? Thanks  
![image](https://user-images.githubusercontent.com/42456946/193135391-39aba84d-6411-48fc-b07c-420f6b63d8d8.jpeg)

**Comment by opa334** [comment]
I don't see how this has anything to do with TrollStore.
