### ISSUE TITLE
[*] Waiting for device in DFU mode A10

### ISSUE THREAD

**Issue by neizvedaniydag** [opa334/TrollStore#218]
pls help I've had [*] Waiting for device in DFU mode for 5 minutes already
<img width="682" alt="screenshot" src="https://user-images.githubusercontent.com/62785983/193205878-d676f7fe-1bc6-4770-9d1e-ec9224bd1470.png">

**Comment by Your-Eliauk** [comment]
Looking forward to the adaptation of A15 15.4.1

**Comment by opa334** [comment]
You need to put your device into DFU mode yourself.

**Comment by neizvedaniydag** [comment]
> You need to put your device into DFU mode yourself.

 I switched to dfu mode on the device

**Comment by neizvedaniydag** [comment]
I have an iphone 7+ on 15.4.1 ios

**Comment by opa334** [comment]
can't help you

**Comment by MaximovInk** [comment]
same here [7 plus | ios 15.2.1]

**Comment by RavanGami** [comment]
./sshrd.sh: 35: curl: not found [-] An error occurred [-] uploading logs, if this fails, it's not a big deal. ./sshrd.sh: 16: curl: not found
