### ISSUE TITLE
uYouPlus permissions error while downloading any video

### ISSUE THREAD

**Issue by baziex** [opa334/TrollStore#22]
uYouPlus having issues with Notifications and Photos access permissions.

**Comment by opa334** [comment]
looking into it right now

**Comment by skelitonlord** [comment]
I know opa hasn't gotten back, currently notifications are not gonna work due to the extensions.

**Comment by besrm** [comment]
Is there a way to access the files. Then we can just cut and paste it in to the correct directory. It seems uYou finish downloads yet it can't transfer(based on the error message). If we had a way to get filza or something similar then we could do it manually ——just guessing, not sure if this would work???

**Comment by opa334** [comment]
This was fixed in TrollStore 1.0.2. Update to latest TrollStore, then refresh app registrations.
