### ISSUE TITLE
使用TrollStore安装的软件，无法用icloud云备份（Software installed using TrollStore cannot be backed up with icloud）

### ISSUE THREAD

**Issue by wcn666** [opa334/TrollStore#220]
我安装的微信，QQ等软件，在设置里面无法找到它们，icloud备份里面也是一样找不到。无法对其使用云备份。我使用的是官方的bundle identifier安装，软件的推送通知完全正常，就是用不了icloud备份。(I installed WeChat, QQ and other software, but I can't find them in the settings, and I can't find them in the icloud backup.  Can't use cloud backup for it.  I use the official bundle identifier installation, and the push notifications of the software are completely normal, but icloud backup is not used.)

**Comment by wcn666** [comment]
![image](https://user-images.githubusercontent.com/80608339/193416469-e8d22acb-c939-48bd-bc10-704e3ec0b331.png)

**Comment by tom-snow** [comment]
Translated with deepL:
> I can't find them in the settings of WeChat, QQ and other software I installed, and the same can't be found in icloud backup. I can't use cloud backup for them. I used the official bundle identifier to install the software, and the push notifications are completely normal, but I can't use the icloud backup.

**Comment by opa334** [comment]
normal behaviour, TrollStore apps are installed as System and don't show up in settings, permissions can be altered under privacy however
