### ISSUE TITLE
dosen't work on my iPad Pro 10.5 (A10x)iOS15.4.1

### ISSUE THREAD

**Issue by Zaker-hso** [opa334/TrollStore#229]
Using SSH Ramdisk to install trollstore. successfully installed on my iPhone se 1st(15.4.1). But it's failed when i try to install it on my iPad Pro 10.5 (also 15.4.1), the first step (`./sshrd.sh 15.4.1 TrollStore Tips`) is passed, and next commond is `./sshrd.sh boot` , it recommand can't connect devices. 
Computer system version: Mac OS 12.6

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.

**Comment by Zaker-hso** [comment]
thx，i‘ll try.
