### ISSUE TITLE
error 171

### ISSUE THREAD

**Issue by cwr31** [opa334/TrollStore#23]
![5BC6CE8E-DDFC-46EB-8F46-0C026C514BA8](https://user-images.githubusercontent.com/59834457/188267832-105c6f7c-39e4-4400-8f4d-7fb0c04c709d.png)

no any YouTube-related app installed

**Comment by opa334** [comment]
I will add an option to force installation soon

**Comment by besrm** [comment]
I had the same error….If you already have a file that is similar to the one you are trying to download then this error will occur…….Case in point. Youtube — I had the original YouTube and tried to get uYou , I received the error. I had to delete my original YouTube and then the uYou was installed. The same for any other app that was already installed on my phone. Hope this helps.  opa334. —you are freaking awesome and this app is phenomenal.

**Comment by dudeedud4** [comment]
> I had the same error….If you already have a file that is similar to the one you are trying to download then this error will occur…….Case in point. Youtube — I had the original YouTube and tried to get uYou , I received the error. I had to delete my original YouTube and then the uYou was installed. The same for any other app that was already installed on my phone. Hope this helps. opa334. —you are freaking awesome and this app is phenomenal.

This helps immensely, thank you for this info.
