### ISSUE TITLE
ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by githubprogit** [opa334/TrollStore#230]
Here is the screenshot which showing an error. Plese tell me what happened.
My ios version is 15.5b4
iPhone 8
![trolstore-error](https://user-images.githubusercontent.com/83770392/194278573-aea52395-8045-4698-9982-2c007fb72800.png)

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.

**Comment by Zaker-hso** [comment]
I faced the same problem on my iPad Pro10.5! if you can solve this problem, please share your way. thanks a lot.

**Comment by githubprogit** [comment]
> I faced the same problem on my iPad Pro10.5! if you can solve this problem, please share your way. thanks a lot.

can you solve it
