### ISSUE TITLE
Unable to build TrollInstaller2 for iOS 14 devices

### ISSUE THREAD

**Issue by ccdesu** [opa334/TrollStore#239]
I'm trying to build TrollInstaller2 with the 9.3.1 version of the Developer ipa for ios 14 on A14 but once I run the script, the resulting DeveloperInstaller.ipa seems to be the same as the Developer.ipa file I put in the target folder. When installed, it just opens as the normal Developer app. I have Theos and the 14.5 sdk installed and here is the [log](https://github.com/opa334/TrollStore/files/9731269/log.txt)

**Comment by CubeBag** [comment]
The build script works if you have the 9.3.1 version, which you're doing right. There's another reason why the build is failing; look through the output and see if you can spot any errors

**Comment by tom-snow** [comment]
Through your log:

```
user-iMac:~ user$ cd Desktop/Trollstore/_compile
user-iMac:_compile user$ ./build_trollinstaller2.sh 
Makefile:5: /makefiles/common.mk: No such file or directory
Makefile:17: /application.mk: No such file or directory
make: *** No rule to make target `/application.mk'.  Stop.
Makefile:5: /makefiles/common.mk: No such file or directory
Makefile:17: /application.mk: No such file or directory
make: *** No rule to make target `/application.mk'.  Stop.
```

Did you installed [THEOS](https://theos.dev/docs/installation-macos) before?

**Comment by neil0306** [comment]
@ccdesu Hi, 
could you please tell me how to get the IPA file for developer 9.3.1?
Thanks!

**Comment by opa334** [comment]
Yes you need an IPA of the Developer app that supports iOS 14, then it will work.
