### ISSUE TITLE
A non trollstore app with the same identifier is already installed.

### ISSUE THREAD

**Issue by CycilismRSA** [opa334/TrollStore#24]
I know im not the smartest with this shit but what am i doing wrong (using altstore to sideload trollinstaller)

**Comment by dxwil** [comment]
If you're installing uYou for example, make sure you uninstall the original YouTube app. So basically uninstall the original version if you're installing a tweaked app.

**Comment by opa334** [comment]
There is now an option to Force Install in TrollStore 1.0.2 and up
