### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by mym77** [opa334/TrollStore#243]
![IMG_E0DF17F57C62-1](https://user-images.githubusercontent.com/66462224/194510393-3aaf8944-6b1f-466f-a907-14dd68d5b42b.jpeg)

**Comment by tom-snow** [comment]
你可能需要连接 海外的vpn 来确保能够下载相关组件。

You may need to connect VPN to ensure that the components can be downloaded.

**Comment by evelynce1** [comment]
didn't work

**Comment by opa334** [comment]
Fixed now, recompile IPA and try again.
