### ISSUE TITLE
Device stuck on SSHRD_Script

### ISSUE THREAD

**Issue by githubprogit** [opa334/TrollStore#247]
Hello opa334,
My device = iPhone 8 15.5 beta 4

there are an error which shown in photos

When i run **./sshrd.sh boot** command then it shown an error "Error Unable to connect to device"
after that i edited sshrd.sh file and at last add command **./sshrd.sh boot** 
now device also showing same error " Error Unable to connect to device"
after that i pressed volume down with power button and script got working 
But Device stuck on **SSHRD_Script** running on screen

there are some photos so that you understand.
![trolstore-error](https://user-images.githubusercontent.com/83770392/194549725-ffd643fb-f346-435a-8d0e-59d9cb38646a.png)
![2nd-error-3](https://user-images.githubusercontent.com/83770392/194549813-44db81bd-6012-4df1-9fff-5fff8b879fd2.png)
![IMG_20221007_172847](https://user-images.githubusercontent.com/83770392/194549972-f3b49e61-3f30-4b17-a907-7767f710742e.jpg)
  

After some time device booted without an error but device exit from DFU mode automatically when  **./sshrd.sh boot** command is running

**Comment by opa334** [comment]
Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
