### ISSUE TITLE
There was an error connecting to the Apple ID server

### ISSUE THREAD

**Issue by maxonlinux** [opa334/TrollStore#249]
iOS 14.6 A14 (iPhone 12 Mini)
While compiling the TrollInstaller2 according to the [guide](https://github.com/flowerible/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy) I download iTunes by the link in this guide (it downloads the version 12.6.3.6 but not 12.6.5 as the guide says, which I suppose doesn't even exist). After trying to log into my Apple account I have an error: `There was an error connecting to the Apple ID server`, so that version of iTunes doesn't simply let me to connect to the Apple servers. Any suggestions? Have somebody already compiled the new TrollInstaller2 for iOS 14 ?

**Comment by tom-snow** [comment]
> After trying to log into my Apple account I have an error: There was an error connecting to the Apple ID server
 Make sure you open Charles first.

And the newest TrollStore2 Supports ANY encrypted AppStore IPA now, you can read the [newest guide](https://github.com/opa334/TrollStore/blob/4afc4f37efe2719cf04b26f757f39ddfd3957b7e/install_trollinstaller2.md)

**Comment by opa334** [comment]
As said above, you can use ipatool now to download any App Store app that supports iOS 14 and use that.
