### ISSUE TITLE
install TrollStore Error With returned 1 

### ISSUE THREAD

**Issue by League2EB** [opa334/TrollStore#250]
I successfully compiled TrollInstaller2
But I ran into the following problem after I turned it on
My device message
iPhone 12
iOS 15.4

how can i fix it ?

thx all!!

![](https://i.imgur.com/hBfzSwD.jpg)

**Comment by opa334** [comment]
No idea, works for me. This error appears when the app you installed has improper entitlements, idk what could cause this unfortunately, maybe make absolutely sure that you got Procursus ldid.
