### ISSUE TITLE
TrollInstaller2 ipa does not install

### ISSUE THREAD

**Issue by rllbe** [opa334/TrollStore#252]
I've just followed the tutorial and successfully get an ipa inside the out folder, however it refuses to install on my A15 ipad mini by any means

I got following errors when installed 
via ideviceinstaller:
`Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008001: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.fsEnaD/extracted/Payload/Developer.app : 0xe8008001 (An unknown error has occurred.)`

via Sideloadly Normal Install:
`There was an issue during installation: 3892346881: ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Emh8mK/extracted/Payload/Developer.app : 0xe8008001 (An unknown error has occurred.))`

via Sideloadly Apple ID Sideload:
`There was an issue during installation: 0: IncorrectArchitecture (Failed to find matching arch for input file: /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.xWDE3j/extracted/Payload/Developer.app/Developer)`

I've double checked every step of the tutorial is well followed and no significant error in the [log](https://justpaste.it/5moyb). Do I need to update to the latest xcode version? I was using macOS catalina and xcode 11

**Comment by opa334** [comment]
My two cents would be that you're not using Procursus ldid, maybe another ldid version is overwriting the path, enter `ldid` in the command line and make sure it says `Link Identity Editor v2.1.5-procursus5` at the top of the output.

**Comment by opa334** [comment]
That or something else went wrong, maybe right click and open pwnify_compiled, it might be quarantized.

**Comment by rllbe** [comment]
Nah that's not those two things, I really uninstalled my brew ldid and downloaded the procursus one, it does return exactly `v2.1.5-procursus5` when I run it. And no, pwnify_compiled is not quarantized and returns `Usage: pwnify <program to modify> <program to inject>` when run without arguments in terminal, which means it works fine

**Comment by rllbe** [comment]
I even made an ipa by hand according to the shell script, but still the same result; however the ipa i got from another reddit user can be installed and works fine on my device. So maybe it's really xcode version? I'm using a hackintosh and cannot update to big sur real quick

**Comment by opa334** [comment]
I doubt it's the Xcode version. Try installing your victim IPA via the same method, if it doesn't work then that IPA is your problem.
