### ISSUE TITLE
Cannot install M1 iPad Air 15.5 b4

### ISSUE THREAD

**Issue by Delamcode** [opa334/TrollStore#253]
When in TSI2 I press install, it never seems to work. It just resprings.

**Comment by opa334** [comment]
Well that means it worked, after respring the TrollStore should show on the home screen. There is no way it would respring if the installation did not work.

**Comment by Delamcode** [comment]
No. The app does not exist.

**Comment by Delamcode** [comment]
Never mind. I’m dumb.

**Comment by opa334** [comment]
The Installer will still say install, that's normal, it's supposed to show installed but for some reason it doesn't, and yeah I agree.
