### ISSUE TITLE
ios14.5.1 with TrollInstaller 2?

### ISSUE THREAD

**Issue by wanghuangjie** [opa334/TrollStore#255]
[TrollInstaller 2](https://github.com/opa334/TrollStore/blob/main/install_trollinstaller2.md)
**Supported devices: A12 - A15, 14.0 - 15.4.1 (15.5b4)**

----

Installing 'developer.apple.wwdc-Release'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)ERROR: Install failed. Got error "DeviceOSVersionTooLow" with code 0x00000000: The system version is lower than the minimum OS version specified for bundle at /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.zZ2SUI/extracted/Payload/Developer.app. **Have 14.5.1; need 15.0**

**Comment by opa334** [comment]
use any app that supports iOS 14 instead of the developer app
