### ISSUE TITLE
15.3.1 It does not accept installation

### ISSUE THREAD

**Issue by zaabal3** [opa334/TrollStore#257]
I tried to install several times, the file is not accepted, it does not bear, according to the attached picture.

https://e.top4top.io/p_2472amzyf1.png

[url=https://e.top4top.io/p_2472amzyf1.png][img]https://e.top4top.io/s_2472amzyf1.png[/img][/url]

**Comment by opa334** [comment]
Looks fine to me.

Follow the instructions of this video closely then it should work

https://www.youtube.com/watch?v=2hBE4OzqZEk

For macOS use brew instead of apt to install the dependencies.

Closing, as issues aren't for support and I also can't help with ramdisk issues.
