### ISSUE TITLE
Domain Effectiveness

### ISSUE THREAD

**Issue by esf5021314** [opa334/TrollStore#258]
The domain name http://nathan4s.lol/ has already taken effect, and the program can no longer be used normally. I hope it can be repaired as soon as possible.

**Comment by verygenericname** [comment]
its still useable even if its down, i'll fix it rn

**Comment by verygenericname** [comment]
fixed

**Comment by verygenericname** [comment]
When I get spectrum as a wifi provider (should be soon) my ip will be static and wont change when my router restarts, sorry for the inconvenience.
