### ISSUE TITLE
Trollinstaller2 on A9

### ISSUE THREAD

**Issue by trollo2** [opa334/TrollStore#259]
Will there be trollinstaller2 on a8-11 as i am unable to do ssh ramdisk because it doesn't do anything
(Im using arch x64 and an iphone7 on ios 15.4.1)

**Comment by tom-snow** [comment]
> i am unable to do ssh ramdisk because it doesn't do anything
(Im using arch x64 and an iphone7 on ios 15.4.1)

This is your problem, not us.

[SSH Ramdisk tutorial](https://github.com/opa334/TrollStore/blob/main/install_with_sshrd.md)

**Comment by trollo2** [comment]
Ok

**Comment by opa334** [comment]
No there won't be one

**Comment by xoyi** [comment]
> > 我无法做 ssh ramdisk，因为它什么都不做
> > （我在 ios 15.4.1 上使用 arch x64 和 iphone7）
> 
> 这是你的问题，不是我们的。
> 
> [SSH Ramdisk 教程](https://github.com/opa334/TrollStore/blob/main/install_with_sshrd.md)

404not found

**Comment by opa334** [comment]
> > > 我无法做 ssh ramdisk，因为它什么都不做
> 
> > > （我在 ios 15.4.1 上使用 arch x64 和 iphone7）
> 
> > 
> 
> > 这是你的问题，不是我们的。
> 
> > 
> 
> > [SSH Ramdisk 教程](https://github.com/opa334/TrollStore/blob/main/install_with_sshrd.md)
> 
> 
> 
> 404not found

Your device is supported by the new TrollInstaller2.
