### ISSUE TITLE
Makefiles 5 and 17 (/makefiles/common.mk and /application.mk) missing

### ISSUE THREAD

**Issue by Zthrowaway** [opa334/TrollStore#260]
Intel i5 - MacOS 12.6 (Monterey)

The guide was followed to a T - with the exception of installing the ldid that works with the M1/M2 chips instead of Intel chips the first time.

I checked /usr/local/bin but it wasn't there, so I couldn't do anything to that version of ldid and redid the process with the correct one. After that, I cd'd into `/TrollStore/_compile` and ran `./build_trollinstaller2.sh`. The following was the result:

```
noturpc:_compile user$ ./build_trollinstaller2.sh
Link Identity Editor v2.1.5-procursus5

Usage: ldid [-Acputype:subtype] [-a] [-C[adhoc | enforcement | expires | hard |
            host | kill | library-validation | restrict | runtime]] [-D] [-d]
            [-Enum:file] [-e] [-H[sha1 | sha256]] [-h] [-Iname]
            [-Kkey.p12 [-Upassword]] [-M] [-P[num]] [-Qrequirements.xml] [-q]
            [-r | -Sfile.xml | -s] [-u] [-arch arch_type] file ...
Common Options:
   -S[file.xml]  Pseudo-sign using the entitlements in file.xml
   -Kkey.p12     Sign using private key in key.p12
   -Upassword    Use password to unlock key.p12
   -M            Merge entitlements with any existing
   -h            Print CDHash of file

More information: 'man ldid'
Makefile:5: /makefiles/common.mk: No such file or directory
Makefile:17: /application.mk: No such file or directory
make: *** No rule to make target `/application.mk'.  Stop.
```

TrollInstaller2.ipa never appeared, but an empty folder named tmppwn did. Was something missed, or is it something with the program? Thanks for all y'all do!

**Comment by opa334** [comment]
Install THEOS, an iOS 14.5 sdk and add THEOS to path.
