### ISSUE TITLE
> I tried to install several times, the file is not accepted, it does not bear, according to the attached picture.

### ISSUE THREAD

**Issue by bigdawg-codes** [opa334/TrollStore#261]
> I tried to install several times, the file is not accepted, it does not bear, according to the attached picture.
> 
> https://e.top4top.io/p_2472amzyf1.png
> 
> [url=https://e.top4top.io/p_2472amzyf1.png][img][https://e.top4top.io/s_2472amzyf1.png[/img][/url]](https://e.top4top.io/s_2472amzyf1.png%5B/img%5D%5B/url%5D)

__

_Originally posted by @bigdawg-codes in https://github.com/opa334/TrollStore/issues/257#issuecomment-1272400456_

**Comment by opa334** [comment]
????
