### ISSUE TITLE
TrollHelperOTA does not support arm64 iOS 14

### ISSUE THREAD

**Issue by pythonName** [opa334/TrollStore#268]
iphone7 , ios14.6 "GTA Car Tracker" crashed when open it.

why?

**Comment by ewgundam** [comment]
same issue.iOS14.6

**Comment by pai1233** [comment]
same issue IOS 14.1
why

**Comment by daxiewo** [comment]
same 14.3

**Comment by tom-snow** [comment]
If the prebuilt Trollinstaller2 doesn't work, you can try [building it yourself](https://github.com/opa334/TrollStore/blob/37dcff4fcd29555b9bc5d5bce968ecee02cccdab/install_trollinstaller2.md).


If still not work, please try the methods previously provided in the repository or wait for an update.

**Comment by opa334** [comment]
Known issue, TrollInstaller2 unfortunately does not work on iOS 14, use checkra1n + TrollHelper to install it.

For arm64e iOS 14 devices, use https://api.jailbreaks.app/troll64e.

**Comment by RavanGami** [comment]
iphone 8 plus not work

**Comment by CubeBag** [comment]
Have you thought about reverting the last few commits so the version table is on the homepage again?

**Comment by Git-James23** [comment]
same issue, 6s, iOS 14.4 
Hope boss update soon!!!

**Comment by opa334** [comment]
Probably not possible to fix. The issue is that iOS 14 does not seem to support launching arm64v8 binaries :/

**Comment by xoyi** [comment]
> 可能无法修复。问题是 iOS 14 似乎不支持启动 arm64v8 二进制文件：/，所以只有 arm64e 版本（https://api.jailbreaks.app/troll64e）有效

same with others, 6s p ,ios 14.5.1 , i use checkra1n + TrollHelper can use

**Comment by Git-James23** [comment]
Bad news😭so only jailbreak can work?

**Comment by xiuxianchengdi** [comment]
@Git-James23 You can use SSHRD (a8-a11) to install it on ios14+ without jailbreak

**Comment by opa334** [comment]
Closing as this is impossible because arm64v8 are not supported by the iOS 14 kernel.

**Comment by opa334** [comment]
> iphone 13pro ios 15.6 installed "GTA Car Tracker" from https://api.jailbreaks.app/troll64e, not Opening!

readme exists to read it

**Comment by gamer191** [comment]
> You can use SSHRD (a8-a11) to install it on ios14+ without jailbreak

Does that method permanently delete the tips app (or whichever app you choose) or can it be reverted?
