### ISSUE TITLE
Can i uninstall ldid?

### ISSUE THREAD

**Issue by DevCoud18** [opa334/TrollStore#269]
I have installed the Store on my i13 but how can i uninstall 'ldid' if i want to uninstall trollstore completley? ldid is not installed yet.

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/194807601-ff194ba1-5518-4ffd-ab4c-5fbe36d3e4d1.jpeg)

**Comment by RavanGami** [comment]
help

**Comment by RavanGami** [comment]
[*] Walting for device in DFU mode [*] Getting device info... this may take a second ing4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEA Compiled with plist: YES Saved IM4M to work/IM4M
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8 init pzb: null [-] uploading logs, if this falls, it's not a big deal. mv: cannot stat *.log': No such file or directory Verston 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36 Error init failed [-] An error occurred

**Comment by RavanGami** [comment]
[*] Walting for device in DFU mode 
[*] Getting device info..
this may take a second 
ing4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEA Compiled with plist: YES Saved IM4M to work/IM4M
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8 init pzb: null 
[-] uploading logs, if this falls, it's not a big deal. 
mv: cannot stat
 *.log': No such file or directory Verston 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36 Error init failed 
[-] An error occurred

**Comment by tom-snow** [comment]
@RavanGami Did you tried TrollInstaller2?

**Comment by tom-snow** [comment]
> I have installed the Store on my i13 but how can i uninstall 'ldid' if i want to uninstall trollstore completley? ldid is not installed yet.

Just click "Uninstall TrollStore" in TrollStore.

**Comment by opa334** [comment]
ldid is installed into the TrollStore app directory, it will uninstall alongside TrollStore.
