### ISSUE TITLE
Installer doesn’t seem to have network permissions

### ISSUE THREAD

**Issue by orbitaldr0p** [opa334/TrollStore#272]
![F4B51BF2-C2ED-4083-8E0C-23C856704B7D](https://user-images.githubusercontent.com/33896795/194835219-b5fb5694-1bc8-4843-8620-6acf1ba7ef36.png)

**Comment by opa334** [comment]
Yeah this is an issue with chinese devices, I tried to fix it but my fix doesn't seem to work.
