### ISSUE TITLE
where is the TrollInstaller.ipa of v1.2?

### ISSUE THREAD

**Issue by tanghengvip** [opa334/TrollStore#280]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

get a v1.2 version TrollStore.IPA

### Current Behavior?

TrollStore v1.1.2 couldn't successful install on my device(iOS15.3). 
so I was gonna trying v1.2. but I can't fine TrollInstller.ipa at releases page.
<img width="921" alt="image" src="https://user-images.githubusercontent.com/4047349/195305585-99563166-5353-4ba0-9db1-af7febdabd0f.png">

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore2

### iOS/iPadOS version

iOS 15.3

### iDevice Model

iPhone 11

**Comment by tajetaje** [comment]
See readme

> # Installing TrollStore (No Jailbreak)
> 
> ## Installation Links:
> 
> [Installation Link 1 - Supports all devices on iOS 15 and up](https://api.jailbreaks.app/troll)
> 
> [Installation Link 2 - Supports all arm64e (A12 - A15) devices on iOS 14 and up](https://api.jailbreaks.app/troll64e)
> 
> Please refer to "Compatbility" above to check whether your version is compatible, if it's not then these links will not work.
> 
> This installation method unfortunately does **NOT** work on arm64 (A8 - A11) iOS 14 devices, for these devices, jailbreak with checkra1n and then use the jailbroken installation guide below.
> 
> ## Guide
> 
> 1. Based on what device you are using, pick the one of the two links above and tap it.
> 
> 2. An alert should appear, click "Install".
> 
> 3. When the installation is finished, you will find a "GTA Car Tracker" application on your device.
> 
> 4. If this app has not appeared, that's a stock iOS bug, reboot your device and it will appear.
> 
> 5. Launch the app, tap "Install TrollStore".
> 
> 6. Wait a few seconds, your device should respring and TrollStore will be installed.
> 
> 7. You can now either delete the "GTA Car Tracker" app, or register it as the persistence helper by opening it and tapping the option at the bottom and keep it.
> 
> 8. Open the TrollStore app and press "Install ldid" in the Settings tab, then read the information under "Persistence", and install the Persistence Helper into a system app if want persistence.
> 
> 9. Done, you can now share IPA files with TrollStore and they will be permanently installed on your device.
