### ISSUE TITLE
What's the TrollHelperOTA install link magic?

### ISSUE THREAD

**Issue by panderman** [opa334/TrollStore#287]
When i open  [TrollHelperOTA Link 1 - Supports all devices on iOS 15 and up](https://api.jailbreaks.app/troll), It's install in my phone success whitout any cert, But when i download ipa file from https://jailbreaks.app/cdn/plists/TrollHelper.plist, Then install it though local OTA link, It's always fails, Why?

**Comment by opa334** [comment]
I'm unsure what you mean by "local OTA link"? The magic is that this is an app that appears to the system as a legit app store app but in reality it has TrollHelper embedded inside it. When you resign the IPA, this breaks.

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/195661110-0f262189-8499-4c02-a0fe-18bc5f40721c.png)
