### ISSUE TITLE
Wallpaper zoomed in after respring with TrollStore 

### ISSUE THREAD

**Issue by AymenKcm1** [opa334/TrollStore#290]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Wallpaper stays as I set it.

![601345DC-B95F-4791-B9F5-5F92C491DEB6](https://user-images.githubusercontent.com/67245917/195992608-e5410490-912d-405b-abf8-c6818291ab11.png)

### Current Behavior?

It’s a small thing: The wallpaper gets zoomed in after respring, not always but enough to be bothersome.

![610774D6-2F7D-4FF3-B001-27F99CEB7B9C](https://user-images.githubusercontent.com/67245917/195992293-8e49e1f9-6863-47dc-a343-a4d7588499d9.png)

The issue have been present since earlier versions and still happening with the latest.

### Possible Solution?

-

### Steps to Reproduce

- Set a wallpaper and don’t zoom it to crop it in the screen.
- Respring with TrollStore 
- Check the wallpaper whether it’s zoomed in or not.

### TrollStore Version

TrollStore 1.2

### iOS/iPadOS version

iOS 15.1.1

### iDevice Model

iPhone 12 Pro Max

**Comment by opa334** [comment]
Idk, if anything this is a stock issue, TrollStore just kills SpringBoard to respring.

**Comment by AymenKcm1** [comment]
OK, if possible maybe other respring method / cmd (other than killall if you're using it) could be looked into, if there is any (I have some jb knowledge but not an expert 😅)

Thanks.
