### ISSUE TITLE
Unable to open app. "Restrictions Enabled, certain apps or features can’t be seen or used when restrictions are on"

### ISSUE THREAD

**Issue by qosmio** [opa334/TrollStore#292]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

App icon should appear in springboard after refreshing uncache. App should open without receiving "Restrictions" warning.

### Current Behavior?

Installed YouTube IPA (uYouPlus). Was in the process of enabling options in the app, it ended up crashing. I was unable to open it or even find the icon after that. Tried running the "rebuild icon cache" option, "respring", still no icon.

After wiping the app in Trollstore, and installing from App store, I still am unable to find the icon. If try to open from the app store i receive the error:

```
"Restrictions Enabled, certain apps or features can’t be seen or used when restrictions are on" 
```

I've tried to manually wipe traces using Filza as well, running in a jailed and unjailed state.

Several users reported on reddit as well.

1.) [[Help] Installed an app using trollstore then uninstalled it after breaking some of it and now I can’t use it at all even if I try to install using AppStore or trollstore or filza](https://www.reddit.com/r/jailbreak/comments/y3ssmo/help_installed_an_app_using_trollstore_then/)

2.) [How can I resolve the issue , the InShot app was working fine before , I tried with TrollStore , then it happened , and tried by removing app, reinstalling and with Filza , same](https://www.reddit.com/r/Trollstore/comments/xxunl8/how_can_i_resolve_the_issue_the_inshot_app_was)

![Screenshot](https://user-images.githubusercontent.com/8892380/196112744-84c9d7c4-f7e1-4e86-bc23-cb87cbd71ef6.jpeg)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

1.2

### iOS/iPadOS version

14.6

### iDevice Model

iPhone 11 Pro Max

### Other info of your environment

macOS 12.6, unc0ver (unc0ver Trollstore launcher)

**Comment by opa334** [comment]
Please send me the IPA this happened with

**Comment by opa334** [comment]
You say you installed uYouPlus but your screenshot says InShot, what now? Are App Store downloads completely broken?

This sounds weird, no idea what could cause this. Try going to /var/containers/Bundle/Application in Filza, if you can find the app name there, delete the folder and then refresh icon cache.

**Comment by qosmio** [comment]
Apologies the screenshot was from the Reddit post. I didn’t have a screenshot of the one for YouTube. I can take one one as well. Let me try deleting the app through Filza again.

**Comment by qosmio** [comment]
This was the IPA https://github.com/qnblackcat/uYouPlus/releases/download/v17.40.5-2.1/uYouPlus_17.40.5_2.1.ipa

After initially deleting from TrollStore, I was actually unable to install it through TrollStore a subsequent time. I could only install it from the App Store, but failed to open.

I’m not near the device currently. It belongs to a relative of mine, but will update with more screenshots and logs when they return later this evening.

**Comment by qosmio** [comment]
App Store Error
![Error](https://user-images.githubusercontent.com/8892380/196330822-84c0350e-d53a-437c-8b11-6d50ba43b2e5.png)

Error opening in TrollStore (uYouPlus IPA)
![1B985251-3495-4C3C-88DF-37228FAF6DD7](https://user-images.githubusercontent.com/8892380/196330823-c3b1aabc-beb0-411c-904a-a76e2362426b.png)

Error opening in TrollStore (OLED tweaked YouTube)
![1AF2053B-2ED1-458C-9ADC-3BF31AAA244A](https://user-images.githubusercontent.com/8892380/196330825-89c185ab-96c4-4597-9992-b29a7506a012.png)

TrollStore updated to 1.2.1 
![0AB88450-6520-42F0-BAD7-7E2B2F286670](https://user-images.githubusercontent.com/8892380/196330826-876018b5-5296-42d0-a370-439263f05e7c.png)

Tried the following again, with no success.

1.) Uninstalling through Filza, and reinstalling in jailed mode from the App Store. 
2.) Rebooting into jailed mode, reinstalling through TS.
3.) Refreshing uicache
4.) Running persistence helper through Tips.
5.) Installing AppSync to test in JB mode, and installing through App Store and TrollStore.
6.) Opening from NewTerm with “open” utility. 
```bash
open com.google.ios.youtube
```
Immediately aborts “reason code 8”
7.) Verified TrollStore is able to install other apps. Tested with SoundCloud and it opens.
8.) Tried multiple IPAs of YoutTube (uYouPlus, OLED, generating custom IPA from another device with Frida IPA dumper (the final IPA had no tweaks injected)
9.) Deleting all traces of `com.google.ios.youtube` from keychain-2.db. 
```sql
DELETE FROM genp WHERE agrp like '%com.google.ios.youtube%
```
10.) Running iCleaner and respiringing throughout the whole endeavor.

Not sure what else to try. In every instance I’ve been unable to see the icon as well. I have confirmed that screen time restrictions are disabled.

**Comment by combustor** [comment]
Same exact problem

iOS 14.4 on unc0ver 

So I was playing around with an app's bundle ID and I broke it somewhat and I uninstalled it, the app was installed through trollstore

So after I uninstalled it I reinstalled it and tried opening it from trollstore, it says unable to open com.bundleidoftheapp 

I uninstalled it through Filza and tried reinstalling it from the AppStore and it doesn't show up in the homescreen, I tried opening it through NewTerm using "open" and I get error message 8

I tried opening through AppStore and I get the message "Restrictions Enabled, certain apps or features can’t be seen or used when restrictions are on"


I tried disabling screentime daemon and nothing works

Any help would be appreciated

**Comment by TheOrbOfDestiny** [comment]
i tested this for myself and it works fine for me out of the box

i’m using an iPad Mini 5 on iOS 14.8 (no jailbreaks)

**Comment by combustor** [comment]
> i tested this for myself and it works fine for me out of the box
> 
> 
> 
> i’m using an iPad Mini 5 on iOS 14.8 (no jailbreaks)

What exactly did you test?

**Comment by qosmio** [comment]
@TheOrbOfDestiny 

I don’t believe this is specific to the YouTube IPA. Because it worked fine on my other devices, running 14.6 iPad (not JB), 15.4 iPhone. 

The app opened up the first time I installed it, only to crash a few minutes later and then failed to open properly after that.

@combustor

Are you able to verify it opens if you change the bubdleid of the IPA with Azule?

**Comment by opa334** [comment]
If anyone affected has a mac, please use Console.log to view the logs of the device, enter the affected app name in the top right search bar, then try to download it from App Store (when the restrictions error appears) and send me the logs here. Granted this is most definitely a stock issue though, probably some cache is invalid.

**Comment by combustor** [comment]
> @combustor
> 
> 
> 
> Are you able to verify it opens if you change the bubdleid of the IPA with Azule? 

Yep it does open and work normally if I change the bundleid

**Comment by qosmio** [comment]
@combustor 
> Yep it does open and work normally if I change the bundleid with azule

That's what I suspected would happen as well. Haven't been able to test this myself yet. Waiting to meet my relative later this week.

> > @opa334 
> > If anyone affected has a Mac, please use Console.log to view the logs of the device

> @combustor 
> I unfortunately don't

You should be able to use Sideloadly. Granted the screenshot is on my Mac, the features should be available in the Windows version. It was when Cydia Impactor was around.
<img width="933" alt="Screen Shot 2022-10-19 at 6 47 55 PM" src="https://user-images.githubusercontent.com/8892380/196819283-4a88f48a-5958-45d4-b9f3-8afb1f07e224.png">

**Comment by opa334** [comment]
Yes that's true, Sideloadly / Cydia Impactor will work on Windows too

**Comment by combustor** [comment]
> You should be able to use Sideloadly. Granted the screenshot is on my Mac, the features should be available in the Windows version. It was when Cydia Impactor was around.


I currently can't use my PC but I found a package named "oslog" and I'm guessing it's pretty much the same output

Here's the result of `oslog | grep Launch` when trying to launch the app from the AppStore 
[Logs](https://mega.nz/file/vapHyDQL#L-9AHSPMv1ww-yK9nxm4i4m0klM8816G6MqHEq6ORGM)

I can upload the full log when installing the game but I would rather privately message it to @opa334

**Comment by opa334** [comment]
This error message is printed in -[SBMainWorkspace _validateRequestToOpenApplication:options:origin:error:] when -[SpringBoard isBundleIdentifierRestrictionDisabled:] returns YES.

That calls out to -[SBApplicationRestrictionController isApplicationIdentifierRestricted:], which checks if the _restrictedIdentifiers ivar of SBApplicationRestrictionController contains the bundle id in question.

This leads me to believe that the system thinks the app is actually restricted.

Please check the screen time settings on your device, as you can see in this video https://www.youtube.com/watch?v=qEIVqg3aoVI when apps are restricted, they also will not show up on the home screen.

As to how any of this would be triggered by TrollStore, I have no idea.

**Comment by combustor** [comment]
> Please check the screen time settings on your device, as you can see in this video https://www.youtube.com/watch?v=qEIVqg3aoVI when apps are restricted, they also will not show up on the home screen.
> 
> 
> 
> As to how any of this would be triggered by TrollStore, I have no idea.

I already have checked it unfortunately and screentime isn't even on, turned it on and it still didn't show up

Is there a way to delete those restrictions manually like through Filza?

**Comment by opa334** [comment]
I looked into it some more and if I'm not completely wrong then the settings related to restrictions should be in `/private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles/UserSettings.plist`. Please send me the file first, afterwards you can try deleting it and then reboot.

**Comment by combustor** [comment]
> I looked into it some more and if I'm not completely wrong then the settings related to restrictions should be in `/private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles/UserSettings.plist`. Please send me the file first, afterwards you can try deleting it and then reboot.

I searched everywhere in that plist and found nothing related to my app
Here's the [plist](https://mega.nz/file/GDR0RAhR#jKu3oCiseH8MrfD15CMKpKaEjs3kfOoUKxoYxJtxV-8)

**Comment by opa334** [comment]
Yeah idk I can't see anything either. Maybe try deleting everything in that ConfigurationProfiles folder, otherwise the only other file that I saw had some involvement was /var/mobile/Library/Preferences/com.apple.springboard.plist. If deleting all of these and rebooting doesn't work, idk what else to try :/.

**Comment by combustor** [comment]
> Yeah idk I can't see anything either. Maybe try deleting everything in that ConfigurationProfiles folder, otherwise the only other file that I saw had some involvement was /var/mobile/Library/Preferences/com.apple.springboard.plist. If deleting all of these and rebooting doesn't work, idk what else to try :/.

Solved!

I did a bit of searching in the same folder and found the BID of the app in ClientTruth.plist and I deleted the entry, rebooted and now it works!
Here's the file before the modification [ClientTruth.plist](https://mega.nz/file/uawDTJAI#LAznk_XqL_BmGUCas2FarYA1kyd40RxSM4ZU7GRyUak)
Thank you for your help!

**Comment by qosmio** [comment]
This is great news! I will try the same later this evening. Thank you both!

**Comment by qosmio** [comment]
Writing to confirm that after removing the key **`com.google.ios.youtube`** from **`ClientTruth.plist`**, I was able to reinstall through TrollStore and it opened up without issue.

Steps for those who might come across this post. 

## Pre-reqs
Jailbroken
1.) Download Filza

Non-Jailbroken (UNTESTED)
1.) Download [Filza for TrollStore](https://raw.githubusercontent.com/baziex/TrollStoreApps/main/TrollStoreApps/FilzaTS_BZ.ipa)

## Both
1.) In Filza , navigate to: `/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles`
2.) Open file **`ClientTruth.plist`**
3.) Locate and delete the bundle id of the app in:
```yaml
com.apple.lsd.appremoval:
 clientRestrictions:
  union:
   removedSystemAppBundleIDs:
     values:
```
4.) Save, and reboot.

It should install/open after that.

**Comment by opa334** [comment]
Should be fully fixed now, if this still happens to you, refresh icon cache.
