### ISSUE TITLE
Awesome, How can I install the IPA app directly from the OAT link like your TrollHelperOTA link?

### ISSUE THREAD

**Issue by panderman** [opa334/TrollStore#293]
Hi, This repo is very awesome for me, I'm looking for some method that can install IPA file directly from the OAT link like:

[TrollHelperOTA Link 1 - Supports all devices on iOS 15 and up](https://api.jailbreaks.app/troll)

How is this done, what you said before:

> The magic is that this is an app that appears to the system as a legit app store app but in reality it has TrollHelper embedded inside it. When you resign the IPA, this breaks.

If I want to do this, How to do it in code level?

Looking forward to your reply.

**Comment by bolabola6789** [comment]
Use it with your iOS device's safari. I struggled like you at first.

**Comment by panderman** [comment]
> Use it with your iOS device's safari. I struggled like you at first.

Thanks for you reply，You may have misunderstood what I mean, I mean the code level

**Comment by opa334** [comment]
This is mostly explained in the Fugu15 presentation.

Also see:

https://github.com/opa334/TrollStore/tree/main/Pwnify

https://github.com/opa334/TrollStore/blob/main/Makefile

https://github.com/opa334/TrollStore/tree/main/Victim
