### ISSUE TITLE
help me iphone 8 15.6.1

### ISSUE THREAD

**Issue by hil3m** [opa334/TrollStore#295]
help me please
![E09AB81B-DCC0-48E1-A94B-47648376FD53](https://user-images.githubusercontent.com/67930632/196262402-7523564f-0062-4050-88b7-df7778aa80d3.png)

**Comment by xiuxianchengdi** [comment]
Not support

**Comment by hil3m** [comment]
> Not support

I installed beta profile but still the same I really want to install trollstore, is it impossible to come in next updates? very sad

**Comment by xiuxianchengdi** [comment]
https://github.com/opa334/TrollStore#compatibility

**Comment by teamc00lkidd1** [comment]
@opa334 please close this
