### ISSUE TITLE
[iPhone 11, iOS 15.0.1] TrollStore installed with TrollHelperOTA cannot install apps, ldid error 175

### ISSUE THREAD

**Issue by Absolucy** [opa334/TrollStore#296]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I expected TrollHelperOTA to be able to install a fully working TrollStore.

### Current Behavior?

Trying to install any app (tested with latest TrollNonce and uYou+) results in install error 175

### Possible Solution?

Installing TrollStore via TrollInstaller then updating TrollStore works.

### Steps to Reproduce

- Install TrollHelperOTA (only Link 2 has been tested)

### TrollStore Version

TrollStore 1.2.1

### iOS/iPadOS version

15.0.1

### iDevice Model

iPhone 11

**Comment by JasmineYong** [comment]
![微信图片_20221018100201](https://user-images.githubusercontent.com/45485611/196318018-4a413016-add6-43d8-872f-f7eb84dc3fd3.jpg)
same problem！

**Comment by opa334** [comment]
Please attach the logs from "TrollStore" and "trollstorehelper" while this happens.

**Comment by Absolucy** [comment]
Uhh. Bad news. Due to a failed FutureRestore, my iPhone 11 is now stuck on 15.7, so I can no longer help 😬 

@JasmineYong can you post your logs?

**Comment by Absolucy** [comment]
Just confirmed, issue is **not** present on an A12 device, using OTA 1 on iOS 15.0.1.

**Comment by opa334** [comment]
> Just confirmed, issue is **not** present on an A10 device, using OTA 1 on iOS 15.0.1.
> 
> 
> 
> That narrows down the issue being either OTA 2 or arm64e (or one of those things in combination with iOS 15.0.1)

It's definitely not that. The method you used to install TrollStore shouldn't matter, I think ldid is just getting corrupted for some people, I may need to start checking the hash.

**Comment by CxiaoyuN** [comment]
I'm getting the same error when installing kodi

**Comment by opa334** [comment]
> I'm getting the same error when installing kodi

yeah that's known and an issue with the Kodi IPA

**Comment by PoomSmart** [comment]
@opa334 Here's what I see from the log.

```
info	21:44:51.262542+0700	ldid	ExtensionLoader 1f6762f: startup
debug	21:44:51.264149+0700	ldid	ExtensionLoader 1f6762f: completed in 5 ms
default	21:44:51.277968+0700	trollstorehelper	ldid exited with status 1
default	21:44:51.278091+0700	trollstorehelper	- ldid error output start -
default	21:44:51.278296+0700	trollstorehelper	ldid: operator(): Operation not permitted
default	21:44:51.278388+0700	trollstorehelper	- ldid error output end -
default	21:44:53.443173+0700	TrollStore	installed app! ret:175, error: Error Domain=TrollStoreErrorDomain Code=175 "Failed to sign the app. ldid returned a non zero status code." UserInfo={NSLocalizedDescription=Failed to sign the app. ldid returned a non zero status code.}
```

**Comment by opa334** [comment]
@PoomSmart What IPA was this? Do others work?

**Comment by opa334** [comment]
> @opa334 Filza. Other IPAs also get me ldid error 175.

Weird, it also doesn't help that ldids output sucks. I see you're jailbroken, does it work when not jailbroken? Also maybe try running the ldid binary in the TrollStore app bundle manually via ssh and check if it works correctly there.

**Comment by PoomSmart** [comment]
I can probably try the latter because my device is tethered jailbroken.. there's no way it can be unjailbroken unless I restored rootfs or sth.

**Comment by PoomSmart** [comment]
@opa334 Via ssh or Terminal, I can execute ldid binary just fine as it shows usage and stuffs normally.

**Comment by opa334** [comment]
> I can probably try the latter because my device is tethered jailbroken.. there's no way it can be unjailbroken unless I restored rootfs or sth.

Ah yeah that's a known palera1n issue then. I have no idea why but Substitute breaks ldid when it's spawned by trollstorehelper. I wanted to look into it but TrollStore doesn't even open on palera1n for me.

**Comment by PoomSmart** [comment]
@opa334 While still being jailbroken, I tried installing an IPA when:

1. Safe mode is enabled
2. Substitute's Tweak Injection is disabled (substitute-loader.dylib won't load into ldid process)
4. Safe mode is enabled and Tweak Injection is disabled

All failed with the same error 175 and the same logs in Console, but I'd guess you could try disabling Tweak Injection to debug your way?

**Comment by PoomSmart** [comment]
But there's a good news. I tethered boot my iPhone again but without `--tweaks` flag. Now `ldid` works correctly.

```
default	20:13:42.053136+0700	trollstorehelper	ldid exited with status 0
default	20:13:42.053292+0700	trollstorehelper	- ldid error output start -
default	20:13:42.053565+0700	trollstorehelper	- ldid error output end -
```

**Comment by opa334** [comment]
I don't think I can do anything about this issue, it's either a Substitute or palera1n bug

**Comment by Absolucy** [comment]
The initial issue I reported wasn't using any jailbreak...

**Comment by opa334** [comment]
> The initial issue I reported wasn't using any jailbreak...

yeah, I know that, really weird. I think ldid may have just been corrupted on your device or something.

**Comment by PoomSmart** [comment]
@opa334 Then would it be possible if TrollStore allows reinstallation of ldid?

**Comment by opa334** [comment]
> @opa334 Then would it be possible if TrollStore allows reinstallation of ldid?

In that case TrollStore can just be uninstalled and installed again, then ldid will also be gone

**Comment by Absolucy** [comment]
I think I tried re-installing it before making this issue, to no avail?

**Comment by CycloneCX** [comment]
Cannot install any apps at all, tried appstore.

Tried to delete icon cache via appstore.

iPhone 13 Pro Max, iOS 15.1.

Jailbreak with Xina15, currently not in a jailbroken state.

Restarted too, of course nothing.

Only thing I have found so far is this. 

https://www.reddit.com/r/Trollstore/comments/zzoj39/unable_to_download_update_apps/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Still cannot install apps, the tweaks I have for iOS 15, are battery indicators and iOS 16 lockscreen, as well as Shadow (JB) bypass, that’s it.

**Comment by CycloneCX** [comment]
Some say it’s tied to «App Manager» permissions, I did install that /update it not too long ago.

**Comment by CycloneCX** [comment]
I tried to rebuild ldid, reinstalled / uninstallted trollstore, nothing. Will try purging all the apps but it seems like something had changed permissions.

**Comment by opa334** [comment]
> I tried to rebuild ldid, reinstalled / uninstalled trollstore, nothing. Will try purging all the apps but it seems like something had changed permissions.

I have tried debugging this issue with another user but couldn't find anything particular different in file permissions. Have you used Fugu15 before?

**Comment by opa334** [comment]
(Also resetting all contents and settings will fix this but that's besides the point, I'm trying to find a fix that doesn't involve that)

**Comment by CycloneCX** [comment]
Hello again, sorry I posted here love your work, I was just getting desperate after trying many different solutions, I talked to someone in the /r/jailbreak discord and they told me to double check my Daemons, this is where I found out that "passbook" daemon was somehow disable through "iCleaner Pro" which somehow broke Appstore, thank you for replying so fast I wanted to leave the fix here incase someone else end up in the same situation.  #NotTrollstoreRelated.

**Comment by plia7** [comment]
> > I'm getting the same error when installing kodi
> 
> yeah that's known and an issue with the Kodi IPA and not with TrollStore

Hello @opa334, so what would be the resolution for this? I'm trying to install Kodi 19.4 ipa on my iPhone 12 Pro Max with iOS 14.4.1 after upgrading from u0 to Taurine and use troll store now... It used to work fine in u0.
 TS log says it's failing at the kodi framework library and there was something about python 3.8:

![image](https://github.com/opa334/TrollStore/assets/134864072/1672aaeb-3ddf-450d-bac1-98322c8c00e2)

2023-12-12 12:08:20.198 trollstorehelper[25483:372881] [/private/var/tmp/415B2F3D-442C-4609-A107-D2F2F94A3DFD/Payload/Kodi.app/Frameworks/lib/python3.8/config-3.8-darwin/python.o] **Applying CoreTrust bypass...** 2023-12-12 12:08:20.198 trollstorehelper[25483:372881] [/private/var/tmp/415B2F3D-442C-4609-A107-D2F2F94A3DFD/Payload/Kodi.app/Frameworks/lib/python3.8/config-3.8-darwin/python.o] **CoreTrust bypass failed!!!** :( 2023-12-12 12:08:20.707 trollstorehelper[25483:372881] **trollstorehelper returning 175**

How come with untether unc0ver it's not an issue there but an issue here? Maybe the same can be done for TrollStore to bypass that? Or do you think it's something the Kodi dev team should solve?

Thank you.
