### ISSUE TITLE
how to know, where the app was installed from by trollstore or appstore?

### ISSUE THREAD

**Issue by 24** [opa334/TrollStore#297]
@opa334 

in app code , how to know where the app was installed from by trollstore or appstore ?

How to judge?

Thank you   @opa334

**Comment by teamc00lkidd1** [comment]
I’m not sure if this is possible, you might be able to check if the app is installed as a system application or a user application. Trollstore installs IPAs as system applications, the App Store installs them as user applications

**Comment by opa334** [comment]
Parse LC_CODE_SIGNATURE of the apps main binary and verify the team id and certificate names match your real app store binary. You could also check if the _TrollStore fule exists in one path above your app bundle, but that's a bad solution. Through LC_CODE_SIGNATURE parsing you can prevent your app from being sideloaded or installed via TrollStore.

**Comment by 24** [comment]
@opa334  Thank you so much
