### ISSUE TITLE
App Crash and Unable to Remove Bugged/Ghost App

### ISSUE THREAD

**Issue by nick-botticelli** [opa334/TrollStore#3]
Environment: iPhone 13 Pro 15.1.1 (19B81)

I attempted to install an application which was most likely not compatible, and it appears under the TrollStore listing but does not appear on the home screen. Attempting to remove the application (or at least its ghost listing) by deleting it in TrollStore results in the app immediately crashing and the app still listed upon starting TrollStore again. Attached is what I think may be a relevant crash log I found.

[TrollStore-2022-09-02-123434.txt](https://github.com/opa334/TrollStore/files/9480694/TrollStore-2022-09-02-123434.txt)

**Comment by opa334** [comment]
idk iOS 15 crash logs are really complicated to read :/ will also look into this tomorrow

**Comment by opa334** [comment]
Should be fixed in 1.0.5. The "ghost" app should also be removable now.
