### ISSUE TITLE
Is there something wrong when I re-make?

### ISSUE THREAD

**Issue by panderman** [opa334/TrollStore#301]
Hello, first of all thank you for open source such an amazing project.

I download the git code myself and compiled it with "GTA Car Tracker" IPA, everything as well, but when I downloaded another IPA called "TrackerInfo" from the App Store to compile, It can be successfully installed on my iPhone with iOS 15.0.1, but the screen is black with nothing in when opening the app. 

I have obtained the TeamID of "TrackerInfo" which is "VZ3XHW8R9T", and use make_cert.sh to regenerate victim.p12. What am I missing?

How are cert.p12 and cert_new.p12 generated and what are they used for? Is it related to this?

Looking forward to your reply.

![WechatIMG20](https://user-images.githubusercontent.com/2589642/196634514-c9eb46f4-0da2-46f4-a030-ed05aa7107f4.png)
![WechatIMG18](https://user-images.githubusercontent.com/2589642/196634527-5ef5d1d5-3e7f-4053-ac35-354252e75ed9.png)
![WechatIMG19](https://user-images.githubusercontent.com/2589642/196634535-c2ffab2a-2ac7-4eb8-ac1e-fb72c566d12d.jpeg)

**Comment by opa334** [comment]
Probably an issue with the SceneDelegate of that app, will take a look later

**Comment by panderman** [comment]
> Probably an issue with the SceneDelegate of that app, will take a look later

Thanks for your reply, how are cert.p12 and cert_new.p12 generated?

**Comment by modudibai** [comment]
> 

I got a problem when make [build_installer15] task,  the error is:
`ldid.cpp(3316): _assert(): flag_S || key.empty()
libc++abi: terminating with uncaught exception of type char const*
make: *** [build_installer15] Abort trap: 6
`
I also used ./make_cert.sh to make a victim.p12 first. what I missed? please help

**Comment by opa334** [comment]
> > 
> 
> I got a problem when make [build_installer15] task, the error is: `ldid.cpp(3316): _assert(): flag_S || key.empty() libc++abi: terminating with uncaught exception of type char const* make: *** [build_installer15] Abort trap: 6 ` I also used ./make_cert.sh to make a victim.p12 first. what I missed? please help

you need procursus ldid

**Comment by modudibai** [comment]
> > > 
> > 
> > 
> > I got a problem when make [build_installer15] task, the error is: `ldid.cpp(3316): _assert(): flag_S || key.empty() libc++abi: terminating with uncaught exception of type char const* make: *** [build_installer15] Abort trap: 6 ` I also used ./make_cert.sh to make a victim.p12 first. what I missed? please help
> 
> you need procursus ldid

I already have Idid installed, what should I do more?

**Comment by modudibai** [comment]
> > > > 
> > > 
> > > 
> > > I got a problem when make [build_installer15] task, the error is: `ldid.cpp(3316): _assert(): flag_S || key.empty() libc++abi: terminating with uncaught exception of type char const* make: *** [build_installer15] Abort trap: 6 ` I also used ./make_cert.sh to make a victim.p12 first. what I missed? please help
> > 
> > 
> > you need procursus ldid
> 
> I already have Idid installed, what should I do more?

sorry, I got it. Should use the exactly **procursus ldid** from: https://github.com/ProcursusTeam/ldid
thank you!

**Comment by opa334** [comment]
I briefly looked into this, but can't see anything too different about the TickerInfo app that would cause this black screen, really weird.

**Comment by panderman** [comment]
I found this to be the problem because the TrickerInfo application's Info.plist uses UIApplicationSceneManifest but there is no UISceneConfigurations node, I have replaced another app and it works, thanks a lot.

> I briefly looked into this, but can't see anything too different about the TickerInfo app that would cause this black screen, really weird.
