### ISSUE TITLE
How to move iPad internal applications to mobile hard disk？

### ISSUE THREAD

**Issue by INTKILOW** [opa334/TrollStore#303]
### No Duplicates Issue

- [x] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

How to move iPad internal applications to mobile hard disk

### Current Behavior?

How to move iPad internal applications to mobile hard disk

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

iOS 15.1

### iDevice Model

iPhone 11

**Comment by opa334** [comment]
don't understand

**Comment by INTKILOW** [comment]
I want to move my iPad application to the SD card to run, because my iPad is 64g
