### ISSUE TITLE
Trollstore crash when open it?

### ISSUE THREAD

**Issue by sumvipconbai** [opa334/TrollStore#304]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

iphone11 promax , ios14.8 Trollstore crashed when open it. I tried to reinstall it by tweak and GTA car tracker but can’t done.

### Current Behavior?

I found out the error was caused by jailbreak. When I restart the my phone, trollstore works properly.  But when I jailbreak again with uncover, its crash again

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

trollintaller2

### iOS/iPadOS version

14.8

### iDevice Model

ip11 promax

**Comment by opa334** [comment]
needs more info and less "pls", some crash logs would be good as a start

**Comment by plooshi** [comment]
pls

**Comment by opa334** [comment]
ok that's it

**Comment by sumvipconbai** [comment]
> needs more info and less "pls", some crash logs would be good as a start

i have restarted the phone its working properly.  But when I jb with uncover, it crashes again.

**Comment by sumvipconbai** [comment]
> needs more info and less "pls", some crash logs would be good as a start

**Comment by opa334** [comment]
Sounds like a tweak issue to me
