### ISSUE TITLE
The first step aka trying to boot up the gta tracking app crashes version 15.6.1

### ISSUE THREAD

**Issue by IwantToDieRightNow-e** [opa334/TrollStore#307]
### No Duplicates Issue

- [x] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I expected it to work normally 
(Also I don’t  know if this review counts as a duplicate since it’s basically  the same as another review but with different versions)

### Current Behavior?

It’s in the title I open the app and it immediately crashes I was able to download the first app (the gta car tracking app) through the second link which I assume is t troll installer 2

### Possible Solution?

Im not a genius I don’t know anything about this

### Steps to Reproduce

Never messed around with code it kinda just happened

### TrollStore Version

2 (I assume)

### iOS/iPadOS version

15.6.1

### iDevice Model

Ipad 8

### Other info of your environment

I dunno

**Comment by opa334** [comment]
The readme is there to read it.
