### ISSUE TITLE
there is something wrong for iPad mini 4

### ISSUE THREAD

**Issue by HarryWang29** [opa334/TrollStore#312]
there is something wrong

iPad mini 4 / A8 / ios15.5 

use `https://api.jailbreaks.app/troll`

when I open `GTA Car Tracker`, it flash

https://user-images.githubusercontent.com/8288067/197489821-4c0751c6-6ea8-4f5f-b009-ee69fbb79281.MP4

_Originally posted by @HarryWang29 in https://github.com/opa334/TrollStore/issues/53#issuecomment-1288692092_

**Comment by opa334** [comment]
15.5 is not supported (and never will be)
