### ISSUE TITLE
Install error 167

### ISSUE THREAD

**Issue by Apibug** [opa334/TrollStore#313]
A11 ios14.8
1.2.1 installed 1.2.2
![0DF37494-8FA1-4752-A8EB-9DB76A03636F](https://user-images.githubusercontent.com/29590985/197611516-5d6c1096-cf9a-4526-84d7-9dd56b3a1d0b.png)
![705E795C-DCA1-49E3-9C58-27652CEBEB51](https://user-images.githubusercontent.com/29590985/197611533-89913a16-52f6-41c1-a365-966ad18ba9a7.png)
![E21279D2-D7C6-4CBE-A44F-722B821E36B9](https://user-images.githubusercontent.com/29590985/197611538-9e36a407-f529-4eac-9f82-54301d8952fc.png)
#
![D1F10981-A153-45C8-91FD-91B0EB53804D](https://user-images.githubusercontent.com/29590985/197611633-c76eb37c-d84a-42bc-807b-1cb0565aa1c8.png)

**Comment by opa334** [comment]
issue with the IPA you're trying to install

**Comment by Apibug** [comment]
No problem with the other iPhone

**Comment by opa334** [comment]
maybe your phone storage is full so it can't extract it?

**Comment by Apibug** [comment]
There was no problem with the previous version, but now the installation is 1.2.2
