### ISSUE TITLE
Will ios 15.6.1 support it in the future

### ISSUE THREAD

**Issue by SnailInLeaves** [opa334/TrollStore#314]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Will ios 15.6.1 support it in the future

### Current Behavior?

Will ios 15.6.1 support it in the future

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

ios 15.6.1

### iDevice Model

ipad8

**Comment by Beast9265** [comment]
no
