### ISSUE TITLE
Error 179

### ISSUE THREAD

**Issue by EndermanchYT** [opa334/TrollStore#319]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Error 179
This app you tried has the same identifier as a system app already installed on the device. The installation has been prevented to protect you from possible bootloops or other issues. 

### Current Behavior?

Error 179
This app you tried has the same identifier as a system app already installed on the device. The installation has been prevented to protect you from possible bootloops or other issues. 

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore v1.3

### iOS/iPadOS version

iOS 15.6 RC

### iDevice Model

iPhone X

### Other info of your environment

macOS 12.5

**Comment by opa334** [comment]
What IPA did you try to install?

**Comment by Deja-Wu** [comment]
> What IPA did you try to install?

For myself personally it’s Filza v3.9.8 and AppsManager v1.7.0 which were both already installed previously when jailbroken. Unable to unistall them currently due to u0’s corrupted dpkg error disallowing a successful jailbreak to complete. So either need to be able to overwrite, install concurrently, or ability/option to change bundle IDs.

iPhone11,2
iOS 14.8

**Comment by opa334** [comment]
> > What IPA did you try to install?
> 
> 
> 
> For myself personally it’s Filza v3.9.8 and AppsManager v1.7.0 which both are already installed previously when jailbroken. Unable to unistall them currently now due to u0’s corrupted dpkg bug disallowing a successful jailbreak to complete. So either need to be able to overwrite, install concurrently, or ability/option to change bundle IDs. If any of those options are doable. 
> 
> 
> 
> iPhone11,2
> 
> iOS 14.8

yeah, just edit the bundle identifier in the info.plist yourself

**Comment by Deja-Wu** [comment]
> > > What IPA did you try to install?
> > 
> > 
> > For myself personally it’s Filza v3.9.8 and AppsManager v1.7.0 which both are already installed previously when jailbroken. Unable to unistall them currently now due to u0’s corrupted dpkg bug disallowing a successful jailbreak to complete. So either need to be able to overwrite, install concurrently, or ability/option to change bundle IDs. If any of those options are doable.
> > iPhone11,2
> > iOS 14.8
> 
> yeah, just edit the bundle identifier in the info.plist yourself

Yeah I figured so, which is what I did and was successful with, but was just curious. Is there a reason why though? Because some other IPAs are able to install side-by-side concurrently with no issue, e.g. u0 v8.0.2 which is one I just tested a moment ago…fluke?

**Comment by opa334** [comment]
u0 only installs side-by-side because your sideloaded install already uses a different bundle identifier, it has the team id of your apple account in front of it afaik. Replacing a system app (which all jailbreak apps are installed as) is simply not possible.
