### ISSUE TITLE
TrollStore not showing up after install

### ISSUE THREAD

**Issue by ComeOnBear** [opa334/TrollStore#32]
Device info:
A13 iPhone SE (2020), iOS 15.0

Sideloaded with altstore, used installer, trollstore not showing up even after respring or reboot.
(respring done using Jaility)

**Comment by ender** [comment]
try downloading version 1.0.1 instead. i had the same issue and this worked for me

**Comment by ComeOnBear** [comment]
> try downloading version 1.0.1 instead. i had the same issue and this worked for me

Fixed issue! Thanks!
shouldnt happen though,

**Comment by ComeOnBear** [comment]
-

**Comment by opa334** [comment]
I'm looking into it now
