### ISSUE TITLE
iPhone 13 iOS 15.6.1 don't start

### ISSUE THREAD

**Issue by ntssGH** [opa334/TrollStore#325]
i'm install app and GTA Car Tracker don't start, after start white screen (~1second) before close app. Can anyone help me with this problem? After reboot it don't fix

**Comment by pytwj** [comment]
TrollStore works on iOS 14.0 - 15.4.1, on iOS 15.5 beta 1 - iOS 15.5 beta 4 and on iOS 15.6 beta 1 - iOS 15.6 beta 5.

iOS 15.5 RC / full build is NOT supported.

Anything higher than iOS 15.6 beta 5 (including iOS 15.6 RC / full build) is NOT supported.

Anything lower than iOS 14.0 is NOT supported.

Anything not supported right now will NEVER be supported, TrollStore is a one time thing, it will not receive compatibility updates in the future, please stop asking about it, GitHub issues regarding version support will be closed without an answer.

**Comment by tom-snow** [comment]
> i'm install app and GTA Car Tracker don't start, after start white screen (~1second) before close app. Can anyone help me with this problem? After reboot it don't fix

Did you read `README.md` before create an issue?
