### ISSUE TITLE
The xctest ipa package installation prompt error code 175

### ISSUE THREAD

**Issue by cuijixiong1** [opa334/TrollStore#328]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

We tested multiple ipas and they all worked normally, but the xctest ipa package could not be installed

### Current Behavior?

We tested multiple ipas and they all worked normally, but the xctest ipa package could not be installed;
Package download connection that cannot be installed https://d.accjs.cn/java/AccbotSevice.ipa

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2 1.3.2

### iOS/iPadOS version

15.3

### iDevice Model

 iPhone 7

**Comment by esoman888** [comment]
me toooo

**Comment by opa334** [comment]
Nothing I can do about, you can try using ldid -s <path/to/.app> on a Mac to figure this issue out. Ldid just does not like it.

The error seems to be "Unsupported Mach-O type"
