### ISSUE TITLE
trollstorehelper

### ISSUE THREAD

**Issue by zhaoshuaige** [opa334/TrollStore#332]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I am rewriting your code but I have a problem how do I download it or where can I get trollstorehelper
<img width="774" alt="image" src="https://user-images.githubusercontent.com/14195299/199694507-e0c2f891-8f31-4f54-b05d-6511d20b864b.png">

### Current Behavior?

NSString* rootHelperPath(void)
{
	return [[NSBundle mainBundle].bundlePath stringByAppendingPathComponent:@"trollstorehelper"];
}
Where does the trollstorehelper in this code get it

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

1.3.2

### iOS/iPadOS version

15.2

### iDevice Model

iPhone X

**Comment by opa334** [comment]
trollstorehelper code is in the RootHelper directory
