### ISSUE TITLE
[Request] No URL scheme option?

### ISSUE THREAD

**Issue by silikonz** [opa334/TrollStore#344]
Thanks for TrollStore. It's a truly useful tool; however, I think there are several issues with the new URL scheme.

Firstly, I have a small vision impairment, so I've made a few specialised workflows on top of the Magnifier URL scheme, which I use often.

Secondly, wouldn't the scheme pose a security risk and expose more issues? Even if TrollStore may ask whether to confirm the install of an app that may be very privileged, this still seems too dangerous.

I propose the following:
a separate no URL scheme version, similar to Filza, or a toggle in TrollStore settings to remove the URL scheme (which may or may not be feasible). Thanks!

**Comment by opa334** [comment]
I will consider making a toggle for the URL scheme.

**Comment by opa334** [comment]
Added in 1.4.
