### ISSUE TITLE
Many ipas show failed to open and isn’t opening from trollstore. Any fix??

### ISSUE THREAD

**Issue by fasihqazi** [opa334/TrollStore#349]
![IMG_1748](https://user-images.githubusercontent.com/113187772/201463280-1006ac4e-ed07-4c4c-9796-23692d5c344f.png)

**Comment by fasihqazi** [comment]
The apps crash without their own screen and show transparent background of home btw when opened from home screen like this

**Comment by fasihqazi** [comment]
It crashes when opening from home screen btw

**Comment by opa334** [comment]
then the IPA is broken, try also rebuilding icon cache in TrollStore settings.
