### ISSUE TITLE
Apps installed with TrollStore do not show up in iTunes/Finder

### ISSUE THREAD

**Issue by egigoka** [opa334/TrollStore#35]
macOS 12.5.1 MBA m1
apps installed via AltStore show up just fine, but with TrollStore they aren't in the list of apps.

STR: 
1) Connect iPhone to Mac with cable
2) Open Finder, go to Locations > iPhone, and open the tab Files

Expected result:
apps installed via TrollStore will show up in the list of apps

Experienced result:
apps installed via TrollStore are not in the list of apps

**Comment by opa334** [comment]
Expected because app plugins don't work currently

**Comment by opa334** [comment]
https://github.com/opa334/TrollStore/issues/38
