### ISSUE TITLE
Can’t open app

### ISSUE THREAD

**Issue by kittyrevvy** [opa334/TrollStore#352]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I expected to open the app and be able to download TrollStore as it says.

### Current Behavior?

If doesn’t let me open the app! It kicks me out the moment I open the app.

### TrollStore Version

Trollinstaller1

### iOS/iPadOS version

IOS 15.5

### iDevice Model

Ipad 8

**Comment by kittyrevvy** [comment]
By the way I am not of age yet so ignore any mistakes in this 💕

**Comment by opa334** [comment]
iOS 15.5 is not supported and never will be.
