### ISSUE TITLE
Unable to install apps

### ISSUE THREAD

**Issue by AnthonyGress** [opa334/TrollStore#357]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

It should allow for delete and reinstalling of apps, previous versions worked

### Current Behavior?

When I installed and then uninstalled an app, I got an error saying that a TrollStore app already exists and an option to force install. There was no app as I just deleted it through troll store so I force installed. App didn’t show. Now even older version of TrollStore cannot install apps. 

### Possible Solution?

-n/a

### Steps to Reproduce

-install TrollStore 1.4
- delete app from within ts 
- Install app
- Doesn’t show on Home Screen, can’t install any other apps

### TrollStore Version

1.4

### iOS/iPadOS version

14.7.1

### iDevice Model

iPhone 11 Pro Max

**Comment by Tiaoge-tou** [comment]
I have the same problem

**Comment by Tiaoge-tou** [comment]
And after this problem occurs, the app installed with a certificate signature will not appear on the desktop. The application installed from the appstore will prompt that the access restrictions cannot be opened. Finally, I downgraded the version of trollstore. After restarting the device many times, the icon will not appear on the desktop.

**Comment by Tiaoge-tou** [comment]
And after this problem occurs, the app installed with a certificate signature will not appear on the desktop. The application installed from the appstore will prompt that the access restrictions cannot be opened. Finally, I downgraded the version of trollstore. After restarting the device many times, the icon appears on the desktop.

**Comment by Tiaoge-tou** [comment]
This problem seems to be easy to trigger on ios14.

**Comment by FlexingTiger** [comment]
Same issue on ipad mini5(14.7.1).

**Comment by AnthonyGress** [comment]
Fixed in 1.4.1
