### ISSUE TITLE
Iphone 12 pro max 15.1.1 no trollstore after install

### ISSUE THREAD

**Issue by bob6716** [opa334/TrollStore#36]
I'm not sure if this is a known issue as I didn't see in the list of issues but I sideloaded TrollStore Installer and clicked on "Install". However, nothing showed up on my homescreen. Even after reboot nothing was there. Is this a known issue? I am on version 1.0.2.

**Comment by rubenizag** [comment]
Mines as well, I have the same model. I checked storage to see if the app was installed. Only saw the installer so I went to install again, reboot and no app.

**Comment by dxwil** [comment]
Make sure you search for it, because it won't show up in the recently added section in the App Library.

**Comment by opa334** [comment]
will look into it now, use the 1.0.1 installer for now

**Comment by bob6716** [comment]
I used 1.0.1 like Opa said and it worked fine. Then I used the link in his Twitter and installed 1.0.2 and it's now updated.

**Comment by rubenizag** [comment]
This is exactly what I was gonna try, glad to hear it worked fine.

**Comment by opa334** [comment]
Fixed in 1.0.3.
