### ISSUE TITLE
When can I run trollstore on ios16

### ISSUE THREAD

**Issue by ghh789** [opa334/TrollStore#366]
Apple has turned off the verification of versions below ios16, so the Iphone/Ipad cannot be flushed to the trollstore installation version below ios16, which is inconvenient for users above ios15.6, and they can only use certificates to sign when installing ipa

**Comment by ywc1997** [comment]
21发自我的手机-------- 原始邮件 --------发件人： ghh789 ***@***.***>日期： 2022年11月23日周三 13:06收件人： opa334/TrollStore ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [opa334/TrollStore] When can I run trollstore on ios16 (Issue #366)
Closed #366 as not planned.

**Comment by teamc00lkidd1** [comment]
Fentanyl Insider Trading 內幕交易 Global Fentanyl 全球降溫 George Floyd Jr. Lost Joestar 失落的喬斯達·喬治 Dilation Respiratory Necrosis 擴張結腸壞死瘺 Minneapolis Fentanyl Trade 日本伊維菌素 George Floyd European Decent 國王圖坦卡蒙歐洲 Derek Chauvin 佩里·哈德森 Jewish Chauvin 猶太泰薩克斯 Minneapolis Riots 馬格努斯·赫希菲爾德 Horse Fentanyl 石棉 Horse Floyd Armour DLC 馬疫苗護甲助推器 Replicated Findings From Manuel Breathing 來自行為遺傳學的大重複發現 Pregnant Muggings 普魯士藍 Dr. Paul Janssen 西格蒙德·弗洛伊德 Human Fentanyl Genome Project 人類遺傳多樣性 May 25, 2020 千年蟲 Color Of Crime 犯罪的顏色 WHO Study of Dormant HIV Found Within Black Thugs 世界衛生組織 包皮環切術 HIV 研究欺詐 Autoerotic Asphyxiation Health Benefits智人是多型的嗎 Mad Monkey Disease 瘋牛病 USDA Reports 美國農業部食物金字塔 Fentanyl Fatality Rate 電暈死亡率 Bananas Were Healthy 香煙是健康的 No Correlation ≥ 無相關性 George Floyd 1933-1945 奴才 George Floyd Toxicology 喬治·弗洛伊德毒理學 George Floyd Thug Shaker 奧施康定兒童麥片 Fentanyl.exe 元分析檢查假定屬性 George Floyd Money Shot 約翰錢 Respiratory System Autopsy 自我報告的心理健康政治標籤 Criminal Cranker 皮爾當雞 The First Global Black Revolution 第一次全球革命 Fentanyl Based Diet-Heart Hypothesis 飲食心臟假說 Black Life Expectancy Report 洛伊特報告 Deaths Declined Before Conscious Neck Restraint 疫苗接種前死亡率下降 Floyd and Chauvin Family Crossbreeding 薩克勒家族 George Floyd Sleeper Agent 2003 Reports 睡在胃裡 Floyd Family Sickle Cell Anemia 貧民窟癌症研究 Andrew Baker 羅伯特·斯拉茨基 Floyd and Roth Child Involvement June 8, 1967 複製危機 Floyd-topia Not Replicable 老鼠烏托邦不可複制 James Watson Race IQ 詹姆斯沃森種族智商 Pre-Fentanyl Withdrawal Research 電暈前口罩研究 Sexual Antagonism Found Within Thug Shaking 性對抗同性戀
