### ISSUE TITLE
Can't install/update apps from Appstore

### ISSUE THREAD

**Issue by heinekenpsx** [opa334/TrollStore#369]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I'm not sure if this problem is TrollStore related or not, but I remember this error appeared when I updated Trollstore to v1.3.5, then I downgraded back to 1.3.2.
Currently I cannot install or update apps in the appstore. When I try to install an ipa file with Terminal (I use myinst and appinst) the following error occurs :
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(4294967295) failed'
*** First throw call stack:
(0x1a351d9d8 0x1b7886b54 0x1a47d9038 0x1a46bc2a4 0x102cfba6c 0x102cf4cf8 0x1a3175568)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
P/s installing ipas via Trollstore is fine

### Current Behavior?

Can't install/update apps, can't install any ipas

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

1.4.4

### iOS/iPadOS version

iOS 14.3

### iDevice Model

iphone X

**Comment by opa334** [comment]
appinst is broken since forever.

No idea what the issue with installing stuff from App Store is, it's definitely not related to TrollStore though.

**Comment by heinekenpsx** [comment]
> appinst is broken since forever.
> 
> No idea what the issue with installing stuff from App Store is, it's definitely not related to TrollStore though.

I don't think it's broken because i was able to use it before
Anyway, thank you for your reply

**Comment by heinekenpsx** [comment]
@opa334 
Try to install an encrypted ipa via appsync, can you help me ?
https://ibb.co/5B4bfkN

**Comment by opa334** [comment]
> @opa334 Try to install an encrypted ipa via appsync, can you help me ? https://ibb.co/5B4bfkN

no clue, sorry. maybe some directory permissions are wrong on your device?
