### ISSUE TITLE
[Bug] Reinstalling app from Appstore after installing with TrollStore

### ISSUE THREAD

**Issue by AymenKcm1** [opa334/TrollStore#37]
When you install a tweaked app (MessengerShark for example) and it shows in TrollStore's list, and then you redownload the original app from Appstore it replaces the tweaked app but it stays in TrollStore's list, if you try to delete it from there it deletes the app right after it in the list with it.

Video: 

https://user-images.githubusercontent.com/67245917/188289952-83ce942b-8592-4b65-8d3e-0c57b585feff.MOV

**Comment by opa334** [comment]
I don't think there is a way to fix this
