### ISSUE TITLE
Too sad

### ISSUE THREAD

**Issue by mokatrs** [opa334/TrollStore#375]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Can you add support for iso 15.5 

### Current Behavior?

Make it possible 

### Possible Solution?

-nothing 

### Steps to Reproduce

-nothing 

### TrollStore Version

TrollStore ota

### iOS/iPadOS version

15.5

### iDevice Model

iPhone 7

**Comment by dontbanmeplz** [comment]
Not possible core trust bug is patched, please delete this issue and give me a sec so i can look at your git account to insult you

**Comment by mokatrs** [comment]
> Not possible core trust bug is patched, please delete this issue and give me a sec so i can look at your git account to i
