### ISSUE TITLE
1.4.5b1 The app cannot be stored in folders.

### ISSUE THREAD

**Issue by gujiaming2022** [opa334/TrollStore#376]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

After Rebuild Icon Cache, apps installed through Trollstore in the folder will leave the folder and restore their original location.

### Current Behavior?

After Rebuild Icon Cache, apps installed through Trollstore in the folder will leave the folder and restore their original location.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

Trollstore 1.4.5b1

### iOS/iPadOS version

iOS15.4

### iDevice Model

iPhone12ProMax

**Comment by opa334** [comment]
fixed in 1.4.5 final
