### ISSUE TITLE
Some software cannot be reinstalled after being deleted

### ISSUE THREAD

**Issue by lovedreamland** [opa334/TrollStore#377]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

https://pan.ios98.com/TrollStore/CallAssist(trollstore).ipa
For example, when I install these software, I delete it from the TrollStore and install it again. It can be installed normally, but there is no icon on the desktop. Running the software from the TrollStore also prompts failure.
However, I can modify the package path of this software and it will work again.
However, after deletion, the problem will still be solved again, unless the package name is changed again.

### Current Behavior?

After the software is installed, remove it and reinstall it. The desktop has no icon and cannot be used

### Possible Solution?

-Modify the package path and repackage for installation

### Steps to Reproduce

-Install the software, delete it in the TrollStore, and reinstall the software again. The software displays that the installation is successful, but there is no icon on the desktop. Open it in the TrollStore, and you will be prompted that it cannot be loaded.

### TrollStore Version

1.4.4

### iOS/iPadOS version

14.8.1

### iDevice Model

iphone xs max

**Comment by opa334** [comment]
This has already been fixed in 1.4.1, idk it will right now only still trigger if your app identifier starts with `com.apple`, this will be fixed in 1.4.5 though.
