### ISSUE TITLE
Deleting TrollStore apps

### ISSUE THREAD

**Issue by AronL** [opa334/TrollStore#378]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I should be able to delete TrollStore-installed apps from the home screen.

### Current Behavior?

According to the release notes, deletion has been re-enabled from the the springboard, but I am not seeing that option. Only ‘Remove from Home Screen.’

### Possible Solution?

-

### Steps to Reproduce

Attempt to delete an app as you normally would.

### TrollStore Version

1.4.5

### iOS/iPadOS version

15.1.1

### iDevice Model

14 Pro

**Comment by opa334** [comment]
You need to rebuild icon cache for the option to uninstall to appear.

**Comment by AronL** [comment]
Thanks for letting me know! I’ll give that a try.

**Comment by AronL** [comment]
All sorted out!
