### ISSUE TITLE
App plugins do not work

### ISSUE THREAD

**Issue by opa334** [opa334/TrollStore#38]
Yes, we all know this now. I have tried fixing it but not sure what's the problem. Hopefully I will find a fix at some point.

EDIT: Notifications work now in 1.0.5. Plugins still don't.

**Comment by ak4zh** [comment]
This also means Keyboard Apps won’t work right?

**Comment by opa334** [comment]
> This also means Keyboard Apps won’t work right?

yes

**Comment by opa334** [comment]
fixed in 1.0.6
