### ISSUE TITLE
Unable to install from File Manager

### ISSUE THREAD

**Issue by xybp888** [opa334/TrollStore#39]
Unable to install from File Manager
![4ED6BF8B-93D7-4CC6-BF65-836E96F8039A](https://user-images.githubusercontent.com/24733048/188290487-522ace10-f3b8-4330-878b-ca3566503b0e.png)

**Comment by opa334** [comment]
no idea

**Comment by xybp888** [comment]
> 

Error when installing from iCloud

**Comment by xybp888** [comment]
> 

1.0.1 No error occurred when installing from iCloud

**Comment by hydrationMan** [comment]
Same problem here, 1.0.1/1.0 are the only ones that have worked thus far for me.

**Comment by xybp888** [comment]
> Same problem here, 1.0.1/1.0 are the only ones that have worked thus far for me.

yes

**Comment by opa334** [comment]
will be fixed shortly

**Comment by opa334** [comment]
should be fixed in 1.0.5
