### ISSUE TITLE
Apps downloaded using ipatool do not launch

### ISSUE THREAD

**Issue by alnmy** [opa334/TrollStore#393]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

App launches

### Current Behavior?

I download Outplayer (com.stps.outplayer) using ipatool and install it using TrollStore. App crashes. 
I download Outplayer from the app store. Perfectly fine.

I thought this could be because so far I haven't signed into iCloud on this device but signing in doesn't seem to help with anything.
I tried installing from appstore and then force installing using trollstore but this just seemed to softlock my phone (no apps were launching and only the basic system functionality seemed to work but i was stuck on a grey screen)

I have many other apps installed using Trollstore and all of them work

https://user-images.githubusercontent.com/67667676/207971213-04425d0c-03e6-401f-b003-adb6d0cc06e1.mov

### Possible Solution?

-

### Steps to Reproduce

- Use ipatool to download bundle identifier com.stps.outplayer
- Launch app

### TrollStore Version

Trollstore 1.4.5

### iOS/iPadOS version

iOS 15.1

### iDevice Model

iPhone Xs

### Other info of your environment

Windows 10 LTSC 2021 used to download the IPA

**Comment by opa334** [comment]
Just use Sideloadly "Normal Install" option to install the IPA, using TrollStore is not needed here.
