### ISSUE TITLE
Cannot install retro arch

### ISSUE THREAD

**Issue by seropigeorgedev** [opa334/TrollStore#394]

**Comment by seropigeorgedev** [comment]
Debug log:
2022-12-17 14:18:26.152 trollstorehelper[549:21720] trollstore helper go, uid: 0, gid: 0
Write failed
Write failed
Write to restore size failed
2022-12-17 14:18:28.542 trollstorehelper[549:21720] returning 168

**Comment by opa334** [comment]
ldid error, nothing I can do about, there probably is something wrong with the IPA

**Comment by seropigeorgedev** [comment]
Im sorry there was something wrong with my ipad (storage) it's not trollstore
