### ISSUE TITLE
Safari Downloads Break

### ISSUE THREAD

**Issue by Delamcode** [opa334/TrollStore#395]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Safari would download normally.

### Current Behavior?

The file claims to have been downloading, but files and filza say it is incomplete.

### Possible Solution?

Respiringing does not fix it, but rebooting does. This may have something to do with filza? 

### Steps to Reproduce

Not sure, but filza may have something to do with it?

### TrollStore Version

Installer2, 1.4.5

### iOS/iPadOS version

iPadOS 15.5b4

### iDevice Model

iPad Air 5

**Comment by opa334** [comment]
This really cannot in any way be caused by TrollStore
