### ISSUE TITLE
Trouble Installing Larger Apps

### ISSUE THREAD

**Issue by nick-botticelli** [opa334/TrollStore#4]
Environment: iPhone 13 Pro 15.1.1 (19B81)

Attempting to install large applications (such as 120 MB) seems to be unsuccessful, as the app does not appear under the listing even after waiting 10 minutes in the app. Others on Twitter appear to have the same issue.

**Comment by opa334** [comment]
Will look into this tomorrow

**Comment by Peng1029** [comment]
I personally have this problem for uyou+ if you need an app to test

**Comment by opa334** [comment]
Should be fixed in 1.0.1.
