### ISSUE TITLE
Update without losing signed apps

### ISSUE THREAD

**Issue by AlawiYNWA** [opa334/TrollStore#40]
Hello 
How to update the trollstore without delete it ? 
i try open it via trollstore but nothing happen
Any idea?
Thanks

**Comment by pytwj** [comment]
Trollstore has an OTA update mechanism. When a new version is released, you can download trollstore from GitHub Tar file and open it in trollstore, which will update all contents (including persistence assistant) and restart.

**Comment by AlawiYNWA** [comment]
Thank you 🙏🏻
