### ISSUE TITLE
I updated to ios 16 and all my apps (including trollstore) stopped working

### ISSUE THREAD

**Issue by Marqap** [opa334/TrollStore#406]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I expected it to stay there

### Current Behavior?

But it was like a scar app

### Possible Solution?

To fix it make an ios 16 verison or else…

### Steps to Reproduce

Try remaking it for ios 16
Share It To The Public
Add It To Github
Respect others
Make it every time you update ios it asks you if you update ios it might break trollstore

### TrollStore Version

TrollInstaller1

### iOS/iPadOS version

16.2

### iDevice Model

iPad 8

### Other info of your environment

ipados 16.2

**Comment by Marqap** [comment]
I hope u fix it such big fan

**Comment by opa334** [comment]
<img width="677" alt="Screen_Shot_2018-10-25_at_11 02 15_AM" src="https://user-images.githubusercontent.com/18235760/211032440-0e6087b9-1dcf-4d5b-82e4-dffc8407f1f2.png">

**Comment by darkestcore** [comment]
godly
