### ISSUE TITLE
You hacked me and closed my thread without fixing it

### ISSUE THREAD

**Issue by Marqap** [opa334/TrollStore#418]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I expected you to fix the bug :((((((((((((((((((((((((((((((((((((((

### Current Behavior?

You didn’t Fix The Bug

### Possible Solution?

In closed thread

### Steps to Reproduce

In closed thread

### TrollStore Version

TrollInstaller2 idiot

### iOS/iPadOS version

16.2

### iDevice Model

iPad 8

### Other info of your environment

The Newest Theos Idiot

**Comment by AronL** [comment]
This is a joke, right?

**Comment by opa334** [comment]
No, you came here and opened a stupid issue without reading the README, not my problem.
