### ISSUE TITLE
Install Error IPhone 12 ios 15.0

### ISSUE THREAD

**Issue by MrBrownie124** [opa334/TrollStore#42]
The Ipa Dose Not Exist or is Not Accessible

**Comment by LevRost2306** [comment]
You should install from local drive, not iCloud.

**Comment by Eclyzia** [comment]
I have exactly the same problem. My IPA is in the "Files" folder. When I try to install it, it gives me this error: 

Install Error 166.
The IPA file does not exist or is not accessible.

**Comment by opa334** [comment]
fixed in 1.0.5
