### ISSUE TITLE
When will ios16+ be supported？

### ISSUE THREAD

**Issue by zhaoxinkun** [opa334/TrollStore#421]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I would like to ask developers to support ios16+ as soon as possible

### Current Behavior?

I would like to ask developers to support ios16+ as soon as possible

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

ios16.2

### iDevice Model

iphone13

### Other info of your environment

ipados16.2

**Comment by opa334** [comment]
Clearly answered in the readme
