### ISSUE TITLE
Some apps installed through trollstore not working properly 

### ISSUE THREAD

**Issue by Rei-rahul** [opa334/TrollStore#425]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

App working probably

### Current Behavior?

When installing app through trollstore, some features of that app not working properly due to how trollstore sign it upon setup. For example: anime now is not able to download any episodes after installing it through trollstore, despite working absolutely fine when installed with sideloadly.

More information here:
[https://github.com/AnimeNow-Team/AnimeNow/issues/51](https://github.com/AnimeNow-Team/AnimeNow/issues/51)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

145

### iOS/iPadOS version

iOS 15.4

### iDevice Model

iphone xs max

**Comment by opa334** [comment]
https://github.com/AnimeNow-Team/AnimeNow/issues/51#issuecomment-1405649734
