### ISSUE TITLE
Problems encountered in use

### ISSUE THREAD

**Issue by 239144498** [opa334/TrollStore#43]
A small suggestion, I hope to indicate the software version number on the app interface.
A somewhat strange operation, when I installed the new version of TrollStore with the old version of TrollStore, click the install button in the new version of TrollStore and the device restarted, and then I put
After the old version of TrollStore was removed, I'm not sure if the new version of TrollStore is taking effect.

**Comment by 239144498** [comment]
Supplementary information: Using device ipad9, version 15.0

**Comment by pytwj** [comment]
Version number at the bottom of rollstore settings

**Comment by pytwj** [comment]
![image](https://user-images.githubusercontent.com/62314967/188294747-8bde3d54-414e-44fa-b5ac-f43625d619a8.png)
