### ISSUE TITLE
我想对巨魔助手进行二次开发，我需要帮助。有-偿

### ISSUE THREAD

**Issue by 1007637107** [opa334/TrollStore#437]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

因为功能太少了。我想对巨魔助手进行二次开发，我需要帮助。有-偿。我希望能看懂人联系我。价格不是问题

### Current Behavior?

因为功能太少了。我想对巨魔助手进行二次开发，我需要帮助。有-偿。我希望能看懂人联系我。价格不是问题

### TrollStore Version

 TrollInstaller1.5

### iOS/iPadOS version

iOS 15.1

### iDevice Model

iPhone 8

### Other info of your environment

最新的 THEOS...

**Comment by 1007637107** [comment]
1007637107@qq.com

**Comment by gejianju** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
