### ISSUE TITLE
Will there be an unjailbroken version of ios14.2?

### ISSUE THREAD

**Issue by MagnateXu** [opa334/TrollStore#44]
Will there be an unjailbroken version of ios14.2?

**Comment by MagnateXu** [comment]
Hello developer, 
I would like to ask if the unjailbroken version of ios14.2 will be released in the future, I very much hope that he will work on the unjailbroken ios14, thank you (my device is xr ios14.2)

**Comment by WillXProject** [comment]
I'm sure the jailbroken version works about the same as the ipa, just different things, if it works, tell me!

**Comment by opa334** [comment]
no, just use the jailbroken version
