### ISSUE TITLE
GTA Car Tracker Crashing

### ISSUE THREAD

**Issue by rdc457** [opa334/TrollStore#446]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

It should let me open the app, letting me install trollstore 

### Current Behavior?

when I open GTA car tracker, it crashes and puts me back to my home screen 

### TrollStore Version

TrollHelper (arm64e) 

### iOS/iPadOS version

iOS 15.1

### iDevice Model

iPad 8 generation 

### Other info of your environment

Idk

**Comment by unblockedgames04** [comment]
I am having this same problem with IpadOS 15.6. Have you found a solution?

**Comment by opa334** [comment]
> I am having this same problem with IpadOS 15.6. Have you found a solution?

Please read the readme....

**Comment by bigpowerabc** [comment]
gogogo

**Comment by ChankaPack** [comment]
> 

I have read the readme and  it does not help. I am also on ios 15.5 and am having the same issue

**Comment by opa334** [comment]
> I have read the readme and it does not help. I am also on ios 15.5 and am having the same issue

You clearly have not read the readme.....

**Comment by ChankaPack** [comment]
> > I have read the readme and it does not help. I am also on ios 15.5 and am having the same issue
> 
> You clearly have not read the readme.....

honestly i did cant you just help me instead of being so stuck up?

**Comment by opa334** [comment]
> > > I have read the readme and it does not help. I am also on ios 15.5 and am having the same issue
> > 
> > 
> > You clearly have not read the readme.....
> 
> honestly i did cant you just help me instead of being so stuck up?



15.5 (RC) | Not Supported (CT Bug fixed) | Not Supported (CT Bug fixed)

**Comment by Gqhx89** [comment]
Existing equipment 15.6.1,Already installed TrollStore2。If you upgrade your device to 17.0,Can TrollStore2 still be used normally?
