### ISSUE TITLE
GTA Car Tracker Crashing

### ISSUE THREAD

**Issue by asimzafar202** [opa334/TrollStore#467]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Car tracker app crashes IOS 15.6.1 A15 chip

### Current Behavior?

App crashes and goes back to home screen

### Possible Solution?

Retry install

### Steps to Reproduce

Retry install

### TrollStore Version

TrollHelperOTA (arm64e)

### iOS/iPadOS version

15.6.1

### iDevice Model

Iphone 13 pro max

**Comment by xantiago0** [comment]
iOS 15.6.1 is not supported (CT Bug Patched)
