### ISSUE TITLE
Cannot install troll store I p11  iOS 14.7 

### ISSUE THREAD

**Issue by D0lcegabbana** [opa334/TrollStore#485]
![048654B1-BE4C-4CD8-8E66-637F02B48040](https://user-images.githubusercontent.com/94684662/232251800-183f90e9-abc7-411c-83ec-82fdbf6579f4.png)
Cannot install troll store on iPhone 11 iOS 14.7  link not work https://api.jailbreaks.app/troll64e
With vpn and without vpn link don’t open .

**Comment by magmaus3** [comment]
1. the error message tells you **exactly** what happened
2. it works (at least for me), so it may have been a temporary problem

**Comment by D0lcegabbana** [comment]
Problem solved   
server down only 1 day
