### ISSUE TITLE
Installing Fugu15Max beta7 Error 168

### ISSUE THREAD

**Issue by MaxBuer** [opa334/TrollStore#486]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Why did such a problem happen and how should I solve it?

### Current Behavior?

Installing Fugu15Max beta7 Error 168 
![Uploading 6C059550-A6AE-4D3F-BD89-A44DE5AEF127.png…]()

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

1.5.1

### iOS/iPadOS version

15.4.1

### iDevice Model

iphone12

**Comment by opa334** [comment]
can't reproduce

**Comment by Alex793** [comment]
Hey, just had this same error with a random app, it’s just because my iPad didn’t have enough space. 

In fact I had enough space ~500mb for a 50mb app but error 168 when installing, same error with a 28mb app, so just to check I made some place (7gb free) and no more error 168 👍
