### ISSUE TITLE
URL Scheme doesn't pull-up TrollStore but Apple Magnifier itself

### ISSUE THREAD

**Issue by Liam0205** [opa334/TrollStore#492]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

When not-Jailbroken, press upgrade button of Dopamine should pull-up TrollStore to install the latest Dopamine release.

### Current Behavior?

Apple Magnifier is pulled-up.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

1.5.1

### iOS/iPadOS version

iOS 15.4.1

### iDevice Model

iPhone 13 Pro

### Other info of your environment

-

**Comment by opa334** [comment]
You need to turn on the "URL Scheme" option inside TrollStore in order for it to work
