### ISSUE TITLE
Install Error 175

### ISSUE THREAD

**Issue by asdfzxcvbn** [opa334/TrollStore#504]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

the IPA should be installed normally. tweaks are injected using azule. it installs fine when sideloading normally with an apple dev account/a paid certificate, and even through Filza with appsync unified installed. trollstore is the only installation tool giving this problem. this error has been reported before, but the solutions did not work.

### Current Behavior?

trollstore shows `Installing` for a while before showing the error.

**Install Error 175**
Failed to sign the app. ldid returned a non zero status code.

here's the full debug log:
```
SubstituteLog: Attempted to hook non-existant selector "_addStatusBarIfNeeded" in class "nil"
SubstituteLog: Attempted to hook non-existant selector "trustStateWithTrustRequiredReasons:" in class "nil"
SubstituteLog: Attempted to hook non-existant selector "trustState" in class "nil"
2023-06-14 19:51:15.445 trollstorehelper[1463:28960] trollstorehelper invoked with arguments: (
    install,
    custom,
    "/private/var/mobile/Containers/Data/Application/ACC92650-11B7-4DD7-9C6F-C6130612E375/tmp/com.opa334.TrollStore-Inbox/Instagram_287.0_Rocket_3.8.9_Plus_2.50_OIIExtension_@thisismanpreets_apptesters.org.ipa"
)
2023-06-14 19:51:17.475 trollstorehelper[1463:28960] [installApp force = 0]
2023-06-14 19:51:17.535 trollstorehelper[1463:28960] [dumpEntitlements] dumped {
    "application-identifier" = "MH9GU9K5PX.com.burbn.instagram";
    "aps-environment" = production;
    "com.apple.developer.associated-domains" =     (
        "applinks:instagram.com",
        "applinks:www.instagram.com",
        "applinks:ig.me",
        "applinks:www.instagr.am",
        "applinks:instagr.am",
        "applinks:applink.instagram.com",
        "applinks:familycenter.instagram.com",
        "applinks:call.instagram.com"
    );
    "com.apple.developer.avfoundation.multitasking-camera-access" = 1;
    "com.apple.developer.icloud-container-environment" = Production;
    "com.apple.developer.icloud-container-identifiers" =     (
        "iCloud.com.burbn.instagram"
    );
    "com.apple.developer.icloud-services" =     (
        CloudKit
    );
    "com.apple.developer.kernel.extended-virtual-addressing" = 1;
    "com.apple.developer.kernel.increased-memory-limit" = 1;
    "com.apple.developer.networking.HotspotConfiguration" = 1;
    "com.apple.developer.team-identifier" = 777W53UFB2;
    "com.apple.developer.ubiquity-container-identifiers" =     (
        "iCloud.com.burbn.instagram"
    );
    "com.apple.developer.ubiquity-kvstore-identifier" = "777W53UFB2.com.burbn.instagram";
    "com.apple.developer.usernotifications.communication" = 1;
    "com.apple.security.application-groups" =     (
        "group.com.burbn.instagram",
        "group.com.facebook.family"
    );
    "keychain-access-groups" =     (
        "MH9GU9K5PX.platformFamily",
        "MH9GU9K5PX.shared"
    );
}
2023-06-14 19:51:18.470 trollstorehelper[1463:28960] ldid exited with status 1
2023-06-14 19:51:18.470 trollstorehelper[1463:28960] - ldid error output start -
2023-06-14 19:51:18.470 trollstorehelper[1463:28960] ldid: Failed to parse plist
2023-06-14 19:51:18.470 trollstorehelper[1463:28960] - ldid error output end -
2023-06-14 19:51:18.637 trollstorehelper[1463:28960] trollstorehelper returning 175
```

### Steps to Reproduce

1. download the ipa from direct link using safari
2. select ipa from downloads
3. open in trollstore
4. click install

### TrollStore Version

TrollStore Helper + TrollStore 1.5.1

### iOS/iPadOS version

14.8

### iDevice Model

iPhone 7

### Other info of your environment

dualbooted with dualra1n and jailbroken, however other people are having this same problem

**Comment by swaggyP36000** [comment]
Same issue here, having trouble updating a couple apps because of this issue

**Comment by k3v1nwrld** [comment]
Iirc you can 'downgrade' azule and use the -U option. If ur on ac, use the builds that were released around February, and if ur on linux, use the build from October last '22

**Comment by asdfzxcvbn** [comment]
> iirc you can 'downgrade' azule and use the -U option. If ur on mac, use the builds that were released around February, and if ur on linux, use the build from October last '22

thanks, that seems to have fixed it. im still confused on why this happens in the first place though. ldid complains about not being able to parse the plist even though the ipa works everywhere else
