### ISSUE TITLE
When does TrollStore support iOS/iPadOS 17

### ISSUE THREAD

**Issue by tnt0x** [opa334/TrollStore#509]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Hope TrollStore supports iOS/iPadOS 17

### Current Behavior?

Hope TrollStore supports iOS/iPadOS 17

### Possible Solution?

-Enable TrollStore support on iOS/iPadOS 17

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

iOS 17.0 Public Beta

### iDevice Model

iPad 10

**Comment by gejianju** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
