### ISSUE TITLE
Exceptionally occupies excessive storage space

### ISSUE THREAD

**Issue by Meteony** [opa334/TrollStore#517]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Apps installed through TrollStore should be completely wiped from my device after uninstallation

### Current Behavior?

Data from uninstalled applications persist, though undetected, causing storage space indicated in settings to become unsynced with the actual storage space shown in Filza. No current methods can be applied to detect/free up the excessively occupied storage space.   ![2FD468D0-D56B-482B-9BC0-5A456C182D37](https://github.com/opa334/TrollStore/assets/141850520/464d3465-a348-4b31-a543-1c2af97efba7)
![33F01721-F0B4-4218-9DB5-5A040AEDF290](https://github.com/opa334/TrollStore/assets/141850520/60a9dcf0-3baf-45c6-ac8b-5c13dff076f6)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore 1.5.1

### iOS/iPadOS version

iOS 14.7.1

### iDevice Model

iPhone 11

**Comment by Meteony** [comment]
P.S. This is a serious issue. If TrollStore persists to take up excessive space, storage will eventually be drained, causing bootup failures.

**Comment by opa334** [comment]
apps should be wiped properly when using the installd uninstall method, the custom one has an issue that I haven't gotten around pushing a fix for yet

**Comment by Meteony** [comment]
> apps should be wiped properly when using the installd uninstall method, the custom one has an issue that I haven't gotten around pushing a fix for yet

Is there anything we still can do to get our storage back for now? And if a patch on that is to be delivered in the future, when should we expect it to be landed?

**Comment by Meteony** [comment]
> 

And also. The custom uninstall method was not used for me to trigger this issue, since I remained all settings at default. Iirc I have been using installd uninstall method for every uninstallation of trollstore from the very beginning to now, so guess it may be a new issue.

**Comment by piyush8** [comment]
Hi,
I have iPhone 7 device iOS version 15.7.8
I want to install this App TrollStore. How can I install it can you please help me?
Is it possible ti install on this version.
If you need any more details please let me know.

**Comment by opa334** [comment]
I highly doubt this issue has anything to do with TrollStore.
