### ISSUE TITLE
The description file cannot be installed

### ISSUE THREAD

**Issue by victorli-cn** [opa334/TrollStore#521]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Can successfully install the description file

### Current Behavior?

if I want to install another description file during the use process, I will automatically jump to the app installed using the troll store instead of the installation description file, resulting in the description file being unable to be installed

### Possible Solution?

-Can install the description file normally

### Steps to Reproduce

-I have already installed many IPAs in the troll store, and the latest one is the installation of a shadowrocket in the troll store. When opening a shadowrocket , I need to install a description file to add the certificate. However, when installing the description file now, I will directly jump to other IPAs installed in the troll store

### TrollStore Version

1.5.1

### iOS/iPadOS version

ios 15.0

### iDevice Model

iphone 13

**Comment by opa334** [comment]
Reinstall the app it jumps to until it starts jumping to the right app again.
