### ISSUE TITLE
Will there be an update if the troll store 2 bug is found?

### ISSUE THREAD

**Issue by GreatNateDev** [opa334/TrollStore#543]
This video: https://www.youtube.com/shorts/xhGn3aaGfeQ

**Comment by opa334** [comment]
TrollStore 2 was a joke, I have no idea if this is possible...

**Comment by GreatNateDev** [comment]
If it was though would it happen?

**Comment by opa334** [comment]
If it is possible, of course

**Comment by GreatNateDev** [comment]
Cool

**Comment by GreatNateDev** [comment]
What about this https://youtu.be/6CacTpbb-kQ?si=LgB9MI5wi6peUztJ

**Comment by GreatNateDev** [comment]
I called it xd
