### ISSUE TITLE
Not really an issue who's excited for trollstore on ios 16 to ios 16.6b1 or higher and ios 17

### ISSUE THREAD

**Issue by jackson392** [opa334/TrollStore#548]
### No Duplicates Issue

- [x] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

(:

### Current Behavior?

(:

### Possible Solution?

(:

### Steps to Reproduce

(:

### TrollStore Version

2

### iOS/iPadOS version

16.6.1 b1

### iDevice Model

Iphone se 2020

### Other info of your environment

no

**Comment by olivertzeng** [comment]
Wth bad issue but im exited too!
Hope that will exist!

**Comment by parknich** [comment]
stop making random issues @opa334 close this
