### ISSUE TITLE
Cant install ipa on MTXN2LL/A ipad pro.

### ISSUE THREAD

**Issue by uratrtl** [opa334/TrollStore#55]
Hi, I got Troll installer installed through the alt store and set everything up according to the Reddit thread, but when I try to install an IPA, paperback.IPA, ichan.ipa twitter mod, etc. I get Install error 166, "The IPA files does not exist or is not accessible". I know you can't install ipas through icloud in the files app, so I am making sure the ipas are local to the iPad. I configured the persistence helper to the tips app. Idid is also installed.

**Comment by opa334** [comment]
Are you on TrollStore 1.0.5? If not, update

**Comment by uratrtl** [comment]
Just tried, and the issue is resolved, thanks!
