### ISSUE TITLE
Icons in Apple Files are stuck as trollstore icon

### ISSUE THREAD

**Issue by mak448a** [opa334/TrollStore#569]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I expect the icons to be reset after uninstalling.

### Current Behavior?

After uninstalling trollstore via trollhelper, all the ipa icons in the files app are still trollstore.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

iOS 15.7.2

### iDevice Model

iPhone 6s

### Other info of your environment

Jailbroken iPhone 6s via palen1x

**Comment by opa334** [comment]
Refresh icon cache maybe? Anyways not an issue
