### ISSUE TITLE
iPA installs, but cannot be opened

### ISSUE THREAD

**Issue by ComeOnBear** [opa334/TrollStore#57]
As title says,
iPAs install, but cannot be opened. 

From homescreen: Opens for a split second, then crashes (?) back to the homescreen.
From trollstore app: When clicking on app in list, button stays highlighted but app is still responsive (can still use menus)

Device info:
iPhone SE 2020 (A13), iOS 15.0, non jailbroken.
Trollinstaller sideloaded using AltStore.

**Comment by opa334** [comment]
install ldid in settings page, make sure you're on TrollStore 1.0.5, then reinstall the ipa and try again

**Comment by ComeOnBear** [comment]
I have Idid installed
However i cant use the latest trollstore because it cannot install properly on my device
was referenced before in one of my other issues.
#32 
https://github.com/opa334/TrollStore/issues/32

**Comment by ComeOnBear** [comment]
Thanks for fast response 
I have completely reinstalled trollstore using V1.0.5 but the issue still persists.
reboots and resprings dont fix the issue either.

**Comment by ComeOnBear** [comment]
Issue!
The iPA i was trying to use was just having issues. 
I installed [`This`](https://appdb.to/app/cydia/1900000703) and it worked fine. 
I think appdb is a little shit, the iPA i tried to install before wouldnt even sideload properly
