### ISSUE TITLE
All non-trollstore specific apps seem to crash on launch with bug error 309.

### ISSUE THREAD

**Issue by milankkk** [opa334/TrollStore#573]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

The app in question to open.

### Current Behavior?

Crashes on launch, crash log:

{"app_name":"Aidoku","timestamp":"2023-11-28 00:58:19.00 +0100","app_version":"0.6.6","slice_uuid":"b2c91f32-168f-3352-a2f8-5ec7cc3b16eb","build_version":"2","platform":2,"bundleID":"xyz.skitty.Aidoku","share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"iPhone OS 15.6 (19G71)","incident_id":"38DB9840-DF1F-4FFA-9BD3-785B3923AEB1","name":"Aidoku"}
{
  "uptime" : 900,
  "procLaunch" : "2023-11-28 00:58:19.2154 +0100",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad13,9",
  "procStartAbsTime" : 21701014674,
  "coalitionID" : 508,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.6",
    "releaseType" : "User",
    "build" : "19G71"
  },
  "captureTime" : "2023-11-28 00:58:19.2199 +0100",
  "incident" : "38DB9840-DF1F-4FFA-9BD3-785B3923AEB1",
  "bug_type" : "309",
  "pid" : 505,
  "procExitAbsTime" : 21701095384,
  "cpuType" : "ARM-64",
  "procName" : "Aidoku",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/4A0313C0-813F-4A5C-B1DE-8E78BFB03C15\/Aidoku.app\/Aidoku",
  "bundleInfo" : {"CFBundleShortVersionString":"0.6.6","CFBundleVersion":"2","CFBundleIdentifier":"xyz.skitty.Aidoku"},
  "storeInfo" : {"deviceIdentifierForVendor":"DCAAC428-14FF-46C5-BD9E-07114299D775"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "xyz.skitty.Aidoku",
  "crashReporterKey" : "13557709415bbe3adf3a7ca0df25b5fa79d2c88c",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":518,"code":1,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":[]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":14469,"threadState":{"x":[{"value":6},{"value":1},{"value":6155398424},{"value":149},{"value":6155397400},{"value":0},{"value":0},{"value":2800},{"value":32},{"value":9},{"value":6155397473},{"value":170},{"value":0},{"value":53},{"value":8958145165},{"value":0},{"value":521},{"value":4317000136,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6155397400},{"value":149},{"value":6155398424},{"value":1},{"value":6},{"value":6155397400},{"value":1024},{"value":465},{"value":916}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4317046476},"cpsr":{"value":4096},"fp":{"value":6155397344},"sp":{"value":6155397280},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4317022996,"matchesCrashFrame":1},"far":{"value":4316610560}},"frames":[{"imageOffset":297748,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":321228,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":321280,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":125440,"symbol":"dyld4::halt(char const*)","symbolLocation":580,"imageIndex":0},{"imageOffset":113184,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3560,"imageIndex":0},{"imageOffset":105860,"symbol":"start","symbolLocation":488,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4316725248,
    "size" : 360448,
    "uuid" : "66e1fb26-68f8-379b-a052-eb8b8291b5e1",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6442926080,
  "size" : 2526363648,
  "uuid" : "d9cfde34-5b79-31ba-a93d-2ada0010a887"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=5088K resident=0K(0%) swapped_out_or_unallocated=5088K(100%)\nWritable regions: Total=2144K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2144K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                         16K        1 \nStack                             1008K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                             352K        3 \n__DATA_CONST                       224K        2 \n__LINKEDIT                         672K        2 \n__TEXT                            4416K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             7728K       13 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_HAMMER" : "63f991eb7a214850f5842aba"
      },
      "deploymentId" : 240000614
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
}
}

### Possible Solution?

Seems to be missing a library.

### Steps to Reproduce

-

### TrollStore Version

trollstore-arm64e

### iOS/iPadOS version

15.6

### iDevice Model

iPad Pro 5th gen (12.9 inch)

**Comment by CalderG** [comment]
Did you manage to solve this issue? I have the same problem with Delta Emulator, Provenance, and Jitterbug when installed through TrollStore.

**Comment by milankkk** [comment]
The newest update seemed to fix it for me. Maybe try reinstalling trollstore? Which iphone do you have?

**Comment by CalderG** [comment]
> The newest update seemed to fix it for me. Maybe try reinstalling trollstore? Which iphone do you have?

I managed to fix the issue by toggling on Developer Mode again and then uninstalling and reinstalling the apps that were causing the issues. After that I didn't get any more crashes with error code 309.
