### ISSUE TITLE
App launch crash

### ISSUE THREAD

**Issue by JQJoe** [opa334/TrollStore#578]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

After launching the app installed from Trollstore 2.0.4, it crashes.

### Current Behavior?

Same as

### Possible Solution?

Same as

### TrollStore Version

TrollStore v2.0.4

### iOS/iPadOS version

iOS 16.4

### iDevice Model

iPhone 14 Pro

### Other info of your environment

iOS 16.4

**Comment by swvv** [comment]
IOS 16.1.1 iPhone se2 has same problem.

**Comment by JQJoe** [comment]
fixed at 2.0.5
