### ISSUE TITLE
TrollStore works on iOS 16 however some apps don't work.

### ISSUE THREAD

**Issue by Pogchamp2000** [opa334/TrollStore#579]
When I install apps like Spotify deluxe, UTM (TrollStore Version), and cowabunga the app crashes and for some reason when I sign it with TrollStore even though the app is intended for designed for TrollStore or originally designed for TrollStore however when I install apps like UTM, Spotify deluxe, and Cowabunga on IOS 15. The app works just as normally, when I install apps intended for iOS 15 like AppStore++, TrollTools, DebToIPA, and Uyou++ (Trollstore version) (Iphone Xr Version 16.1.2)

**Comment by Pogchamp2000** [comment]
This problem still prosists on the versions on with Security.framework, and Idid signing

**Comment by hardwork-anytime** [comment]
Still persist on 2.05version

**Comment by nakheel77** [comment]
Does TrollStore 2 work on iOS 16.6.1 ? Many thanks!

**Comment by opa334** [comment]
all issues like these should be fixed in 2.0.6
