### ISSUE TITLE
install response return 1

### ISSUE THREAD

**Issue by biankobe24** [opa334/TrollStore#584]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

successed install TrollStore2

### Current Behavior?

1 Misaka click Toolbox to install TrollStore, success
2 click tips then resping, success
3 open tips then install TrollStore, response returned 1

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.05

### iOS/iPadOS version

16.5

### iDevice Model

13 pro max

**Comment by bg7758** [comment]
the same problem,trollstorehelper returned 1

**Comment by sss768** [comment]
the same problem, returned 1, ios 16.5, iphone 13 pro
