### ISSUE TITLE
iPhone12 16.3 Installation Failure with Misaka

### ISSUE THREAD

**Issue by liiiuyang** [opa334/TrollStore#585]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

fine

### Current Behavior?

failed

### Possible Solution?

-

### Steps to Reproduce

1.install  Misaka
2.Packages(Emu/var) 
3.Install TrollStore 
4.choose tips
Then：
automatic reboot and open tips No change

Tried it many times.

### TrollStore Version

TrollStore2

### iOS/iPadOS version

iOS16.3

### iDevice Model

iPhone12

**Comment by shx2129** [comment]
same with me, my ios version is 16.1.2, device is iphone13
