### ISSUE TITLE
Unable to install Idid, there is no response when clicked. Many people have reported this issue. Is it a system issue or a need to wait for further repairs?

### ISSUE THREAD

**Issue by liudeiang** [opa334/TrollStore#588]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Unable to install Idid, there is no response when clicked. Many people have reported this issue. Is it a system issue or a need to wait for further repairs?

### Current Behavior?

Unable to install Idid, there is no response when clicked. Many people have reported this issue. Is it a system issue or a need to wait for further repairs?

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore 2.0.5

### iOS/iPadOS version

IOS 16.3.1

### iDevice Model

iPhone 13

**Comment by Matzoh** [comment]
me too

**Comment by opa334** [comment]
duplicate of https://github.com/opa334/TrollStore/issues/590
