### ISSUE TITLE
Thank you very much for solving the notification push. But there's a new problem:Screenshot cannot be sent via wechat.

### ISSUE THREAD

**Issue by 95716354** [opa334/TrollStore#59]
Thank you very much for solving the notification push. But there's a new problem:Wechat installed through trollstore,Screenshot cannot be sent via wechat.Wechat cannot be found because of the send option.
![Uploading 7B8DB670-836D-4B86-B36A-571483FF19DF.png…]()

**Comment by 95716354** [comment]
![Uploading F1FF1A70-612A-46D6-83F8-922D0E60E90E.png…]()

**Comment by 95716354** [comment]
When I took a screenshot, I couldn't quickly send a picture to wechat with my iPhone.

**Comment by Peng1029** [comment]
The share sheet? I think 1.7 fixed this but for example it’s  still kinda buggy for apps like discord giving network error

**Comment by 95716354** [comment]
Yes, it was later discovered that, to be precise, the sharing module couldn't find all the programs installed with troll.

**Comment by HuChundong** [comment]
any update?

**Comment by HuChundong** [comment]
it was because dump ipa issue.
you need to dump all plugins in *.app too.
