### ISSUE TITLE
Ldid not installing

### ISSUE THREAD

**Issue by Matzoh** [opa334/TrollStore#590]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

ipa Install error 175, click to install the ldid button without any reaction.

My network is very smooth and fast.

<img width="221" alt="image" src="https://github.com/opa334/TrollStore/assets/19823952/39f0fc87-0b5a-4e7c-b7e8-ba806f76a274">

### Current Behavior?

Can't install ldid
no response

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.5

### iOS/iPadOS version

iOS 16.3.1

### iDevice Model

iPhone13 Pro Max

**Comment by opa334** [comment]
Definitely a network issue though

**Comment by hjjhhgc** [comment]
I met the same problem

**Comment by im5033** [comment]
I have the same problem
ios 16.0
iPhone 13

**Comment by georgenoob1234** [comment]
Same problem iOS 16.5 iPhone 14

**Comment by opa334** [comment]
Potential fix

https://x.com/phonephone731/status/1729482386327621892?s=46

**Comment by georgenoob1234** [comment]
that worked thank you!1!1!

**Comment by kai2ou** [comment]
> Potential fix
> 
> https://x.com/phonephone731/status/1729482386327621892?s=46

参照上面的方法搞定了！一开始用qx开全局代理还是不行，后面改用小火箭1次就成功了，给力！

**Comment by shx2129** [comment]
> > Potential fix
> > https://x.com/phonephone731/status/1729482386327621892?s=46
> 
> 参照上面的方法搞定了！一开始用qx开全局代理还是不行，后面改用小火箭1次就成功了，给力！

I used shadowrocket, still failed to install Ldid

**Comment by Matzoh** [comment]
Try to change "Tun Only" to "Http Proxy & Tun Only"

I succeeded

**Comment by xuewencao** [comment]
换了好几个VPN终于解决了

**Comment by Shengdujun** [comment]
> 换了好几个VPN终于解决了

最后用的哪个vpn软件啊

**Comment by ShketRybee** [comment]
ShadowSocks OBFS HTTP with USA server on Shadowrocket helped. The ldid was set automatically after reinstalling the TrollStore. It is also worth noting that the installation did not occur with other VPNs, I do not know if it is related to the servers or the protocols themselves. iPhone 11, Chinese model (A2223), iOS 16.4

**Comment by Shengdujun** [comment]
> ShadowSocks OBFS HTTP with USA server on Shadowrocket helped. The ldid was set automatically after reinstalling the TrollStore. It is also worth noting that the installation did not occur with other VPNs, I do not know if it is related to the servers or the protocols themselves. iPhone 11, Chinese model (A2223), iOS 16.4
> 
> 

牛 solved

**Comment by NasserL1** [comment]
> ### No Duplicates Issue
> * [x]  I'm sure I've searched on the issue tracker before creating one.
> 
> ### Expected Behavior?
> ipa Install error 175, click to install the ldid button without any reaction.
> 
> My network is very smooth and fast.
> 
> <img alt="image" width="221" src="https://private-user-images.githubusercontent.com/19823952/286223743-39f0fc87-0b5a-4e7c-b7e8-ba806f76a274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTk3NDgsIm5iZiI6MTcwNzgxOTQ0OCwicGF0aCI6Ii8xOTgyMzk1Mi8yODYyMjM3NDMtMzlmMGZjODctMGI1YS00ZTdjLWI3ZTgtYmE4MDZmNzZhMjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEwMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MGU3YzM0ODYyM2YwMDNkZjEzMzU0YTc3NDBjNzg0NDJjMzdjNWQwZWViN2E5MjJhZmFmYTMwZDdiMTdkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jp-gsKWDQ_TvCnoYNANXqUIUHR77A0Zt15A27fonmUE">
> ### Current Behavior?
> Can't install ldid no response
> 
> ### Possible Solution?
> 
> ### Steps to Reproduce
> 
> ### TrollStore Version
> 2.0.5
> 
> ### iOS/iPadOS version
> iOS 16.3.1
> 
> ### iDevice Model
> iPhone13 Pro Max
> 
> ### Other info of your environment
> _No response_

O
