### ISSUE TITLE
Can 15.6.1 upgrade to 17.0TrollStore2 be used normally?

### ISSUE THREAD

**Issue by Gqhx89** [opa334/TrollStore#591]
Existing equipment 15.6.1,Already installed TrollStore2。If you upgrade your device to 17.0,Can TrollStore2 still be used normally?

**Comment by opa334** [comment]
Maybe if you set up a persistence helper beforehand, feel free to try.

**Comment by Gqhx89** [comment]
> Maybe if you set up a persistence helper beforehand, feel free to try.

I mean OTA delayed upgrade to 17.0, I don't know if it's ok.I'm a beginner and I don't know much about it, so I'll ask.Thanks for the answer.

**Comment by opa334** [comment]
nevertheless this is neither an issue nor the right place to ask such questions
