### ISSUE TITLE
Helium problem

### ISSUE THREAD

**Issue by notfence** [opa334/TrollStore#592]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

1

### Current Behavior?

When I open the Helium, the error "Not supported. This app must be installed with trollstore». The problem appeared after upgrading to 2.0.6 (from 2.0.3)
![A7240E71-CFC0-40E5-B228-6021718A47EB](https://github.com/opa334/TrollStore/assets/54737416/060b420a-4350-4745-8ee6-b4a685ac2c8e)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.6

### iOS/iPadOS version

iOS 15.6 RC

### iDevice Model

iPhone Xr

**Comment by alfiecg24** [comment]
Reproduced, will look into it.

**Comment by alfiecg24** [comment]
@notfence did you fix it?

**Comment by alfiecg24** [comment]
Nevermind, just seen the latest version fixed this issue.
