### ISSUE TITLE
Tips (patched by TrollStoreMDC and also tested with Misaka version) doesn't work

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [opa334/TrollStore#598]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Successfully signed and installed TrollStore

### Current Behavior?

It doesn't crashing - it gets successfully installed but when I try to install TrollStore from Tips.app, I got response: Error installing TrollStore: trollstorehelper returned 1

### Possible Solution?

- Check in the latest version is the binary signed and also the compatibility with iPhone 7 GSM on iOS 15.5 and also other A11 devices

### Steps to Reproduce

- Download latest TrollStoreMDC.ipa
- Sideload it using SideStore
- Open it and giving all RW access
- After job finished trying to open Tips
- Select Install TrollStore
- Error.
- Method 2:
- Download and install Misaka in the same way like TrollStoreMDC after complete removal and reinstallation of Tips and testing if it will work or not but unfortunatelly same results)
- Open Misaka file manager and following instructions to replace Tips.app binary with correct latest TrollStore persistence helper binary
- Opening Tips.app (crashes first time)
- Opening second time
- Clicking Install TrollStore
- Error.
- Rebooting device and etc... and still the same error

### TrollStore Version

2.0.7

### iOS/iPadOS version

15.5

### iDevice Model

iPhone 7 GSM

**Comment by admin-elvistrujanovic** [comment]
> Hey, do you have a mac/pc? if so you can download palera1n (mac) or you can search for palen1x (not sure if it exists)

I have linux and probably the problem could also be that one binary patching is not enough


Persistence helper required trollstorehelper binary that doesn't even exist in Tips.app after patching it via TrollStoreMDC.ipa/Misaka

**Comment by admin-elvistrujanovic** [comment]
And will restoring rootfs of palera1n remove also TrollStore??

**Comment by opa334** [comment]
The TrollHelper_Embedded binary under releases has the trollstorehelper file embedded inside it, you do not need to do anything more than replace the system app with it. If it doesn't work, you're doing something wrong.

**Comment by suitawesome** [comment]
@opa334 I have the same issue as the author. Currently trying on iPhone 7 iOS 15.5!

![IMG_1681](https://github.com/opa334/TrollStore/assets/152329962/f7de2629-0a1d-4d6f-a0a9-66944f96591c)

**Comment by admin-elvistrujanovic** [comment]
So @opa334 - it's clearly that we're not doing anything wrong. Checkm8 method works but mdc/kfd doesn't.

**Comment by suitawesome** [comment]
@admin-elvistrujanovic had you given sideloadly admin privileges? I don't remember if I had done that! Don’t think that matters though after the successful install. And were there any issues with sideloadly? Like any errors?

**Comment by admin-elvistrujanovic** [comment]
> @admin-elvistrujanovic so did you get it to install using the checkm8 method? Can you briefly walk me through it.
> 

It's simple. Jailbreak your device using palera1n/palera1x (rootless), go to latest release of TrollStore from github and download arm64 deb file. Open it via Sileo, install it and open it.


After that, select the option to install TrollStore


Your device will respring and that's normal, now open TrollStore, it's settings and add persistence helper to Tips


Now you can revert (remove) jailbreak and that TrollstoreHelper that you've installed from deb file will be only removed with of course Sileo and jailbreak.

That's it!

**Comment by suitawesome** [comment]
Thanks a lot @admin-elvistrujanovic. Now will wait for @opa334 on the above issue or else will follow the steps. Much appreciated 😄

**Comment by opa334** [comment]
> So @opa334 - it's clearly that we're not doing anything wrong. Checkm8 method works but mdc/kfd doesn't.

no that makes it even more clear that you're doing something wrong, lol

**Comment by suitawesome** [comment]
For reference I have used this guide: https://ios.cfw.guide/installing-trollhelper-mdc/

**Comment by suitawesome** [comment]
@opa334 Is this the right way? Are there any more steps?

**Comment by FuFris** [comment]
I also have the same problem on my iPhone 11 ios16.1.1.

**Comment by FuFris** [comment]
![微信图片_20231129135803](https://github.com/opa334/TrollStore/assets/106427585/628c5647-b924-48d4-a1d8-3ac3ac2645c8)

**Comment by admin-elvistrujanovic** [comment]
> For reference I have used this guide: https://ios.cfw.guide/installing-trollhelper-mdc/

Tried and doesn't work

**Comment by admin-elvistrujanovic** [comment]
It's still the same error - And when I try to use Misaka, even everything that requires mdc like tweaks and etc... crashes

I'm moving back to checkm8

**Comment by FuFris** [comment]
I updated TrollinstallerMDC v1.0.3 solved the problem.

**Comment by admin-elvistrujanovic** [comment]
> I updated TrollinstallerMDC v1.0.3 solved the problem.

So new version of TrollInstallerMDC (signed in jailbreaks.app) fixed the problem?
