### ISSUE TITLE
Discord (vendetta) installed using TrollStore get updated to latest Discord build on TestFlight

### ISSUE THREAD

**Issue by dora727** [opa334/TrollStore#599]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

apple or testflight can’t do anything to this

### Current Behavior?

title. this only happens with discord (vendetta)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.6

### iOS/iPadOS version

16.4

### iDevice Model

iPhone SE 2022

**Comment by alfiecg24** [comment]
This is probably a result of the TrollStore-installed app having the same bundle identifier as the original Discord.

**Comment by opa334** [comment]
if this actually is an issue, it's not fixable
