### ISSUE TITLE
Bug of install vpn or other configuration file

### ISSUE THREAD

**Issue by makejohn** [opa334/TrollStore#60]
When add normal vpn configuration file, after click allow, it doesn’t go to settings, it will open a app which is installed by TrollStore, if you delete this app, another app installed by TrollStore will be opend

**Comment by Sp0derDev** [comment]
I assume VPNs fall under the plug-ins issue and will be looked at soon.

**Comment by makejohn** [comment]
New findings, every action that lead to setting will cause this issue. Like, from notice page, when you swipe to the notice, and choose view settings, it will got to a random app that is installed by TrollStore, instead of settings app itself

**Comment by satanicang3l** [comment]
Hi I noticed the same thing as well. Can't add any VPN config for now.

**Comment by opa334** [comment]
this will be fixed shortly but you will have to reinstall the IPA that gets opened instead of the settings app

**Comment by opa334** [comment]
This was fixed a while ago, the IPA that gets opened instead of settings has to be reinstalled tho.
