### ISSUE TITLE
TollinstallerMDC failed to unsandbox

### ISSUE THREAD

**Issue by shx2129** [opa334/TrollStore#600]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Successfully signed and installed TrollStore

### Current Behavior?

when I open TollinstallerMDC, it shows as below
![Uploading IMG_5551.png…]()

![IMG_5550](https://github.com/opa334/TrollStore/assets/79363504/b88d8d84-ac79-4295-9503-3cd2e15b2710)

### Possible Solution?

-

### Steps to Reproduce

1. Download latest TrollStoreMDC.ipa
2. Sideload it using SideStore
3. Open it and giving all RW access
4. failed to unsandbox
5. reinstalling Tips and reboot 
6. still failed to unsandbox

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

IOS 16.1.2

### iDevice Model

Iphone 13

**Comment by Martin-dq** [comment]
same issue, how to fix?

**Comment by shx2129** [comment]
> same issue, how to fix?

only successfully installed TrollStore with Misaka of enterprise signature in version 3.4, installation failed with Misaka of Personal signature in version 3.4 and 3.5

**Comment by Martin-dq** [comment]
noted, thanks

**Comment by Martin-dq** [comment]
![image](https://github.com/opa334/TrollStore/assets/56908545/e0ad2d02-33f2-4d6a-9f46-d4750aff2702)

This solution can fix Tips error or 闪退

**Comment by shx2129** [comment]
> ![image](https://private-user-images.githubusercontent.com/56908545/286571147-e0ad2d02-33f2-4d6a-9f46-d4750aff2702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzQ0NzQsIm5iZiI6MTcwMTI3NDE3NCwicGF0aCI6Ii81NjkwODU0NS8yODY1NzExNDctZTBhZDJkMDItMzNmMi00ZDZhLTlmNDYtZDQ3NTBhZmYyNzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE2MDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZTFiMjY5NjQ1MTRiMWE3NzMzNjYyYTUyY2EyNmZlMmI4NDBlZGYxMzI5MjNiZmI1Nzk5YWRhZDZiMGVmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p6o46Wug9qoFdEpo-ut2eocwlFt_25eQ0z4DYbZpZDM)
> 
> This solution can fix Tips error or 闪退

thanks
