### ISSUE TITLE
all apps installed by TrollStore2 cannot launch

### ISSUE THREAD

**Issue by shx2129** [opa334/TrollStore#602]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

all apps installed by TrollStore2 can be used

### Current Behavior?

after installing app in TrollStore2, those app cannot launch

### Possible Solution?

-

### Steps to Reproduce

1. -install TrollStore 2.0.7 by misaka
2. install Persistence Helper
3. install ipa
4. fail to open these apps
5. reboot
6. still fail to open apps

### TrollStore Version

TrollStore 2.0.7

### iOS/iPadOS version

IOS 16.1.2

### iDevice Model

Iphone 13

**Comment by hjjhhgc** [comment]
I have the same problem, and my device is iPhone Xr 16.1

**Comment by opa334** [comment]
what apps?

**Comment by opa334** [comment]
if apps don't show up on springboard, try respringing after installation

**Comment by shx2129** [comment]
> The fix for this is to enable developer mode

developer mode has been opened

**Comment by shx2129** [comment]
> if apps don't show up on springboard, try respringing after installation

the apps can be found in springboard when I take the action of resping

**Comment by shx2129** [comment]
I have successfully installed and used it. Below is my experience for reference.  My version is IOS 16.1.2, device is iphone 13

- [ failed to install TrollStore with TrollInstallerMDC)] 
only successfully installed TrollStore with Misaka of enterprise signature in version 3.4, installation failed with Misaka of Personal signature in version 3.4 and 3.5

- [ apps cannot launch]
Ldid has not been installed.

- [Ldid installation failed]
https://x.com/phonephone731/status/1729482386327621892?s=46
only successfully with shadowrocket via American link

**Comment by opa334** [comment]
> > what apps?
> 
> ![0429FE1F-2EC8-43AE-BF90-F67CE9D8E8A6](https://private-user-images.githubusercontent.com/79363504/286453194-19a571d9-07e9-4417-88a9-90f4f8755d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzAzMzYsIm5iZiI6MTcwMTI3MDAzNiwicGF0aCI6Ii83OTM2MzUwNC8yODY0NTMxOTQtMTlhNTcxZDktMDdlOS00NDE3LTg4YTktOTBmNGY4NzU1ZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZmFhNWZiOGQ3NjUyZDlkNWVmY2E1MTUyODg2YTBhYWVlMDA4ZTEwZDE4M2UxNzY2MDY0ODZjZTQ5MmQ5ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RYgfjq1cYf8G_C8mYCR9WNEVhczSkoMX8hZjWO0fLe0) here is log of first app ![B80E1613-0E33-484D-A648-C4BB3EC365B8](https://private-user-images.githubusercontent.com/79363504/286453587-6740562f-7936-49b4-9a84-81b5911f9eb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzAzMzYsIm5iZiI6MTcwMTI3MDAzNiwicGF0aCI6Ii83OTM2MzUwNC8yODY0NTM1ODctNjc0MDU2MmYtNzkzNi00OWI0LTlhODQtODFiNTkxMWY5ZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZWNkNWM0NmJjODZlM2IzNjY0YzYwYjk1MGI4MmNiNWQ3NTIzNzg3YWM5NjI3NWMzZDRlYmM2ZDQ1YjRmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dnb-pMks9EQsMiHdskqhCLng0RulJvB9rH-gPuBXzO4)

Ensure you are on 2.0.7, then reinstall the app
