### ISSUE TITLE
TrollStore 2 Doesn’t installing on m1 iPad Pro 

### ISSUE THREAD

**Issue by Amurchic** [opa334/TrollStore#603]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

When I click on install, appears error trollstorehelper returned 1

### Current Behavior?

-

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore 2

### iOS/iPadOS version

IPadOS 16.1

### iDevice Model

iPad Pro 12.9 On M1

**Comment by Amurchic** [comment]
I reboot device, use misaka, trollinstallermdc, and reinstalled TrollInstallermdc, misaka, tips, books

**Comment by opa334** [comment]
has nothing to do with trollstore itself, the binary is confirmed to work

**Comment by admin-elvistrujanovic** [comment]
You're not the only one who have this problem. Use checkm8 instead since dev will probably not work on fixes about this.
