### ISSUE TITLE
Are there any fully open-source way to install trollstore 2?

### ISSUE THREAD

**Issue by STMRabbit** [opa334/TrollStore#607]
Hello, I'm reading the [instruction](https://ios.cfw.guide/installing-trollhelper-misaka/) and I noticed that there are two tools which are necessary for installing trollstore on arm64e 16.5 is close-sources: [Sideloadly](https://sideloadly.io/) and [Misaka](https://github.com/straight-tamago/misaka/releases/latest). 
I assume Sideloady can be replaced by [AltStore](https://github.com/altstoreio/AltStore), but are there any open-source tools that can replace [Misaka](https://github.com/straight-tamago/misaka/releases/latest)? 
I trust developers of these two tools for sure, but just for future availability and potential safety reason, I believe a fully open source methods is somehow necessary.  
Thank you very much and best regards!

**Comment by wangliniang** [comment]
I think so too.

**Comment by opa334** [comment]
No, there likely will not be an official tool either, anyone can make an open sourced tool using kfd however, so it's up for the community to make it happen
