### ISSUE TITLE
About 16.6.1 arm64e (A12 - A17 / M1 - M2)

### ISSUE THREAD

**Issue by AboSalemFTK** [opa334/TrollStore#609]
Is there any way to install trollstore in ios 16.6.1 on arm64e devices ??

**Comment by trial** [comment]
yes, a Chinese guy found a way. But first you need a device that is already installed trollstore. then update iOS to 16.6.1 or 17.0 thru Delay OTA.
https://github.com/invalidunit/chflags_trollhelper

**Comment by nakheel77** [comment]
> yes, a Chinese guy found a way. But first you need a device that is already installed trollstore. then update iOS to 16.6.1 or 17.0 thru Delay OTA. https://github.com/invalidunit/chflags_trollhelper

i have a device running 16.6.1 - a13. how to install trollstore 2 to my device ? thanks!
