### ISSUE TITLE
电脑无法获取应用信息

### ISSUE THREAD

**Issue by Aa970117a** [opa334/TrollStore#61]
在新版本中 连接电脑无法获取应用的信息  也不出现此应用的信息情况 。望改善

**Comment by Aa970117a** [comment]
![image](https://user-images.githubusercontent.com/93836713/188327907-1f810892-ea47-49f4-8295-d0c7659e67f6.png)

**Comment by Aa970117a** [comment]
安装的多开微信电脑端没有多开的信息

**Comment by Aa970117a** [comment]
![image](https://user-images.githubusercontent.com/93836713/188328023-ae8879ec-fc35-445a-b30d-93095bc75b97.png)

**Comment by opa334** [comment]
english please
