### ISSUE TITLE
TrollStore2 apps won’t appear in settings (even when if they are switched to user applications)

### ISSUE THREAD

**Issue by Hex34568** [opa334/TrollStore#615]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

pretty self-explanatory.

### Current Behavior?

https://github.com/opa334/TrollStore/assets/103202023/9396fbdc-02fe-4ea9-b535-c18ad6dbf57c

### Possible Solution?

-...-

### Steps to Reproduce

-install any application
-switch it to user apps
-won't show in the settings

### TrollStore Version

2.0.7

### iOS/iPadOS version

15.7 

### iDevice Model

iPad 6 Gen

### Other info of your environment

(checkm8)

**Comment by opa334** [comment]
This hasn't worked for some people on TrollStore 1 either, not sure why

**Comment by Hex34568** [comment]
> This hasn't worked for some people on TrollStore 1 either, not sure why

Uhh, so how am suppose to make it work? is there anything i could do? a workatound maybe? i really need that dark reader

**Comment by acquitelol** [comment]
Bump, I can't see any TS signed apps in settings either, I thought that was just a TS limitation but it's actually a bug?? Interesting.

**Comment by opa334** [comment]
> Bump, I can't see any TS signed apps in settings either, I thought that was just a TS limitation but it's actually a bug?? Interesting.

they should show after you switch them to user registration

**Comment by Sparktion** [comment]
Same issue. iPhone 14 on 16.2.

**Comment by Hex34568** [comment]
This issue has been closed since my peas-sized brain just realized Safari extensions won't appear in the Safari settings application because apps registered with system privileges can’t inject dynamic libraries also for the fact why it didn't appear in the user app section, was because it didn't have any entitlements for it show up @opa334 (forgib me)
