### ISSUE TITLE
some app has iCloud issue with TrollStore

### ISSUE THREAD

**Issue by TrollStoreTV** [opa334/TrollStore#619]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Surge-tvos can use iCloud sync.

### Current Behavior?

Surge-tvos has iCloud sync issue. 
logs below:
BUG IN KVS: Tried to access store that is unknown to the system (YCKFLA6N72.com.nssurge.inc.surge-ios). Please send this bug to NSUbiquitousKeyValueStore.
BUG IN CLIENT OF KVS: Tried to access unknown store YCKFLA6N72.com.nssurge.inc.surge-ios
Error synchronizing with cloud for store <(YCKFLA6N72.com.nssurge.inc.surge-ios)>: Error Domain=SyncedDefaults Code=101010 "Tried to access unknown store YCKFLA6N72.com.nssurge.inc.surge-ios" UserInfo={NSLocalizedDescription=Tried to access unknown store YCKFLA6N72.com.nssurge.inc.surge-ios}

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2.0.7

### iOS/iPadOS version

tvOS 17.0

### iDevice Model

ATV HD

**Comment by opa334** [comment]
tvOS?? TrollStore doesn't even support that

**Comment by TrollStoreTV** [comment]
Maybe iOS also have that bug, cause other stuff works great on tvOS.
If you have time, may take a look.
Thanks.
