### ISSUE TITLE
Iphone 6S   ios15.8安装不上巨魔2

### ISSUE THREAD

**Issue by Dancergh** [opa334/TrollStore#623]
Iphone 6S   ios15.8安装不上巨魔2，A9芯片
misaka，tips显示灰色，不能点击，文件管理器/var空白，没有路径，如何解决呢
TrollnstallerMDC，显示Your ios version is not supported by MacDirtyCow
PicassoDebug，芯片不支持

**Comment by NAVECCIER** [comment]
只能越狱装
