### ISSUE TITLE
Ipad（第六代）机型A1893，系统ios16.6，不能安装巨魔2

### ISSUE THREAD

**Issue by Dancergh** [opa334/TrollStore#624]
Ipad（第六代）机型A1893，系统ios16.6，不能安装巨魔2，
misaka，tips/book/home显示灰色，不能点击，/var路径空白，无路径
TrollnstallerMDC，显示Your ios version is not supported by MacDirtyCow
PicassoDebug，打不开，一直闪退，重启设备也是闪退

**Comment by LemonSoda-RPG** [comment]
> Ipad（第六代）机型A1893，系统ios16.6，不能安装巨魔2， misaka，tips/book/home显示灰色，不能点击，/var路径空白，无路径 TrollnstallerMDC，显示Your ios version is not supported by MacDirtyCow PicassoDebug，打不开，一直闪退，重启设备也是闪退

你最好用英文

**Comment by Dancergh** [comment]
搞忘了，我这看到的是中文

**Comment by NAVECCIER** [comment]
哥们，16.6没漏洞直接装不了，A12以下可以越狱再装

**Comment by 923508946** [comment]
> 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装

![image](https://github.com/opa334/TrollStore/assets/75707148/b71f46cc-bc45-4546-a27d-7d963ce7e550)

16.6装不了？这文档上的范围不是包括16.6吗
https://ios.cfw.guide/installing-trollstore-trollstar/

**Comment by NAVECCIER** [comment]
> commented

我这是去年回复的 当时16.5.1+不越狱装不了

**Comment by NAVECCIER** [comment]
> > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> 
> ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> 
> 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/

我这是去年回复的 当时16.5.1+不越狱装不了

**Comment by 923508946** [comment]
> > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> 
> 我这是去年回复的 当时16.5.1+不越狱装不了

现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性

**Comment by NAVECCIER** [comment]
> > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > 
> > 
> > 我这是去年回复的 当时16.5.1+不越狱装不了
> 
> 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性

可以装呀 你下的ipa对吗

**Comment by 923508946** [comment]
> > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > 
> > > 
> > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > 
> > 
> > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> 
> 可以装呀 你下的ipa对吗

就是从下边这个文档上下的1.2版本
https://github.com/34306/TrollStar/releases/tag/1.2

**Comment by 923508946** [comment]
> > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > 
> > > > > > 
> > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > 
> > > > > 
> > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > 
> > > > 
> > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > 
> > > 
> > > 可以装呀 你下的ipa对吗
> > 
> > 
> > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> 
> 你用啥签的

Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用

**Comment by NAVECCIER** [comment]
> > > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > > 
> > > > > > 
> > > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > > 
> > > > > 
> > > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > > 
> > > > 
> > > > 可以装呀 你下的ipa对吗
> > > 
> > > 
> > > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> > 
> > 
> > 你用啥签的
> 
> Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用

爱思工具里有个ipa签名，先要用你的id把这个ipa签名，然后安装这个签名后的包，直接装未签名的包是装不上去

**Comment by 923508946** [comment]
> > > > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > > > 
> > > > > > > 
> > > > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > > > 
> > > > > > 
> > > > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > > > 
> > > > > 
> > > > > 可以装呀 你下的ipa对吗
> > > > 
> > > > 
> > > > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> > > 
> > > 
> > > 你用啥签的
> > 
> > 
> > Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用
> 
> 爱思工具里有个ipa签名，先要用你的id把这个ipa签名，然后安装这个签名后的包，直接装未签名的包是装不上去

爱思签名完了

**Comment by NAVECCIER** [comment]
> > > > > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > > > > 
> > > > > > > 
> > > > > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > > > > 
> > > > > > 
> > > > > > 可以装呀 你下的ipa对吗
> > > > > 
> > > > > 
> > > > > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> > > > 
> > > > 
> > > > 你用啥签的
> > > 
> > > 
> > > Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用
> > 
> > 
> > 爱思工具里有个ipa签名，先要用你的id把这个ipa签名，然后安装这个签名后的包，直接装未签名的包是装不上去
> 
> 爱思签名完了

sideloadly报错什么

**Comment by 923508946** [comment]
> > > > > > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > > > > > 
> > > > > > > 
> > > > > > > 可以装呀 你下的ipa对吗
> > > > > > 
> > > > > > 
> > > > > > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> > > > > 
> > > > > 
> > > > > 你用啥签的
> > > > 
> > > > 
> > > > Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用
> > > 
> > > 
> > > 爱思工具里有个ipa签名，先要用你的id把这个ipa签名，然后安装这个签名后的包，直接装未签名的包是装不上去
> > 
> > 
> > 爱思签名完了
> 
> sideloadly报错什么

装好了大哥，都搞定了！

**Comment by xinhua16** [comment]
> > > > > > > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可以装呀 你下的ipa对吗
> > > > > > > 
> > > > > > > 
> > > > > > > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> > > > > > 
> > > > > > 
> > > > > > 你用啥签的
> > > > > 
> > > > > 
> > > > > Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用
> > > > 
> > > > 
> > > > 爱思工具里有个ipa签名，先要用你的id把这个ipa签名，然后安装这个签名后的包，直接装未签名的包是装不上去
> > > 
> > > 
> > > 爱思签名完了
> > 
> > 
> > sideloadly报错什么
> 
> 装好了大哥，都搞定了！

兄弟，你是怎么装好的请说一下。
我的问题和你一样，就是装不上

**Comment by 923508946** [comment]
> > > > > > > > > > > > > 哥们，16.6没漏洞直接装不了，A12以下可以越狱再装
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > ![image](https://private-user-images.githubusercontent.com/75707148/313966066-b71f46cc-bc45-4546-a27d-7d963ce7e550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2NTQsIm5iZiI6MTcxMDgzNzM1NCwicGF0aCI6Ii83NTcwNzE0OC8zMTM5NjYwNjYtYjcxZjQ2Y2MtYmM0NS00NTQ2LWEyN2QtN2Q5NjNjZTdlNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmJmM2YyMWRmOGU2Yjk3ZmQ2ZGM4MDJmNzc4NDM4MDZlMDExYTUyMjNmYjI3MDZlMTA2MDI1NDBhYTNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i3V1Bbrq6to6dJgBMJnnmWYmPrrGR6BZFQpNHb4Ga0)
> > > > > > > > > > > > 16.6装不了？这文档上的范围不是包括16.6吗 https://ios.cfw.guide/installing-trollstore-trollstar/
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 我这是去年回复的 当时16.5.1+不越狱装不了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 现在能行吗，我刚才试了试，签名完安装还是显示无法验证完整性
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 可以装呀 你下的ipa对吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 就是从上边的文档打开的这个tag 下的1.2版本 https://github.com/34306/TrollStar/releases/tag/1.2
> > > > > > > 
> > > > > > > 
> > > > > > > 你用啥签的
> > > > > > 
> > > > > > 
> > > > > > Sideloadly和爱思助手都试了都不行。Sideloadly签不上报错说环境有缺陷。爱思能签上但是安装不上，app显示越狱应用
> > > > > 
> > > > > 
> > > > > 爱思工具里有个ipa签名，先要用你的id把这个ipa签名，然后安装这个签名后的包，直接装未签名的包是装不上去
> > > > 
> > > > 
> > > > 爱思签名完了
> > > 
> > > 
> > > sideloadly报错什么
> > 
> > 
> > 装好了大哥，都搞定了！
> 
> 兄弟，你是怎么装好的请说一下。 我的问题和你一样，就是装不上

我犯了个低级错误，应该在爱思助手的下载中心里安装被签名的ipa，而不是安装没有被签名的原始ipa。签名完成后爱思助手会把ipa放到它自己的下载中心里！
![image](https://github.com/opa334/TrollStore/assets/75707148/65aef6ba-c2b4-4e73-b397-691f24b12342)

**Comment by xinhua16** [comment]
我用爱思签名没什么问题，安装也没什么问题。就是装不上TrollStore，只会重启。你是用TrollStar，misaka，Purekfd中哪个签名的？

**Comment by 923508946** [comment]
> 我用爱思签名没什么问题，安装也没什么问题。就是装不上TrollStore，只会重启。你是用TrollStar，misaka，Purekfd中哪个签名的？

<img width="118" alt="8dac27291151247424b783fd0fbd62e" src="https://github.com/opa334/TrollStore/assets/75707148/d6185391-0c12-4002-8663-19748b7e0028">
是不是你选择的这个有问题？
