### ISSUE TITLE
Error occurs when installing TrollStore with Tips APP

### ISSUE THREAD

**Issue by PoetryU** [opa334/TrollStore#625]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I follow the guides at [ios.cfw.guide](https://ios.cfw.guide/installing-trollstore),Installing TrollStore (by Misaka):
[installing-trollstore](https://ios.cfw.guide/installing-trollhelper-misaka/#installing-trollstore)
1. Open the Tips app
2. Tap Install TrollStore
3. Tap Install TrollStore

Your device should respring, and TrollStore should now be installed.

### Current Behavior?

![image](https://github.com/opa334/TrollStore/assets/68501042/5e3e87eb-04ee-436b-a527-7484f1978aa1)
**Error**
Error installing TrollStore: trollstorehelper returned 1

### Possible Solution?

-

### Steps to Reproduce

I follow the guides at [ios.cfw.guide](https://ios.cfw.guide/installing-trollstore),Installing TrollStore (by Misaka):
[installing-trollstore](https://ios.cfw.guide/installing-trollhelper-misaka/#installing-trollstore)
1. Open the Tips app
2. Tap Install TrollStore

then Error occured

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

iOS 16.4.1

### iDevice Model

iPhone 14

**Comment by LemonSoda-RPG** [comment]
http://b23.tv/64qyXgk     
 I used the methods in the video and hope they can help you

**Comment by PoetryU** [comment]
File OverWrite succeeded. thx
