### ISSUE TITLE
Nicegram crashed after share ipa file to TrollStore

### ISSUE THREAD

**Issue by leftshine** [opa334/TrollStore#627]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Nicegram work fine after share ipa file to TrollStore

### Current Behavior?

I shared a ipa file to TrollStore from Nicegram and install it.
Then I back to Nicegram,  it crashed when I close the share menu.

### Possible Solution?

-

### Steps to Reproduce

-download a ipa file in Nicegram;
-share the ipa file to TrollStore and install it;
-back to Nicegram
-close the share menu

https://github.com/opa334/TrollStore/assets/17633965/16883035-cda0-417c-92b2-eef0ba99d121
![da8eec5c0d06f210419f3bf3770f3d5](https://github.com/opa334/TrollStore/assets/17633965/1660e45d-3e89-411b-8383-e1d6c9c3d221)

### TrollStore Version

TrollStore 2.0.8

### iOS/iPadOS version

 iOS 16.1

### iDevice Model

 iPhone 12 mini

### Other info of your environment

Nicegram 1.4.7

**Comment by leftshine** [comment]
> How is this a trollstore issue ? 😭

Because it is ok to share to other application. Only crash when sharing to Trollstore.

**Comment by sowavy234** [comment]
How in the fuck you got my email Burberry.On Nov 30, 2023, at 5:37 PM, leftshine ***@***.***> wrote:﻿

How is this a trollstore issue ? 😭

Because it is ok to share to other application. Only crash when sharing to Trollstore.
