### ISSUE TITLE
Is it currently impossible to use VPN apps in Trollstore 2? I will just crash or be unable to click the button to connect to the shadowrocket

### ISSUE THREAD

**Issue by chris7395328** [opa334/TrollStore#629]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Installing adguard or shadowrockt will crash directly. If you install a cracked version, you can open it but cannot open the vpn button.

### Current Behavior?

Crash or unavailable

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

ios 15.6.1

### iDevice Model

ipad pro 2018

**Comment by Hex34568** [comment]
> ### No Duplicates Issue
> 
> - [X] I'm sure I've searched on the issue tracker before creating one.
> 
> ### Expected Behavior?
> 
> Installing adguard or shadowrockt will crash directly. If you install a cracked version, you can open it but cannot open the vpn button.
> 
> ### Current Behavior?
> 
> Crash or unavailable
> 
> ### Possible Solution?
> 
> -
> 
> ### Steps to Reproduce
> 
> -
> 
> ### TrollStore Version
> 
> TrollInstaller2
> 
> ### iOS/iPadOS version
> 
> ios 15.6.1
> 
> ### iDevice Model
> 
> ipad pro 2018
> 
> ### Other info of your environment
> 
> _No response_

I have tried using several VPNs with ts 2 (works fine for me) assuming they get entitlements for for creating the VPN profile it should work

**Comment by Hex34568** [comment]
> ### No Duplicates Issue
> 
> - [X] I'm sure I've searched on the issue tracker before creating one.
> 
> ### Expected Behavior?
> 
> Installing adguard or shadowrockt will crash directly. If you install a cracked version, you can open it but cannot open the vpn button.
> 
> ### Current Behavior?
> 
> Crash or unavailable
> 
> ### Possible Solution?
> 
> -
> 
> ### Steps to Reproduce
> 
> -
> 
> ### TrollStore Version
> 
> TrollInstaller2
> 
> ### iOS/iPadOS version
> 
> ios 15.6.1
> 
> ### iDevice Model
> 
> ipad pro 2018
> 
> ### Other info of your environment
> 
> _No response_

it's probably an issue with the crack version ur using

**Comment by chris7395328** [comment]
> > ### No Duplicates Issue
> > 
> > * [x]  I'm sure I've searched on the issue tracker before creating one.
> > 
> > ### Expected Behavior?
> > Installing adguard or shadowrockt will crash directly. If you install a cracked version, you can open it but cannot open the vpn button.
> > ### Current Behavior?
> > Crash or unavailable
> > ### Possible Solution?
> > 
> > 
> > 
> > ### Steps to Reproduce
> > 
> > 
> > 
> > ### TrollStore Version
> > TrollInstaller2
> > ### iOS/iPadOS version
> > ios 15.6.1
> > ### iDevice Model
> > ipad pro 2018
> > ### Other info of your environment
> > _No response_
> 
> it's probably an issue with the crack version ur using


Yes, I also found that it is indeed the reason for insufficient cracking permissions, not the IPA dedicated to trolls.
