### ISSUE TITLE
Updating to v2.0.8 breaks “Apps Manager 1.8.0 (1.8 build 1)” 

### ISSUE THREAD

**Issue by Spykington** [opa334/TrollStore#632]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

![5A366EF8-D420-41EF-BF7A-697027223CD2](https://github.com/opa334/TrollStore/assets/18373584/9f39e44c-a4bf-4716-91d5-95e39cfb472d)

Updating to v2.0.8 breaks “Apps Manager 1.8.0 (1.8 build 1)” 

### Current Behavior?

After updating, backups cannot be completed in  “Apps Manager 1.8.0 (1.8 build 1)” as it states that ldid is missing
Have deleted and reinstalled Trollstore and Apps Manager, same result. 
device is: iPhone 11 Pro Max on iOS  15.2.1
Have also duplicated this on a secondary iPhone 11 Pro Max on iOS 16.0

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.8

### iOS/iPadOS version

on iOS  15.2.1

### iDevice Model

iPhone 11 Pro Max

**Comment by bradycodemaster** [comment]
idid not supprted

**Comment by opa334** [comment]
That's an Apps Manager problem, I do not think it's related to TrollStore
