### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by R3n3r0** [opa334/TrollStore#638]
when compiling I get this error
`unzip:  cannot find or open ./Victim/InstallerVictim.ipa, ./Victim/InstallerVictim.ipa.zip or ./Victim/InstallerVictim.ipa.ZIP.`
 it is related to the lack of the ipa victim file, but it is not documented anywhere that ipa should be.

**Comment by Elziy** [comment]
@R3n3r0 Hello, I want to know how to edit the source code and compile it, I have xcode

**Comment by R3n3r0** [comment]
that is, what should be changed ?

**Comment by Elziy** [comment]
I'm not an Apple developer and I don't know how these source codes should be edited and compiled, so I wanted to ask if you know.

**Comment by alfiecg24** [comment]
The IPA needs to be an **encrypted** App Store IPA, which you can download with `ipatool`, for example. It is used to generate the IPAs that allow you to install via the installd bypass (< iOS 15.7). The rest of the artefacts will still build in the `_build` directory if the victim IPA does not exist.

**Comment by BoringApp** [comment]
What happens if my iOS Version higher than iOS 15.7 ? Does iOS 15.7 doesn't need victim.ipa ?

**Comment by alfiecg24** [comment]
Use TrollInstallerX instead.
