### ISSUE TITLE
does installing TrollStore on iPadOS 17.0 with Palera1n make it work on stock iOS ?

### ISSUE THREAD

**Issue by Mas-Deabes** [opa334/TrollStore#642]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Apps function and launch as normal and launch normally

### Current Behavior?

Now I'm asking this because I wanted to experiment and try it installing Trollstore on my 6th Gen iPad with Palera1n and it turns out it works even after the jailbreak is removed and after a restart and I'm able to install apps as normal. 

but 95% of the apps I'm installing end up crashing after a millisecond of loading.

I tried opening the Helper (tips app) to delete TrollsStore and reinstall it again but I still got the same results. if anyone has been able to solve it please get in touch

Thanks in advance

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.8

### iOS/iPadOS version

17.0

### iDevice Model

iPad 6th Gen

**Comment by opa334** [comment]
yes
