### ISSUE TITLE
[bug] lost configs after reboot

### ISSUE THREAD

**Issue by augustobob** [opa334/TrollStore#643]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Configurations to persist through reboots

### Current Behavior?

The configs like notifications asks to allow after every reboot and app folder changes in filza

### Possible Solution?

-

### Steps to Reproduce

- reboot and open an app installed through trollstore

### TrollStore Version

2.0.8

### iOS/iPadOS version

16.5

### iDevice Model

iPhone 12 Pro Max

### Other info of your environment

iOS 16.5

**Comment by opa334** [comment]
not fixable, this is just how TrollStore works
