### ISSUE TITLE
How to sign binary executable for TrollStore2?

### ISSUE THREAD

**Issue by rllbe** [opa334/TrollStore#646]
### No Duplicates Issue

- [x] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

[https://www.reddit.com/r/Trollstore/comments/xqxjnt/comment/iqcivza/](https://www.reddit.com/r/Trollstore/comments/xqxjnt/comment/iqcivza/)
I use these commands to sign my binary executables for TrollStore1 before and they were working fine in Filza fishshell, and I thought they should on TrollStore 2

### Current Behavior?

The binaries stopped working after I update to iOS 17.0 and TrollStore2. It simply gives "unknown error number 85" in Filza fishshell. What should I do to? Should I resign them with the new CT bug? How do I do it if I should?

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore 2.0.8

### iOS/iPadOS version

17.0

### iDevice Model

iPad Pro 12.9" 5th-gen

**Comment by virkingz** [comment]
How to install TrollStore2 with ios17.0

**Comment by opa334** [comment]
Yes, you need to sign them with the new bug.

**Comment by bt** [comment]
> But how do I do it? I tried resigning them with the ldid in the TrollStore app and the legacy.p12 file, but they still didn’t work

Did you manage to work this out? I'm also having the same issue.
