### ISSUE TITLE
u0, iOS 14.5.1 - From JB to stock; app launches but loses its icon image.

### ISSUE THREAD

**Issue by MarsWonderBoy** [opa334/TrollStore#65]
I'm u0 on iPhone 12 Pro running iOS 14.5.1 and I've tested TrollStore. I've noticed that whatever app I install through TrollStore retains its app icon image only while in jailbroken status. If I were to reboot back to stock, the icon loses its image. However, the icon image returns when I enter jb again. Second image shows what the icon should look like.

![IMG_1193](https://user-images.githubusercontent.com/64989845/188336746-e0fc18e0-e7ba-4d30-a7c5-4765c636aa87.jpg)
![0E7E3A51-2104-466B-92D1-B42303CA0719](https://user-images.githubusercontent.com/64989845/188338105-92232135-a399-4ac6-a369-62172128c52a.jpg)

**Comment by opa334** [comment]
I feel like this is an issue that should have been fixed before 1.0 released, but if it's not then I likely can't do anything about it.

**Comment by OverWatch-R** [comment]
You can do it through Filza escaped or Filza if you're jailbroken by going to var>container>bundle>application then find the app you want and add image

**Comment by MarsWonderBoy** [comment]
I think I discovered the workaround. I wasn't extensive, but I think I need to be installing the apps through stock first then the app retains its image both in stock and jb'd.

**Comment by invalidunit** [comment]
I think this problem is caused by the desktop icon cache after activating the jailbreak environment and the desktop icon cache saved when the jailbreak environment is not activated not being on the same path.

**Comment by opa334** [comment]
Can't reproduce, also might be fixed already?
