### ISSUE TITLE
“Error installing trollstore”. iOS 16.6.1. Signed using developer certificate. 

### ISSUE THREAD

**Issue by Kostya2583** [opa334/TrollStore#653]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I used developer certificate to sign version 2.0.8. App successfully installed. 

### Current Behavior?

When I pressed “Install trollstore” I got error: “Error installing trollstore. Trollstorehelper returned 1”. I tried and got this error on iPhone 12 iOS 16.0, iPhone 12 Pro Max iOS 16.6.1 and iPhone X iOS 16.6.1. 
I signed .ipa using zsign and extracted .ipa from arm64 .deb file version 2.0.8. 
Is it any problem with signing method?

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.8

### iOS/iPadOS version

iOS 16.6.1

### iDevice Model

iphone 12 pro max, iphone x

**Comment by taomi** [comment]
CPU >=A12
IOS 16.5.1~16.6.1,17.0
currently no installation method available

**Comment by opa334** [comment]
Why does everyone think they're a genius for coming up with signing it with a dev account?

There is no installation method! Signing with dev account won't make the installer magically work, it needs entitlements.
