### ISSUE TITLE
[Error]I can't use app,but apps like filza could be use

### ISSUE THREAD

**Issue by kenny000001** [opa334/TrollStore#654]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

A lot apps can not use trollstore ,because it will makes app can't open ;if you use trollstore to open the app ,trollstore will show:failed to open X.X.X,but apps like filza could open....

### Current Behavior?

if you use trollstore to open the app ,trollstore will show:failed to open X.X.X,but apps like filza could open with use trollstore....

### Possible Solution?

-I don't know.......

### Steps to Reproduce

I use the tip to do I persistence helper
   [https://ios.cfw.guide/installing-trollhelper/]
   I was use iOS 15.2,I update to 16.6.1 in this 
   week use OTA,and before that,I use filza to 
   lock the folder "tip.app" ,it can let update 
   couldn't change the folder;when update 
   complete , I click the refresh when setup  
   finish;refresh done,but only some apps could 
   open like filza and CAperfHUD

### TrollStore Version

trollstore ver2.8

### iOS/iPadOS version

iOS16.6.1

### iDevice Model

iPhone X

### Other info of your environment

palera1n-rootless

**Comment by opa334** [comment]
that's what the persistence helper is for...
