### ISSUE TITLE
Un-jailbreaking iphone after installing Idid and respring

### ISSUE THREAD

**Issue by doniedogawa** [opa334/TrollStore#659]
I just watched GSM fix video on youtube ([here](https://www.youtube.com/watch?v=rJL4BmYWK0g)). After installing Idid and respring, they skip install Persistence Helper, then Un-jailbreaking the iphone.

Is is actually safe? I don't try it yet, still confused.

**Comment by opa334** [comment]
No, most people unfortunately don't get what the persistence helper is for. So yes, it is missing this step.
