### ISSUE TITLE
Apps installed with trollstore crash on open

### ISSUE THREAD

**Issue by ub96** [opa334/TrollStore#661]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

The app should launch like normal

### Current Behavior?

When I launch an app that’s installed from trollstore, it crashes and the only apps I got working were scarlet (trollstore edition) and misaka. Any fix

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2

### iOS/iPadOS version

16.2

### iDevice Model

iPhone 11

**Comment by opa334** [comment]
Enable dev mode

**Comment by ub96** [comment]
It doesn’t show up
