### ISSUE TITLE
If using Updating (Blobless) (Advanced) to upgrade to 17.0.0, can the installed trollstore2 be retained

### ISSUE THREAD

**Issue by kero990** [opa334/TrollStore#663]
I couldn't find your contact information. Sorry, we can only initiate issues

My device is an iPad mini 6-A15- arm64e, and the current version is still at 15.0.0. Seeing that Trollstore2 currently supports up to 17.0.0, I would like to inquire about upgrading the system version.

My device has now been updated to trollstore2. If I upgrade to 17.0.0, can I keep the trollstore? Because I see that the current installation method for arm64e-17.0.0 is "No Installation Method", if it cannot be retained, then I cannot upgrade to 17.0.0 and reinstall trollstore

Additionally, according to the Upgrading (Blobless) (Advanced) upgrade method, 17.0.0 is about to expire on the 20th, which means I must make a decision before that whether or not to upgrade my device to 17.0.0. So if I upgrade to 17.0.0, will there be a way to install trollstore2 in the future?

**Comment by opa334** [comment]
this is not a support channel

**Comment by An-Unnamed-Developer** [comment]
Yes, if you update you should be able to retain TrollStore, but PLEASE look up a guide.
