### ISSUE TITLE
AppStore++ falsely labelled as “sandboxed”

### ISSUE THREAD

**Issue by gamer191** [opa334/TrollStore#669]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

[AppStore++](https://github.com/CokePokes/AppStorePlus-TrollStore) shouldn’t be labelled as sandboxed, since it obviously isn’t sandboxed (and can’t be installed outside of trollstore)

### Current Behavior?

AppStore++ is labelled as sandboxed
![Metadata
Bundle Identifier:
com.cokepokes.AppStorePlus
Version: 1.0.3
Size: 18.6 MB
Sandboxing 
The app runs sandboxed and can only
access the containers listed below.
Capabilities
The app can not spawn other binaries. Accessible Containers
com.cokepokes.AppStorePlus](https://github.com/opa334/TrollStore/assets/83270075/cb87658c-c842-496e-ba81-63773887446a)

### Possible Solution?

If it’s not possible to verify whether an application is sandboxed, trollstore should be updated to mention that

### Steps to Reproduce

- Download https://github.com/CokePokes/AppStorePlus-TrollStore/releases/download/v1.2-1/AppStore++_TrollStore_v1.0.3-2.ipa
- “Open in” Trollstore

### TrollStore Version

TrollStore 2.0.8

### iOS/iPadOS version

16.1.1

### iDevice Model

iPhone Xs Max

**Comment by opa334** [comment]
It says sandboxed... because it is sandboxed.

Yes it has additional entitlements to perform those app downgrades, but that doesn't have anything to do with sandboxing.
