### ISSUE TITLE
ldid installing url error?

### ISSUE THREAD

**Issue by gdf159159** [opa334/TrollStore#676]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

install ldid   no response
ldid installing url error?
shadowrocket invalid

MitM ldid installing url
https://github.com/repos/opa334/ldid/releases/latest    404

url  404  cause?

### Current Behavior?

install ldid   no response

ldid installing url error?
shadowrocket invalid

MitM ldid installing url
https://github.com/repos/opa334/ldid/releases/latest    404

url  404  cause?

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore  2.0.8

### iOS/iPadOS version

14.8

### iDevice Model

iPhone 11

**Comment by opa334** [comment]
The API URL is https://api.github.com/repos/opa334/ldid/releases/latest, not https://github.com/repos/opa334/ldid/releases/latest
