### ISSUE TITLE
TrollHelper not working

### ISSUE THREAD

**Issue by Searchstars** [opa334/TrollStore#678]
I jailbroken iPhone X using palera1n and installed TrollHelper through Sileo. After opening it, I clicked "Install TrollStore" and the error message in the picture appeared.

![image](https://github.com/opa334/TrollStore/assets/47274115/be1d88f8-1daf-498a-b0c7-b8c6d138c0f2)

This seems to be some network issue, but I've made sure my network connection is working. Another possibility is that iOS is preventing TrollHelper from connecting to the Internet, because even when I first launched TrollHelper, it didn't ask me for network connection permissions, which you know, normal apps ask you for when you first open them. How it connects to the Internet, such as allowing it to use WiFi only or allowing it to use both cellular and WiFi at the same time.

Has anyone encountered the same problem? Or are there any possible solutions available to me?

**Comment by TheOneWhoIsCool** [comment]
Try using something else to sideload trollstore instead of using palera1n.

**Comment by opa334** [comment]
It seems I forgot to push TrollHelper 2.0.8 to Havoc, use the deb in the 2.0.9 release for now, it should be fixed there.

**Comment by TheOneWhoIsCool** [comment]
Dang I tried.
