### ISSUE TITLE
15.7.2 Is there any other way to install TrollStore2?

### ISSUE THREAD

**Issue by hrgfdz** [opa334/TrollStore#681]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Misaka has never been able to install TrollStore2 successfully, is there any other way to install it?

### Current Behavior?

Follow the Misaka installation method, and the "Tips" are always grayed out!

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollStore 2

### iOS/iPadOS version

ios 15.7.2

### iDevice Model

iPhone 13 pro max

**Comment by opa334** [comment]
no
