### ISSUE TITLE
Is there a way to enable developer mode through trollstore without a computer? I cant install any .tipa and I suspect its because of that.

### ISSUE THREAD

**Issue by Darthveder69420** [opa334/TrollStore#683]

**Comment by TheOneWhoIsCool** [comment]
i need this too

**Comment by opa334** [comment]
This is already implemented in upstream but I haven't bothered to push it yet

**Comment by TheOneWhoIsCool** [comment]
> This is already implemented in upstream but I haven't bothered to push it yet

When will trollstore be updated? I’m concerned I’m waiting 6 months for an update.

**Comment by TheOneWhoIsCool** [comment]
Adding it now would help me a lot! Please and thank you.

**Comment by opa334** [comment]
Pushed as 2.0.9
