### ISSUE TITLE
Cannot access website `api.jailbreaks.app` when trying to install TrollHelperOTA

### ISSUE THREAD

**Issue by Gilvern** [opa334/TrollStore#684]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

After navigating to the address `https://api.jailbreaks.app/troll64e` in Safari, I would have expected to be able to press install to install TrollHelperOTA.

### Current Behavior?

In Safari, I get the message 
> Safari cannot open the page because it could not establish a secure connection to the server.
As a result, I cannot proceed with the installation procedure recommended for my particular phone.

### Steps to Reproduce

-

### TrollStore Version

n/a

### iOS/iPadOS version

iOS 15.4.1

### iDevice Model

iPhone 13 Pro Max

**Comment by TheOneWhoIsCool** [comment]
blud that’s an issue wit your wifi provider not trollstore ‼️‼️ use a vpn dumbass

**Comment by Gilvern** [comment]
[@TheOneWhoIsCool](https://github.com/TheOneWhoIsCool) Thanks for your help! That resolved it. (Never had that issue with my ISP before, so taken by surprise.)
