### ISSUE TITLE
When will trollstore get pushed?

### ISSUE THREAD

**Issue by TheOneWhoIsCool** [opa334/TrollStore#686]
Since there’s a developer mode commit, I’ve been needing this for a long time. It’s annoying to have apps crashing for me. It’ll help a lot, and I just want to know _when you’ll push_.

**Comment by TheOneWhoIsCool** [comment]
I know I already asked this in the other issue comment.

**Comment by Darthveder69420** [comment]
When its ready. Most likely before dopamine 2.0 which is atleast 2-3 months away. Try to have patience. We waited for 2 years. We can just a few more months. Dont ask devs when eta as it can annoy them and many left because of the constant barrage of it.

**Comment by TheOneWhoIsCool** [comment]
> When its ready. Most likely before dopamine 2.0 which is atleast 2-3 months away. Try to have patience. We waited for 2 years. We can just a few more months. Dont ask devs when eta as it can annoy them and many left because of the constant barrage of it.

Opa could’ve updated it at any time, it wasn’t in development at all. I know it might annoy him, but I really needed it now.

**Comment by Darthveder69420** [comment]
Well you’re lucky cus it just got pushed right now.
