### ISSUE TITLE
Thire app doesn't show in the Setting page

### ISSUE THREAD

**Issue by Darvyn** [opa334/TrollStore#707]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Open Setting app, and scroll down to the bottom, all the installed third apps show up.

### Current Behavior?

Nothing shows as below,
![image](https://github.com/opa334/TrollStore/assets/26133254/b0433478-90d4-4f60-a7b5-c9cd6281b4b2)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstallerV2.0.11

### iOS/iPadOS version

ios16.5

### iDevice Model

iphone13 pro max

**Comment by opa334** [comment]
Apps registered as system generally do not show up in settings, you can switch them to a user registration and they should show up, but they will only launch in system state.
