### ISSUE TITLE
[Feature Request] Seashell malware detection

### ISSUE THREAD

**Issue by jamesy0ung** [opa334/TrollStore#712]
Hi opa334, would it be possible to add functionality for detecting Seashell into TrollStore?

It's not too hard to do manually, so I imagine it wouldn't be too hard to script in the process documented here: https://theapplewiki.com/wiki/SeaShell#Protecting_against_this_attack

This would generally make life easier for users and keep script kiddies at bay.

**Comment by opa334** [comment]
There is no way to effectively protect against this malware.
