### ISSUE TITLE
'Troll Misaka 2.0 TrollMisaka 2.0' is not a valid name for an app id. Please choose a name only containing alphanumeric characters and spaces

### ISSUE THREAD

**Issue by win-xp-user** [opa334/TrollStore#719]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

the ipa file to be written

### Current Behavior?

error 'Troll Misaka 2.0 TrollMisaka 2.0' is not a valid name for an app id. Please choose a name only containing alphanumeric characters and spaces. (9416)

### Possible Solution?

Modify app name removing the dot in "2.0"

### Steps to Reproduce

Use AltStore to write the ipa file.

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

iOS 15.7.9

### iDevice Model

iPhone SE

### Other info of your environment

Windows 10 virus protection off

**Comment by w316525096** [comment]
![image](https://github.com/opa334/TrollStore/assets/25398881/32526bf4-9a59-4bf4-aeca-469c465aaccb)
via: https://github.com/altstoreio/AltStore/issues/310
