### ISSUE TITLE
The data storage area of ​​apps

### ISSUE THREAD

**Issue by heinekenpsx** [opa334/TrollStore#72]
Applications that are installed using TrollStore have their data stored in /var/mobile/Documents or /var/mobile/Library instead of in their own directory the way regular app installations do. I ask this because they are installed to the user partition, not the system partition.
Can this problem be fixed?

**Comment by opa334** [comment]
I doubt it. This may have been an issue in TrollStore 1.0.0 but I'm not 100% sure, try reinstalling the apps with TrollStore 1.0.6.

**Comment by heinekenpsx** [comment]
Yeah, v1.0.6 working fine
