### ISSUE TITLE
After rebuilding the icon cache, all user applications in the storage are moved to the system data

### ISSUE THREAD

**Issue by rote66** [opa334/TrollStore#720]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

App store installed apps should be in iPhone storage and have notification push permissions

### Current Behavior?

Apps installed in the app store have all been moved to the system data and have no notification push permissions, and you can't see them in the notification options in the settings.
Tried refreshing the icon cache again and refreshing the app registration both didn't fix it.
![20240205102709](https://github.com/opa334/TrollStore/assets/26439391/abb11cd4-a847-4508-8448-20b0e018fb57)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

iOS 15.5

### iDevice Model

iPhone SE3

**Comment by opa334** [comment]
Did you... enable all those applications in Bootstrap?

**Comment by rote66** [comment]
> Did you... enable all those applications in Bootstrap?

Not using bootstrap, only Trollstore2, performed a rebuild icon cache on this, there is a way to fix it?

**Comment by opa334** [comment]
I don't see how this could happen.
