### ISSUE TITLE
Is it possible to run an app (like PPSSPP) through JIT by default?

### ISSUE THREAD

**Issue by i1itione** [opa334/TrollStore#724]
Currently, if I want to run PPSSPP through JIT, I need to manually open TrollStore and run it inside. 
If I want to open PPSSPP through JIT directly on the home menu, how should I operate?

**Comment by fasiltahr** [comment]
> Currently, if I want to run PPSSPP through JIT, I need to manually open TrollStore and run it inside. If I want to open PPSSPP through JIT directly on the home menu, how should I operate?
