### ISSUE TITLE
TrollMisaka 2.0 is not a valid name for an app id.

### ISSUE THREAD

**Issue by AbsoluteWarfail** [opa334/TrollStore#726]
I dont know what i'm doing wrong, ive been searching all forums and github issues for a fix but yet still nothing, I'm trying to do the first step of jailbreaking my iPhone 6s yet i cant even do it, tried changing the name with sideloadly but that doesnt work.

Model: Iphone 6s Plus
iOS 15.7.9
Architecture: Arm64

![Uploading C9B95AAE-71CB-4A44-BA12-FDDDC01F2E63.jpeg…]()

**Comment by cxdxn1** [comment]
TrollMisaka sometimes has unresolvable issues. in this case, use palera1n to jailbreak, get the TrollStore helper via Sileo and install the Persistence helper to Tips.

Hope this helped.
