### ISSUE TITLE
problem about uninstall

### ISSUE THREAD

**Issue by BIGBbox** [opa334/TrollStore#73]
after uninstall TrollStore，can't install again，
it crash or reboot when click the install button，and fail

**Comment by BIGBbox** [comment]
![image](https://user-images.githubusercontent.com/52786394/188462004-e5216ac1-143f-457f-83ed-3fa28363d8cc.png) click the close button then crash

**Comment by opa334** [comment]
the close button exits the app, that's normal. reboot and the TrollStore icon should appear.

**Comment by BIGBbox** [comment]
but nothing happened after > the close button exits the app, that's normal. reboot and the TrollStore icon should appear.

**Comment by opa334** [comment]
hmm idk, works for me. maybe a "force reinstall" button could help in the future"
