### ISSUE TITLE
broken system installer

### ISSUE THREAD

**Issue by n0name-o0o0** [opa334/TrollStore#734]
hello, developer of trollstore, here lies a problem after some operations using trollstore2: I can't install package without trollstore ( app store updates-failed but blue dot appear | trollstore install-success | i4tools7-failed with error"ApplicationSINFCaptureFailed")

[video](https://file.garden/Y37nYZOdi23QPRtp/embed/IMG_2797.MP4)

and 

[video2](https://file.garden/Y37nYZOdi23QPRtp/embed/2.mp4)

operations before this condition is i tried the "installd" method of trollstore instalation... then i swithced back, and lter i installed an app from app store and then it appeared.
and i uninstalle an applic using desktop's (it hasnt uninstalled completely)and i installed it back used trollstore
i cant except the reason caused this is using trollstore,so i ask here

**Comment by n0name-o0o0** [comment]
if its not torlltor e's problem,can you tell me possible solution?
also i'm not native english speakers and some grammar bugs

**Comment by opa334** [comment]
Stock bug, has nothing to do with TrollStore.
Only fix that always works is to
1. backup device data
2. wipe device in settings
3. restore from backup

**Comment by n0name-o0o0** [comment]
i think the way to fix this is to install app store signed and not uncecrypted apps in trollstore

**Comment by n0name-o0o0** [comment]
@opa334 my device's dont have shsh2 backup and if i do that will devixe not bpot up maybe?
