### ISSUE TITLE
When will iOS 17.1.x support be available?

### ISSUE THREAD

**Issue by elvis-hp** [opa334/TrollStore#735]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

When will iOS 17.1.x support be available?

### Current Behavior?

When will iOS 17.1.x support be available?

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

NO

### iOS/iPadOS version

17.1.x

### iDevice Model

11

**Comment by Vel-San** [comment]
+1

**Comment by opa334** [comment]
never

**Comment by elvis-hp** [comment]
> never

will support higher 17.1.x like 17.2 17.3 ... right?
