### ISSUE TITLE
iphone 8 ,ios 14.8.1 ,when install trollstore, keyboard crash,device reboot

### ISSUE THREAD

**Issue by biubiue** [opa334/TrollStore#736]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

not crash

### Current Behavior?

follow guide

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

ios 14.8.1

### iDevice Model

iPhone 8

**Comment by jmwangde3** [comment]
same here
