### ISSUE TITLE
ICloud backup and .tipa apps

### ISSUE THREAD

**Issue by Hetyey** [opa334/TrollStore#737]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I should be able to create/refresh iCloud backup clicking the blue "Biztonsági mentés" button here: 
![IMG_7058](https://github.com/opa334/TrollStore/assets/115489259/11654248-1aaa-4a77-816f-eeed1aa64b8d)

### Current Behavior?

If I have .tipa apps installed I am not able to back my device up. ("iCloud backup could not be completed") (Unfortunately I don't have a screenshot from that bc I managed to backup by uninstalling the tipa apps.)

### Possible Solution?

-

### Steps to Reproduce

-Install a .tipa file and try to iCloud backup (Personally I've had the bootstrap, sileo, trollbox installed.)

### TrollStore Version

Trollstore 2.0.12

### iOS/iPadOS version

iOS 17.0

### iDevice Model

iphone 13

**Comment by opa334** [comment]
There is nothing that can be done about this
