### ISSUE TITLE
Can add some feature like this , me Really need it!!

### ISSUE THREAD

**Issue by wothard** [opa334/TrollStore#741]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

i cant pull req, help

### Current Behavior?

some feature

### Possible Solution?

-add feature in new version

### Steps to Reproduce

-
![未标题-1](https://github.com/opa334/TrollStore/assets/15395394/418efccf-7163-4341-9a91-c0e12451e69d)

### TrollStore Version

2.0.12

### iOS/iPadOS version

iOS 16.6.1

### iDevice Model

iPhone 13 pro

**Comment by alfiecg24** [comment]
A proper UI redesign is planned at some point, so for now we will leave this.
