### ISSUE TITLE
Apps not showing until I respring

### ISSUE THREAD

**Issue by derfrogen** [opa334/TrollStore#743]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Apps showing in system right away after they are installed w/ TrollStore

### Current Behavior?

Apps showing only after respring no matter what install settings are used. Until respring, they can be launched only from TrollStore app itself.

### Possible Solution?

-

### TrollStore Version

2.0.12

### iOS/iPadOS version

iOS 16.6.1

### iDevice Model

iPhone 13

**Comment by alfiecg24** [comment]
Did you try running Reload Icon Cache in TrollStore settings?

**Comment by derfrogen** [comment]
I did it multiple times (on 2.0.13 too), the behavior is same

**Comment by opa334** [comment]
This is a stock bug and unrelated to TrollStore.

**Comment by derfrogen** [comment]
Ok it doesn’t bother me a lot anyways

**Comment by ZeR0Ke1th** [comment]
@opa334 I want to dig more into the issue "stock bug" which you mentioned.
Do you have any related ticket or research doc about that?
Appreciate!
