### ISSUE TITLE
Error 181 - Failed to add app to icon cache - Attempting to install Infinity Blade 2

### ISSUE THREAD

**Issue by xSimone** [opa334/TrollStore#746]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

It should install the app. (Infinity Blade 2)

### Current Behavior?

It is giving me an error. 
Error 181 - Failed to add app to icon cache

### Possible Solution?

I do not know what the fix would be, but here is my error log below.
[Log.txt](https://github.com/opa334/TrollStore/files/14488137/Log.txt)

### Steps to Reproduce

https://drive.usercontent.google.com/download?id=1NMNpEWDOBBxb8Vrdc6or4w4WQK5PbhKW&export=download&authuser=0&confirm=t&uuid=c01533eb-def7-4922-852a-ecb51d98e889&at=APZUnTWGDAaGFiaWD1MHsVEa6jVl:1709589991680

(https://drive.google.com/drive/folders/1SLE-Y5u3DYxcTCUl_2LFQcFrrPK--ny6)

Download the IPA from Google
Attempt to Install with TrollStore

Note this app above is not piracy, it is abandoned and the IPA's were given out by the developer given Apple vs Epic fiasco, having their certificate revoked.

### TrollStore Version

TrollStar

### iOS/iPadOS version

16.3

### iDevice Model

iPhone 14 Pro

### Other info of your environment

Windows 11 - Latest

**Comment by opa334** [comment]
This means there is most likely something wrong with the IPA, I can't tell you what and how to fix it though...

**Comment by xSimone** [comment]
> This means there is most likely something wrong with the IPA, I can't tell you what and how to fix it though...

I'll relay it to the guys handling the ipa.

**Comment by xSimone** [comment]
> This means there is most likely something wrong with the IPA, I can't tell you what and how to fix it though...

May I ask, where would I drop a file into /var for TrollStore to read it? 

I'm downloading on a PC, then transferring by cable. Doesn't seem to work, downloading on device does.. but it's annoying that each time installation fails I need to download a 1+gb file again.

**Comment by opa334** [comment]
> > This means there is most likely something wrong with the IPA, I can't tell you what and how to fix it though...
> 
> May I ask, where would I drop a file into /var for TrollStore to read it?
> 
> I'm downloading on a PC, then transferring by cable. Doesn't seem to work, downloading on device does.. but it's annoying that each time installation fails I need to download a 1+gb file again.

What about the files app?

**Comment by xSimone** [comment]
> > > This means there is most likely something wrong with the IPA, I can't tell you what and how to fix it though...
> > 
> > 
> > May I ask, where would I drop a file into /var for TrollStore to read it?
> > I'm downloading on a PC, then transferring by cable. Doesn't seem to work, downloading on device does.. but it's annoying that each time installation fails I need to download a 1+gb file again.
> 
> What about the files app?

I will give that a try. I think you may be right however about it being the IPA.

I tried SideLoadly and it did indeed work, it installed onto the iDevice, however it is ofcourse not installed with TrollStore and doesn't get the permanent signage.. or is there a way for TrollStore to still sign an app installed this way?

I'm unsure how to use the Files app, but I'll give it a try.

**Comment by xSimone** [comment]
Tried with Files app (didn't know I had to scroll down after download) and the same error occurs. 

Install Error 181 - Failed to add app to icon cache

**Comment by xSimone** [comment]
> > Tried with Files app (didn't know I had to scroll down after download) and the same error occurs.
> > Install Error 181 - Failed to add app to icon cache
> 
> I mean, what did you expect? Same ipa, same issue...

Of course. Just ruling out all possibilities. Fixed the IPA, installs now. 

I'll post a different question unless you'd like me to keep it here..

Currently when I install the three Infinity Blade games, they're zoomed in and fill the X axis of the screen, and are chopped off on the Y axis. 

How do I make sure that when TrollStore installs these apps, it sets the resolution to 16:9? 

When SideLoadly is used, the issue doesn't seem to be present, and I've been told by someone it's a TrollStore thing and a custom resolution needs to be dictated. I'm unsure how to do this however. Would you mind giving some insight?

**Comment by opa334** [comment]
> > > Tried with Files app (didn't know I had to scroll down after download) and the same error occurs.
> > > Install Error 181 - Failed to add app to icon cache
> > 
> > 
> > I mean, what did you expect? Same ipa, same issue...
> 
> Of course. Just ruling out all possibilities. Fixed the IPA, installs now.
> 
> I'll post a different question unless you'd like me to keep it here..
> 
> Currently when I install the three Infinity Blade games, they're zoomed in and fill the X axis of the screen, and are chopped off on the Y axis.
> 
> How do I make sure that when TrollStore installs these apps, it sets the resolution to 16:9?
> 
> When SideLoadly is used, the issue doesn't seem to be present, and I've been told by someone it's a TrollStore thing and a custom resolution needs to be dictated. I'm unsure how to do this however. Would you mind giving some insight?

Yes this is an issue with the app being registered as system (at least as far as I know), I have no idea if there is any way to fix this. Anyways closing as the issue was with the IPA (Although I'd be interested what specifically was broken about it?).

**Comment by xSimone** [comment]
They sadly have no idea, they just did some updates, repackaged it and it works.
They even said they doubt it'd fix the issue but it did.

Surely there must be a fix. Someone has shown me using a tool called 'Scarlet' to install the game then getting TrollStore to sign it works. However doing some research I don't think Scarlet is safe, and has lots of malware.
