### ISSUE TITLE
[Bug] [File Sharing] Apps installed via TrollStore are visible in iTunes, but can't be written/read.

### ISSUE THREAD

**Issue by nicolodonvito** [opa334/TrollStore#75]
Hardware utilized:
* iPhone XS (iOS 15.0.1)

Software utilized:
* Windows 10 (21H2)
* iTunes (v12.12.4.1)
* TrollStore (v1.0.6)

Steps to reproduce:
* Install an application via TrollStore
* Go to iTunes - Device icon - File Sharing
* Select the app installed via TrollStore

Expected results:
* See the app's folders and data.

Experienced result:
* iTunes tries to load the app's folder and data for an indefinite time.
![image](https://user-images.githubusercontent.com/12714578/188467952-751d8c05-e8f4-48dc-b62d-aaac11bbf3a9.png)

Additional notes:
* The applications that I tried are "PPSSPP", "Delta emulator", and "FilzaEscaped15". Only "Delta emulator" created a couple of folders in the "On My iPhone" folder in the Files app, but these can't be accessed from iTunes anyway.
* Manually creating a folder with the same name as the app doesn't fix the problem.
* Sideloading the apps make them accessible in the File Sharing on iTunes.

**Comment by Peng1029** [comment]
Maybe try going to their data folder with santar and checking the permissions?

**Comment by nicolodonvito** [comment]
I am sorry, what is "santar"?

**Comment by Peng1029** [comment]
*Santander , it’s like a read only file manager you can install with trollstore, if you install it you could check the permissions of that folder

**Comment by Ulysses1988** [comment]
I have the same problem when i install retroarch applications.

**Comment by opa334** [comment]
I wanted to look into this now, but for me PPSSPP doesn't even show up in Finder

**Comment by opa334** [comment]
Hmm they show up in Windows but not in macOS, really weird, also hard to debug but will check now

**Comment by opa334** [comment]
`Sep  8 18:32:00 iPhone-SE-von-Lars mobile_house_arrest[1189] <Notice>: invalid application type for org.ppsspp.ppsspp: System
Sep  8 18:32:00 iPhone-SE-von-Lars mobile_house_arrest[1189] <Notice>: org.ppsspp.ppsspp is not an allowed app bundle or extension: InstallationLookupFailed`

not sure if this can be fixed as TrollStore relies on installing apps as system apps

**Comment by opa334** [comment]
I got it past that check but still doesn't seem to work and also no other error gets printed, so not sure what else to try

**Comment by opa334** [comment]
"Fix" is included in 1.3. Set registration state to "User", do the iTunes stuff you want to do and when you're done, set it back to "System".
