### ISSUE TITLE
error 168 on incremental build

### ISSUE THREAD

**Issue by Amzd** [opa334/TrollStore#755]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Expected to be able to install an incremental build of a private app

### Current Behavior?

Second install almost always gives error 168

### Possible Solution?

Workaround is respringing

### Steps to Reproduce

- Install an unsigned .ipa
- Build same app with small change
- Install again
- Error 168

### TrollStore Version

2.0.13

### iOS/iPadOS version

iOS 16.6

### iDevice Model

iPhone X (10,6)

**Comment by Amzd** [comment]
Possibly related to #486 but I am able to reproduce this all the time.

**Comment by opa334** [comment]
This is definitely not an issue with TrollStore, the issue is coming from libarchive and can really only be related to something going wrong in the extraction, such as the ipa being corrupted or the device being too low on space to extract it.
