### ISSUE TITLE
fuck opa334 cuz you removed my issue

### ISSUE THREAD

**Issue by opa3344** [opa334/TrollStore#759]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

päö

### Current Behavior?

åäö

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

åäö

### iOS/iPadOS version

åäö

### iDevice Model

åäö

**Comment by opa3344** [comment]
saw this on reddit XD

**Comment by opa3344** [comment]
fuck u/__jonathan0827__

**Comment by opa3344** [comment]
fuck r/jailbreak

**Comment by opa3344** [comment]
i am from finland

**Comment by opa3344** [comment]
evämaa

**Comment by opa3344** [comment]
dewkjhrtfuewhrfuewhriuweh2

**Comment by opa3344** [comment]
ef.kjfgioerjgioerjkfkre

**Comment by opa3344** [comment]
fuck putin

**Comment by opa3344** [comment]
åäö

**Comment by opa3344** [comment]
go to [jailbreaks.app](cydia2.com)

**Comment by 1along** [comment]
八格牙路

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/04/2024 17:39 |
| To | opa334/TrollStore ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | Re: [opa334/TrollStore] fuck opa334 cuz you removed my issue (Issue #759) |

go to jailbreaks.app

**Comment by 1along** [comment]
bageyalu

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/04/2024 17:39 |
| To | opa334/TrollStore ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | Re: [opa334/TrollStore] fuck opa334 cuz you removed my issue (Issue #759) |

go to jailbreaks.app

**Comment by UInt2048** [comment]
It's worth pointing out that the only issues you've opened here are #756 and #762, both of which you opened and closed

**Comment by opa3344** [comment]
this was a prank, dont worry!
