### ISSUE TITLE
Widgets are not working

### ISSUE THREAD

**Issue by itaysharir** [opa334/TrollStore#76]
The title pretty much says it all.

**Comment by opa334** [comment]
they seem to work for some apps apparently, so idk

**Comment by ComeOnBear** [comment]
Have the same issue 
iOS 15.0, iPhone SE 2020 (A13), trollinstaller sideloaded using AltStore
Had issue with V1.0.5 and V1.0.8
example i found: ARMCPUZ (tweaked) on AppDB

**Comment by itaysharir** [comment]
> they seem to work for some apps apparently, so idk

Sorry for the really late response but yeah, turned out I installed a bad ipa. I installed a different ipa and it worked.
