### ISSUE TITLE
Parse Error 301

### ISSUE THREAD

**Issue by Jazooxd** [opa334/TrollStore#765]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

I was expecting my ipa to load like normal, but instead it shows this error while the file is in ipa.

### Current Behavior?

This error appears and ipa will not load

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

Latest version of TrollStore 

### iOS/iPadOS version

iOS 16.1

### iDevice Model

iPhone 10 (X)

### Other info of your environment

i find this issue but the guy closed withot any solution... and idk how to fix it :/

**Comment by Jazooxd** [comment]
`i find this issue but the guy closed withot any solution` #563

my screenshot:
![screenshot](https://github.com/opa334/TrollStore/assets/166530795/f260b34f-8948-489b-af82-01f7f7a9c484)

**Comment by opa334** [comment]
your IPA is broken
