### ISSUE TITLE
A specific app not working.

### ISSUE THREAD

**Issue by satanicang3l** [opa334/TrollStore#77]
Hardware utilized:
    iPhone 11 Pro Max (iOS 15.0.1)

Software utilized:
    TrollStore (v1.0.6)

Steps to reproduce:
    Install the application via TrollStore

Expected results:
    App runs successfully

Experienced result:
    App crashed

Hi there, first of all thank you for the work! This is amazing and works fine for most of the apps I tried.

There is this one app though (a Chinese music playing app) that I have obtained some time ago from some forum. Basically it was modified so that it allows overseas music playing and some other stuffs. I managed to install it when I had jailbreak back then unfortunately it failed to install in jailed mode using Sideloadly. 

When TrollStore got released I immediately tried installing the app (I tried again using 1.06, the latest version but same results) - it successfully gets installed, however attempting to launch just results in a crash.

Could you please help me with this? I know you are busy - no worries, low priority item. Thanks a lot for your great work again!

IPA in question: https://mega.nz/file/iZJ1VboD#Pr8toH-TZ2eiE773nlAg7C73IguuekBvlLHEA0foS4Y

**Comment by opa334** [comment]
The app works fine for me, make sure ldid is installed in TrollStore settings.

**Comment by satanicang3l** [comment]
I have ldid installed. Will try resetting my phone then. Thanks!
