### ISSUE TITLE
Crashed or Close 

### ISSUE THREAD

**Issue by ramunozp** [opa334/TrollStore#78]
install version 1.0.6, try a facebook ipa and when you open the app, it does, but after a few seconds it closes :(

What I can do?

**Comment by opa334** [comment]
make sure ldid is installed in trollstore settings

**Comment by ramunozp** [comment]
the problem persists. why did you close it?
![image](https://user-images.githubusercontent.com/24207310/188524889-2cf7363d-fc88-4f34-8eee-8683489cbbc1.png)


https://user-images.githubusercontent.com/24207310/188525015-0c332ac6-b375-4b15-bb13-8e5c3ed829fc.MP4
