### ISSUE TITLE
Installing TrollStore causes private/var to be mounted as read and write, and the application is detected as jailbreaking

### ISSUE THREAD

**Issue by lc8899ddff** [opa334/TrollStore#780]
Hopefully there will be a way to mount as read/write

**Comment by roothider** [comment]
> /private/var is always mounted read/write

It is read-only by default in lower versions of iOS 15

**Comment by opa334** [comment]
> > /private/var is always mounted read/write
> 
> 
> 
> It is read-only by default in lower versions of iOS 15

We were talking about `/private/var`, not about `/private/preboot`.

**Comment by roothider** [comment]
> > > /private/var is always mounted read/write
> > 
> > 
> > It is read-only by default in lower versions of iOS 15
> 
> We were talking about `/private/var`, not about `/private/preboot`.

Why does he say this will lead to jailbreak detection?

**Comment by roothider** [comment]
oh I guess what he meant is that some apps installed in trollstore create some extra files in /private/var/ that cause jailbreak detection
