### ISSUE TITLE
Is Persistence Helper a mandatory installation？

### ISSUE THREAD

**Issue by Norton12138** [opa334/TrollStore#785]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

This is a small question, I hope someone in the community can answer it for me.

### Current Behavior?

Currently, I am using an IOS14.0.1 device and have installed TrollInstaller2 but not Persistence Helper. After restarting my device, TrollInstaller2 is still functioning normally. I would like to confirm if Persistence Helper is not needed in the IOS14 environment.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

IOS14.0.1

### iDevice Model

iPhone X

**Comment by SleepingPig35** [comment]
No, is it **possible** to use TrollStore without the Persistence Helper.

However, when you restart the app registrations or reboot, TrollStore is **deleted from the iPhone**; this can be stopped by using the Persistence Helper so **it is recommended to use it**.

**Comment by opa334** [comment]
wtf is TrollInstaller 2? Use TrollHelperOTA, you can also use that as a persistence helper.
