### ISSUE TITLE
UTM does not work

### ISSUE THREAD

**Issue by ChrisGleich1AufsMaul** [opa334/TrollStore#79]
I've noticed that UTM does not work, when it was installed via TrollStore.
But it's not that important. Thanks anyway :)

**Comment by opa334** [comment]
Does UTM need JIT? If so, then that's impossible on iOS 15 because JIT entitlements are locked behind PPL now. AltJIT is the only way to have JIT.

**Comment by ChrisGleich1AufsMaul** [comment]
Yeah it does 
I'm not quite sure if you know what I mean 😅 
the entire app does not work. UTM crashes on launch
... Just to be clear :D

**Comment by opa334** [comment]
The UTM IPA has the dynamic-codesigning entitlement, probably for when you install it on jailbroken iOS 14 devices or something.

But on iOS 15 this entitlement is completely forbidden, apps with it will not launch, that's what you observe here.

**Comment by ChrisGleich1AufsMaul** [comment]
Dang, too bad 😬
Thanks for explaining and your encouragement, man!

**Comment by nicolodonvito** [comment]
@ChrisGleich1AufsMaul There is another version of UTM, called "UTM-SE", it works in iOS 15 without jailbreak. You can download it from the same GitHub repo. I tested it on my iPhone XS running iOS 15.0.1 and it works

**Comment by ChrisGleich1AufsMaul** [comment]
@nicolodonvito ah interesting. But it works probably very slowly, right?

**Comment by nicolodonvito** [comment]
Unfortunately, yes. I tested the Debian 10.4 (Minimal) pre-made VM, but even a simple task required a few minutes. I also tested the Debian 10.4 (Xfce) VM, but it froze at the beginning. You can try and see if you are luckier!

**Comment by ChrisGleich1AufsMaul** [comment]
@nicolodonvito too bad
Thanks man!

**Comment by nicolodonvito** [comment]
You are welcome!

**Comment by plooshi** [comment]
4.0.4 (beta) normal version works out of the box on my a10 ipad 6

**Comment by bigemon** [comment]
> I've noticed that UTM does not work, when it was installed via TrollStore. But it's not that important. Thanks anyway :)

After updating my UTM APP, I had the same problem. 
The final solution is shown below：

① UTM versions after 4.0 now provide a Release called 'UTM.HV.ipa'. you can find it in the Pre-release link [UTM_V407.HV.ipa](https://github.com/utmapp/UTM/releases/download/v4.0.7/UTM.HV.ipa)

②Install this HV version of UTM using the TrollStore

③Install [Jitterbug](https://github.com/osy/Jitterbug) using TorllStore 

④Follow the Jitterbug installation manual to configure the pairing file and developer support dmg file 
[xcode-developer-disk-image-all-platforms](https://github.com/haikieu/xcode-developer-disk-image-all-platforms)

⑤ Use Jitterbug to launch HV version of UTM

⑥If everything goes well, you should not get JIT errors.

⑦Enjoy it

My device is: iPadMini6 
IpadOSVersion: 15.4.1

hope it can help you

![run_winxp](https://user-images.githubusercontent.com/3683548/196246701-71b70097-483b-4b2f-a549-a34542e4ea10.png)
![UTM_HV](https://user-images.githubusercontent.com/3683548/196246722-834867c1-a368-4fd3-b707-a0dbedcedae9.png)
![MyVersion](https://user-images.githubusercontent.com/3683548/196246725-b1b30ea6-4b05-4f87-bf7b-4b93cf76ed19.png)
![UsingJitterbug](https://user-images.githubusercontent.com/3683548/196246729-afd01825-4bc6-41bc-802e-5649a1c35ac8.png)
