### ISSUE TITLE
TrollStore will be detected by third-party apps

### ISSUE THREAD

**Issue by DevelopCubeLab** [opa334/TrollStore#793]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

OP-mobile 66.0.1 and 66.0.6 and 65.0.0 can run.

### Current Behavior?

When I run OP-mobile (a bank application https://apps.apple.com/fi/app/op-mobile/id767393591) it can detected TrollStore, this app need an Finland app store account to download.  
In previous versions of op-mobile, if the device has Filza installed with url scheme, op will not run, but in the new version, it will still be detected without Filza, and TrollStore will work regardless of whether url scheme is enabled.

### Possible Solution?

I don't understand how this app detects TrollStore, it's incredible

### Steps to Reproduce

After installing TrollStore and opening the op-mobile app, it will prompt that the device is not secure. I don’t know how such powerful detection is achieved.

### TrollStore Version

2.0.15

### iOS/iPadOS version

iOS 15.3.1, iOS 15.6RC1, iOS 16.6.1

### iDevice Model

iPhone 13 mini

**Comment by DevelopCubeLab** [comment]
![IMG_5895](https://github.com/opa334/TrollStore/assets/38208636/206023e0-25ab-45a1-96b1-000c008e0ed3)

**Comment by opaa334** [comment]
torilla tavataan!  ite oon suomalainen pränkkitili.

**Comment by opaa334** [comment]
pränkkään opa334 tyyppiä

**Comment by opaa334** [comment]
ja voinko runkkaa verkkokauppa comissa

**Comment by opaa334** [comment]
![Tori fi-Logo](https://github.com/opa334/TrollStore/assets/173428707/25895ebf-c46b-412b-ad65-06d9f43ac9ea)

**Comment by opaa334** [comment]
laita kännykkä tonne myyntiin

**Comment by roothider** [comment]
try roothide

**Comment by DevelopCubeLab** [comment]
> try roothide

The problem has been detected. It is not TrollStore, but Filza's file problem.

**Comment by roothider** [comment]
> > try roothide
> 
> The problem has been detected. It is not TrollStore, but Filza's file problem.

roothide will also make Filza undetectable

**Comment by DevelopCubeLab** [comment]
> > > try roothide
> > 
> > 
> > The problem has been detected. It is not TrollStore, but Filza's file problem.
> 
> roothide will also make Filza undetectable

There is no need to do this because my device only has TrollStore and I already found all the detection points and I deleted them all.

/var/mobile/Library/Caches/com.tigisoftware.Filza

/var/mobile/Library/SplashBoard/Snapshots/com.tigisoftware.Filza

/var/mobile/Library/Application Support/Containers/com.tigisoftware.Filza

/var/mobile/Library/Saved Application State/com.tigisoftware.Filza.savedState

/var/mobile/Library/Preferences/com.tigisoftware.Filza.plist

/var/mobile/Library/HTTPStorages/com.tigisoftware.Filza

/var/mobile/Library/Filza

**Comment by roothider** [comment]
> > > > try roothide
> > > 
> > > 
> > > The problem has been detected. It is not TrollStore, but Filza's file problem.
> > 
> > 
> > roothide will also make Filza undetectable
> 
> There is no need to do this because my device only has TrollStore and I already found all the detection points and I deleted them all.
> 
> /var/mobile/Library/Caches/com.tigisoftware.Filza
> 
> /var/mobile/Library/SplashBoard/Snapshots/com.tigisoftware.Filza
> 
> /var/mobile/Library/Application Support/Containers/com.tigisoftware.Filza
> 
> /var/mobile/Library/Saved Application State/com.tigisoftware.Filza.savedState
> 
> /var/mobile/Library/Preferences/com.tigisoftware.Filza.plist
> 
> /var/mobile/Library/HTTPStorages/com.tigisoftware.Filza
> 
> /var/mobile/Library/Filza

with roothide varClean, it can automatically scan all these files that may cause jailbreak detection
