### ISSUE TITLE
trollstore disappeared!

### ISSUE THREAD

**Issue by FrittersOuO** [opa334/TrollStore#804]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

trollstore icon should be there to lunch 

### Current Behavior?

Persistence Helper on mail is fine,says i’m installed trollstore,but after downloading some random apps,the trollstore icon disappeared.
![E79A17DE-A5D0-4A51-8BAB-0B301F5F42C7](https://github.com/opa334/TrollStore/assets/173804699/96901391-3f8f-4fd4-bd4c-b440cadeec5b)

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

trollstore 1

### iOS/iPadOS version

14.7.1

### iDevice Model

iPhone 8(10,1) NQ7X2LL/A A1863

### Other info of your environment

didn’t jail break

**Comment by opa334** [comment]
Press "Refresh App Registrations", that's why it exists...

**Comment by FrittersOuO** [comment]
> Press "Refresh App Registrations", that's why it exists...



> Press "Refresh App Registrations", that's why it exists...
i tried it didn’t work,that’s why i’m reporting
