### ISSUE TITLE
麦克风问题

### ISSUE THREAD

**Issue by Luyao666888** [opa334/TrollStore#808]
Hello, occasionally when using apps in the Chinese region with Trolls 2, the microphone fails to start properly, and the issue occurs frequently when using WeChat. Given that WeChat is a widely used messaging app in China, the impact is significant. I hope you can address this issue (Trolls 1 does not have this problem). Please, thank you.🙏

**Comment by Hwatu** [comment]
ditto, Please, thank you.🙏

**Comment by opa334** [comment]
Duplicate of #657
