### ISSUE TITLE
 Compilation problems

### ISSUE THREAD

**Issue by guotaoeunke** [opa334/TrollStore#819]
When I compiled TrollStore with theos, this problem occurred. I don’t know how to solve it. I look forward to your reply.
![Snip20240725_1](https://github.com/user-attachments/assets/6ca9b955-b575-463c-9026-c94f813d92de)

**Comment by opa334** [comment]
fastPathSign should have been compiled earlier in the build process, not sure what the problem is but this isn't a support forum either.
