### ISSUE TITLE
ppsspp Emulator

### ISSUE THREAD

**Issue by MrBrownie124** [opa334/TrollStore#82]
when installing ppsspp its supposed to make a file for you to put your games in, in troll store it dose not work. To test this i installed it with sideloadly and it worked as usual.

**Comment by notbugme** [comment]
the same issue ...

**Comment by H1deMe** [comment]
Same here
1.0.8 still not fixed
But retroarch is good working

**Comment by opa334** [comment]
duplicate of https://github.com/opa334/TrollStore/issues/75
