### ISSUE TITLE
"Open with JIT" not an option for some apps

### ISSUE THREAD

**Issue by Khazmar10** [opa334/TrollStore#827]
Why do some apps have the option to be "open with JIT" and some aren't. I'm trying to install this game through trollstore but there is not option to run with JIT. I'm currently using sideloadly to launch with JIT but it's a hassle and I much prefer just using the trollstore directly. 

Link of the ipa: https://app.iosgods.com/store/appdetails/4456-idle-ninja-online-hack.

TrollStore 2.0.15
iPhone SE3
iOS 15.6.1
Dopamine 2.2.1

Thank you for the time and effort. Much appreciated.

**Comment by opa334** [comment]
iOS only allows enabling JIT on apps that are signed with the `get-task-allow` entitlement.
