### ISSUE TITLE
Possible to preserve app data?

### ISSUE THREAD

**Issue by ak4zh** [opa334/TrollStore#83]
If you update an app by opening updated version of IPA TrollStore completely wipes the app data.
Is it possible to allow upgrading just the app and data stays just like how we upgrade from app store?

**Comment by opa334** [comment]
that shouldn't happen, the data should not be touched by updating, I will check soon

**Comment by ak4zh** [comment]
I tested with [Watusi](https://github.com/FouadRaheb/Watusi-for-WhatsApp)

1) Installed App > Setup my account > Made some chats
2) Downloaded same IPA again and opened in TrollStore
3) Opened the installed app all data is gone and I had to re-setup the account.

**Comment by opa334** [comment]
I'm 90% sure the problem is that that Watusi IPA stores chats in a different location than stock WhatsApp. Use the recently published properly entitled version of Watusi.

Anyways I installed the stock IPA on top of the proper Watusi version and everything works, can't reproduce.
