### ISSUE TITLE
Install error 168 - Minecraft Pe

### ISSUE THREAD

**Issue by Huynhagiau1** [opa334/TrollStore#858]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Uh i expected it to download successfully 

### Current Behavior?

Idk but when i install Minecraft pe 1.20.81 Ipa File with 900+ mb it alway said “Install error 168” and something like can’t extract ipa file i don’t rememer but yeah this is it

### Possible Solution?

-

### Steps to Reproduce

2024-12-03 20:33:37.859 trollstorehelper[33029:679882] trollstorehelper invoked with arguments: (
    install,
    custom,
    "/private/var/mobile/Containers/Shared/AppGroup/14CADA39-8469-4F87-AF46-C543A6EDA2CA/File Provider Storage/Downloads/Minecraft_1.20.81_LeTi.ipa"
)
Write failed
Write failed
Write to restore size failed
2024-12-03 20:33:44.584 trollstorehelper[33029:679882] trollstorehelper returning 168

### TrollStore Version

Trollstore 2.1

### iOS/iPadOS version

Ios 15.7.3

### iDevice Model

iPhone 6s

**Comment by bradleytechman** [comment]
You will have to use a new iPA file.
