### ISSUE TITLE
Install Error 173 when installing apps on iPad 9, iOS 15.1

### ISSUE THREAD

**Issue by Pomi108** [opa334/TrollStore#87]
I installed the TrollStore installer via AltStore, opened the app then hit the install button. The app seems to have installed properly, no errors were thrown. However, when I try to open any IPA in TrollStore, it gives me this error: 
![obrazek](https://user-images.githubusercontent.com/59484948/188691791-a9334ae5-5624-4287-b146-14f8d44b2913.png)
As you can see, Idid is installed.

**Comment by opa334** [comment]
The only possible way for this to happen is if

A) ldid is not installed

B) ldid returned with a non zero exit code (can probably only happen if your ipa is broken)

**Comment by opa334** [comment]
try uninstalling TrollStore and installing it again, maybe ldid installation is corrupted or something

**Comment by zh121084** [comment]
![1662551734401](https://user-images.githubusercontent.com/113029426/188872483-6ddb258d-4d0c-4b35-93ea-4832832108e7.jpg)
I don't know how to solve this problem

**Comment by opa334** [comment]
This happens when something is wrong with your internet connection.

**Comment by Pomi108** [comment]
Ah thanks, I reinstalled TrollStore properly now and everything's working this time. The first time I did it i uninstalled TrollStore from the home screen and I think that was the issue
