### ISSUE TITLE
The "fullscreen" issue

### ISSUE THREAD

**Issue by TripleB114** [opa334/TrollStore#94]
I don't know if the trollstore will make any change to the app, but when I install an old app which does not support full screen through trollstore, the old app seems to be forced to support full screen. And the UI is going wrong. But it is ok when I use other installer such as sideloadly, the app is not fullscreen and the UI does not go wrong. So I just want to request for an answer.
My English sucks because I am not an English user and sorry for bothering you..

**Comment by TripleB114** [comment]
> 

I forgot to say, "full screen" refers to iphoneX and up.

**Comment by opa334** [comment]
Seems to be impossible to fix

**Comment by bewl87** [comment]
i have this problem too, anyone found a work around? maybe a .dylib injected into the ipa before installing ![image](https://github.com/opa334/TrollStore/assets/49694850/253123bf-024d-40b9-bc17-7d7710fe4f24)![image](https://github.com/opa334/TrollStore/assets/49694850/aee34be3-5cd3-47be-ba90-0b9088ac3992)
