### ISSUE TITLE
Install error 173 while IDID installed

### ISSUE THREAD

**Issue by henryglends** [opa334/TrollStore#96]
I cant sideload an app, even though I have IDID installed. On 1.0.7 and it won’t work
Edit: it was just the specific IPA causing it

**Comment by opa334** [comment]
can you send me such an IPA?

**Comment by henryglends** [comment]
Sure, here

https://github.com/ginsudev/YTMusicUltimate/releases/tag/Update

**Comment by mailinglists35** [comment]
still broken with ytmusicultimate.

deleting the app and installing with AppStore = finds saved account, prompts to use account and works
deleting the app and installing with Sideloadly = finds saved account and uses it, skipping account choice
deleting the app and installing with Trollstore = shows first use screen, prompts sign in then denies logon with any account

https://user-images.githubusercontent.com/2054302/191264418-65e03cab-697a-4477-a2aa-16e593048273.png

https://user-images.githubusercontent.com/2054302/191264344-55100b65-a574-485b-99cc-16f505f84d11.jpeg

**Comment by mailinglists35** [comment]
15.1.1 iphone14,4

**Comment by opa334** [comment]
this is an issue with the IPA and not with TrollStore
