### ISSUE TITLE
Error 173 appeared when installing Kodi

### ISSUE THREAD

**Issue by heinekenpsx** [opa334/TrollStore#99]
Other apps install normally, so i'm guessing the error comes from Kodi itself. When i use Azule tool (by Al4ise) to change some information of Kodi, error: Couldn't set app rpath
@opa334, do you know what rpath is?
https://ibb.co/TgPhxq9
https://ibb.co/k5hgwYP

**Comment by n0k0m3** [comment]
@opa334 maybe not, kodi ipa works with AltStore as per #92

**Comment by Gghuzr** [comment]
Kodi 18.9 Leia.ipa is working like a charm, but Matrix 19.x.ipa is not working until now.

**Comment by migue30479** [comment]
> Kodi 18.9 Leia.ipa is working like a charm, but Matrix 19.x.ipa is not working until now.

Can u share 18.9 ipa?
